/* tslint:disable */
/* eslint-disable */
/**
 * apollo-rest-api
 * The Apollo API provides programmatic access to [Apollo](https://www.apollo.io/), the all-in-one sales intelligence and engagement platform. Use it to enrich people and company data (individually or in bulk), search Apollo\'s database of over 230 million contacts and 30 million companies, and manage accounts, contacts, deals, sequences, tasks, calls, and conversations in your go-to-market workflows.  ## Base URL  All API requests are made to `https://api.apollo.io/api/v1`.  ## Authentication  - **Apollo users** authenticate with an API key passed in the `x-api-key` request header. See [Create API Keys](https://docs.apollo.io/docs/create-api-key). - **Apollo partners** building integrations on behalf of mutual users authenticate with the [OAuth 2.0 authorization flow](https://docs.apollo.io/docs/use-oauth-20-authorization-flow-to-access-apollo-user-information-partners).  ## Rate limits & credits  Rate limits and credit consumption depend on your [Apollo pricing plan](https://docs.apollo.io/docs/api-pricing). Check your current limits and usage with the [View API Usage Stats and Rate Limits](https://docs.apollo.io/reference/view-api-usage-stats) endpoint. For more details, see [Rate Limits](https://docs.apollo.io/reference/rate-limits) and the [API FAQs](https://docs.apollo.io/docs/apollo-api-faqs).  New to the API? Start with the [Apollo API Overview](https://docs.apollo.io/docs/apollo-api-overview).
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AddContactsToSequence200ResponseEmailerCampaignUniqueScheduled } from './AddContactsToSequence200ResponseEmailerCampaignUniqueScheduled';
import {
    AddContactsToSequence200ResponseEmailerCampaignUniqueScheduledFromJSON,
    AddContactsToSequence200ResponseEmailerCampaignUniqueScheduledFromJSONTyped,
    AddContactsToSequence200ResponseEmailerCampaignUniqueScheduledToJSON,
    AddContactsToSequence200ResponseEmailerCampaignUniqueScheduledToJSONTyped,
} from './AddContactsToSequence200ResponseEmailerCampaignUniqueScheduled';

/**
 * 
 * @export
 * @interface AddContactsToSequence200ResponseEmailerCampaignContactStatuses
 */
export interface AddContactsToSequence200ResponseEmailerCampaignContactStatuses {
    /**
     * 
     * @type {AddContactsToSequence200ResponseEmailerCampaignUniqueScheduled}
     * @memberof AddContactsToSequence200ResponseEmailerCampaignContactStatuses
     */
    active?: AddContactsToSequence200ResponseEmailerCampaignUniqueScheduled;
    /**
     * 
     * @type {number}
     * @memberof AddContactsToSequence200ResponseEmailerCampaignContactStatuses
     */
    failed?: number;
    /**
     * 
     * @type {AddContactsToSequence200ResponseEmailerCampaignUniqueScheduled}
     * @memberof AddContactsToSequence200ResponseEmailerCampaignContactStatuses
     */
    paused?: AddContactsToSequence200ResponseEmailerCampaignUniqueScheduled;
    /**
     * 
     * @type {AddContactsToSequence200ResponseEmailerCampaignUniqueScheduled}
     * @memberof AddContactsToSequence200ResponseEmailerCampaignContactStatuses
     */
    finished?: AddContactsToSequence200ResponseEmailerCampaignUniqueScheduled;
    /**
     * 
     * @type {AddContactsToSequence200ResponseEmailerCampaignUniqueScheduled}
     * @memberof AddContactsToSequence200ResponseEmailerCampaignContactStatuses
     */
    bounced?: AddContactsToSequence200ResponseEmailerCampaignUniqueScheduled;
}

/**
 * Check if a given object implements the AddContactsToSequence200ResponseEmailerCampaignContactStatuses interface.
 */
export function instanceOfAddContactsToSequence200ResponseEmailerCampaignContactStatuses(value: object): value is AddContactsToSequence200ResponseEmailerCampaignContactStatuses {
    return true;
}

export function AddContactsToSequence200ResponseEmailerCampaignContactStatusesFromJSON(json: any): AddContactsToSequence200ResponseEmailerCampaignContactStatuses {
    return AddContactsToSequence200ResponseEmailerCampaignContactStatusesFromJSONTyped(json, false);
}

export function AddContactsToSequence200ResponseEmailerCampaignContactStatusesFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddContactsToSequence200ResponseEmailerCampaignContactStatuses {
    if (json == null) {
        return json;
    }
    return {
        
        'active': json['active'] == null ? undefined : AddContactsToSequence200ResponseEmailerCampaignUniqueScheduledFromJSON(json['active']),
        'failed': json['failed'] == null ? undefined : json['failed'],
        'paused': json['paused'] == null ? undefined : AddContactsToSequence200ResponseEmailerCampaignUniqueScheduledFromJSON(json['paused']),
        'finished': json['finished'] == null ? undefined : AddContactsToSequence200ResponseEmailerCampaignUniqueScheduledFromJSON(json['finished']),
        'bounced': json['bounced'] == null ? undefined : AddContactsToSequence200ResponseEmailerCampaignUniqueScheduledFromJSON(json['bounced']),
    };
}

export function AddContactsToSequence200ResponseEmailerCampaignContactStatusesToJSON(json: any): AddContactsToSequence200ResponseEmailerCampaignContactStatuses {
    return AddContactsToSequence200ResponseEmailerCampaignContactStatusesToJSONTyped(json, false);
}

export function AddContactsToSequence200ResponseEmailerCampaignContactStatusesToJSONTyped(value?: AddContactsToSequence200ResponseEmailerCampaignContactStatuses | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'active': AddContactsToSequence200ResponseEmailerCampaignUniqueScheduledToJSON(value['active']),
        'failed': value['failed'],
        'paused': AddContactsToSequence200ResponseEmailerCampaignUniqueScheduledToJSON(value['paused']),
        'finished': AddContactsToSequence200ResponseEmailerCampaignUniqueScheduledToJSON(value['finished']),
        'bounced': AddContactsToSequence200ResponseEmailerCampaignUniqueScheduledToJSON(value['bounced']),
    };
}

