/* tslint:disable */
/* eslint-disable */
/**
 * apollo-rest-api
 * The Apollo API provides programmatic access to [Apollo](https://www.apollo.io/), the all-in-one sales intelligence and engagement platform. Use it to enrich people and company data (individually or in bulk), search Apollo\'s database of over 230 million contacts and 30 million companies, and manage accounts, contacts, deals, sequences, tasks, calls, and conversations in your go-to-market workflows.  ## Base URL  All API requests are made to `https://api.apollo.io/api/v1`.  ## Authentication  - **Apollo users** authenticate with an API key passed in the `x-api-key` request header. See [Create API Keys](https://docs.apollo.io/docs/create-api-key). - **Apollo partners** building integrations on behalf of mutual users authenticate with the [OAuth 2.0 authorization flow](https://docs.apollo.io/docs/use-oauth-20-authorization-flow-to-access-apollo-user-information-partners).  ## Rate limits & credits  Rate limits and credit consumption depend on your [Apollo pricing plan](https://docs.apollo.io/docs/api-pricing). Check your current limits and usage with the [View API Usage Stats and Rate Limits](https://docs.apollo.io/reference/view-api-usage-stats) endpoint. For more details, see [Rate Limits](https://docs.apollo.io/reference/rate-limits) and the [API FAQs](https://docs.apollo.io/docs/apollo-api-faqs).  New to the API? Start with the [Apollo API Overview](https://docs.apollo.io/docs/apollo-api-overview).
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AddContactsToSequence200ResponseEmailerStepsInner } from './AddContactsToSequence200ResponseEmailerStepsInner';
import {
    AddContactsToSequence200ResponseEmailerStepsInnerFromJSON,
    AddContactsToSequence200ResponseEmailerStepsInnerFromJSONTyped,
    AddContactsToSequence200ResponseEmailerStepsInnerToJSON,
    AddContactsToSequence200ResponseEmailerStepsInnerToJSONTyped,
} from './AddContactsToSequence200ResponseEmailerStepsInner';
import type { AddContactsToSequence200ResponseTeam } from './AddContactsToSequence200ResponseTeam';
import {
    AddContactsToSequence200ResponseTeamFromJSON,
    AddContactsToSequence200ResponseTeamFromJSONTyped,
    AddContactsToSequence200ResponseTeamToJSON,
    AddContactsToSequence200ResponseTeamToJSONTyped,
} from './AddContactsToSequence200ResponseTeam';
import type { AddContactsToSequence200ResponseContactsInner } from './AddContactsToSequence200ResponseContactsInner';
import {
    AddContactsToSequence200ResponseContactsInnerFromJSON,
    AddContactsToSequence200ResponseContactsInnerFromJSONTyped,
    AddContactsToSequence200ResponseContactsInnerToJSON,
    AddContactsToSequence200ResponseContactsInnerToJSONTyped,
} from './AddContactsToSequence200ResponseContactsInner';
import type { AddContactsToSequence200ResponseSkippedContactIds } from './AddContactsToSequence200ResponseSkippedContactIds';
import {
    AddContactsToSequence200ResponseSkippedContactIdsFromJSON,
    AddContactsToSequence200ResponseSkippedContactIdsFromJSONTyped,
    AddContactsToSequence200ResponseSkippedContactIdsToJSON,
    AddContactsToSequence200ResponseSkippedContactIdsToJSONTyped,
} from './AddContactsToSequence200ResponseSkippedContactIds';
import type { AddContactsToSequence200ResponseEmailerTouchesInner } from './AddContactsToSequence200ResponseEmailerTouchesInner';
import {
    AddContactsToSequence200ResponseEmailerTouchesInnerFromJSON,
    AddContactsToSequence200ResponseEmailerTouchesInnerFromJSONTyped,
    AddContactsToSequence200ResponseEmailerTouchesInnerToJSON,
    AddContactsToSequence200ResponseEmailerTouchesInnerToJSONTyped,
} from './AddContactsToSequence200ResponseEmailerTouchesInner';
import type { AddContactsToSequence200ResponseEmailerCampaign } from './AddContactsToSequence200ResponseEmailerCampaign';
import {
    AddContactsToSequence200ResponseEmailerCampaignFromJSON,
    AddContactsToSequence200ResponseEmailerCampaignFromJSONTyped,
    AddContactsToSequence200ResponseEmailerCampaignToJSON,
    AddContactsToSequence200ResponseEmailerCampaignToJSONTyped,
} from './AddContactsToSequence200ResponseEmailerCampaign';

/**
 * 
 * @export
 * @interface AddContactsToSequence200Response
 */
export interface AddContactsToSequence200Response {
    /**
     * Array of contacts that were successfully added to the sequence
     * @type {Array<AddContactsToSequence200ResponseContactsInner>}
     * @memberof AddContactsToSequence200Response
     */
    contacts: Array<AddContactsToSequence200ResponseContactsInner>;
    /**
     * 
     * @type {AddContactsToSequence200ResponseSkippedContactIds}
     * @memberof AddContactsToSequence200Response
     */
    skippedContactIds: AddContactsToSequence200ResponseSkippedContactIds;
    /**
     * 
     * @type {AddContactsToSequence200ResponseEmailerCampaign}
     * @memberof AddContactsToSequence200Response
     */
    emailerCampaign: AddContactsToSequence200ResponseEmailerCampaign;
    /**
     * Array of sequence steps
     * @type {Array<AddContactsToSequence200ResponseEmailerStepsInner>}
     * @memberof AddContactsToSequence200Response
     */
    emailerSteps: Array<AddContactsToSequence200ResponseEmailerStepsInner>;
    /**
     * Array of email templates/touches for the sequence
     * @type {Array<AddContactsToSequence200ResponseEmailerTouchesInner>}
     * @memberof AddContactsToSequence200Response
     */
    emailerTouches: Array<AddContactsToSequence200ResponseEmailerTouchesInner>;
    /**
     * 
     * @type {AddContactsToSequence200ResponseTeam}
     * @memberof AddContactsToSequence200Response
     */
    team: AddContactsToSequence200ResponseTeam;
    /**
     * Optional signals data for play recommendations and analytics
     * @type {object}
     * @memberof AddContactsToSequence200Response
     */
    signalsHash?: object;
}

/**
 * Check if a given object implements the AddContactsToSequence200Response interface.
 */
export function instanceOfAddContactsToSequence200Response(value: object): value is AddContactsToSequence200Response {
    if (!('contacts' in value) || value['contacts'] === undefined) return false;
    if ((!('skippedContactIds' in value) && !('skipped_contact_ids' in value)) || (value['skippedContactIds'] === undefined && value['skipped_contact_ids'] === undefined)) return false;
    if ((!('emailerCampaign' in value) && !('emailer_campaign' in value)) || (value['emailerCampaign'] === undefined && value['emailer_campaign'] === undefined)) return false;
    if ((!('emailerSteps' in value) && !('emailer_steps' in value)) || (value['emailerSteps'] === undefined && value['emailer_steps'] === undefined)) return false;
    if ((!('emailerTouches' in value) && !('emailer_touches' in value)) || (value['emailerTouches'] === undefined && value['emailer_touches'] === undefined)) return false;
    if (!('team' in value) || value['team'] === undefined) return false;
    return true;
}

export function AddContactsToSequence200ResponseFromJSON(json: any): AddContactsToSequence200Response {
    return AddContactsToSequence200ResponseFromJSONTyped(json, false);
}

export function AddContactsToSequence200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddContactsToSequence200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'contacts': ((json['contacts'] as Array<any>).map(AddContactsToSequence200ResponseContactsInnerFromJSON)),
        'skippedContactIds': AddContactsToSequence200ResponseSkippedContactIdsFromJSON(json['skipped_contact_ids']),
        'emailerCampaign': AddContactsToSequence200ResponseEmailerCampaignFromJSON(json['emailer_campaign']),
        'emailerSteps': ((json['emailer_steps'] as Array<any>).map(AddContactsToSequence200ResponseEmailerStepsInnerFromJSON)),
        'emailerTouches': ((json['emailer_touches'] as Array<any>).map(AddContactsToSequence200ResponseEmailerTouchesInnerFromJSON)),
        'team': AddContactsToSequence200ResponseTeamFromJSON(json['team']),
        'signalsHash': json['signals_hash'] == null ? undefined : json['signals_hash'],
    };
}

export function AddContactsToSequence200ResponseToJSON(json: any): AddContactsToSequence200Response {
    return AddContactsToSequence200ResponseToJSONTyped(json, false);
}

export function AddContactsToSequence200ResponseToJSONTyped(value?: AddContactsToSequence200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'contacts': ((value['contacts'] as Array<any>).map(AddContactsToSequence200ResponseContactsInnerToJSON)),
        'skipped_contact_ids': AddContactsToSequence200ResponseSkippedContactIdsToJSON(value['skippedContactIds']),
        'emailer_campaign': AddContactsToSequence200ResponseEmailerCampaignToJSON(value['emailerCampaign']),
        'emailer_steps': ((value['emailerSteps'] as Array<any>).map(AddContactsToSequence200ResponseEmailerStepsInnerToJSON)),
        'emailer_touches': ((value['emailerTouches'] as Array<any>).map(AddContactsToSequence200ResponseEmailerTouchesInnerToJSON)),
        'team': AddContactsToSequence200ResponseTeamToJSON(value['team']),
        'signals_hash': value['signalsHash'],
    };
}

