/* tslint:disable */
/* eslint-disable */
/**
 * apollo-rest-api
 * The Apollo API provides programmatic access to [Apollo](https://www.apollo.io/), the all-in-one sales intelligence and engagement platform. Use it to enrich people and company data (individually or in bulk), search Apollo\'s database of over 230 million contacts and 30 million companies, and manage accounts, contacts, deals, sequences, tasks, calls, and conversations in your go-to-market workflows.  ## Base URL  All API requests are made to `https://api.apollo.io/api/v1`.  ## Authentication  - **Apollo users** authenticate with an API key passed in the `x-api-key` request header. See [Create API Keys](https://docs.apollo.io/docs/create-api-key). - **Apollo partners** building integrations on behalf of mutual users authenticate with the [OAuth 2.0 authorization flow](https://docs.apollo.io/docs/use-oauth-20-authorization-flow-to-access-apollo-user-information-partners).  ## Rate limits & credits  Rate limits and credit consumption depend on your [Apollo pricing plan](https://docs.apollo.io/docs/api-pricing). Check your current limits and usage with the [View API Usage Stats and Rate Limits](https://docs.apollo.io/reference/view-api-usage-stats) endpoint. For more details, see [Rate Limits](https://docs.apollo.io/reference/rate-limits) and the [API FAQs](https://docs.apollo.io/docs/apollo-api-faqs).  New to the API? Start with the [Apollo API Overview](https://docs.apollo.io/docs/apollo-api-overview).
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BulkPeopleEnrichment200ResponseMatchesInner } from './BulkPeopleEnrichment200ResponseMatchesInner';
import {
    BulkPeopleEnrichment200ResponseMatchesInnerFromJSON,
    BulkPeopleEnrichment200ResponseMatchesInnerFromJSONTyped,
    BulkPeopleEnrichment200ResponseMatchesInnerToJSON,
    BulkPeopleEnrichment200ResponseMatchesInnerToJSONTyped,
} from './BulkPeopleEnrichment200ResponseMatchesInner';

/**
 * 
 * @export
 * @interface BulkPeopleEnrichment200Response
 */
export interface BulkPeopleEnrichment200Response {
    /**
     * The request ID for the enrichment request. Save this ID to map this request with the corresponding webhook result.
     * @type {number}
     * @memberof BulkPeopleEnrichment200Response
     */
    requestId?: number;
    /**
     * 
     * @type {string}
     * @memberof BulkPeopleEnrichment200Response
     */
    status?: string;
    /**
     * 
     * @type {any}
     * @memberof BulkPeopleEnrichment200Response
     */
    errorCode?: any | null;
    /**
     * 
     * @type {any}
     * @memberof BulkPeopleEnrichment200Response
     */
    errorMessage?: any | null;
    /**
     * 
     * @type {number}
     * @memberof BulkPeopleEnrichment200Response
     */
    totalRequestedEnrichments?: number;
    /**
     * 
     * @type {number}
     * @memberof BulkPeopleEnrichment200Response
     */
    uniqueEnrichedRecords?: number;
    /**
     * 
     * @type {number}
     * @memberof BulkPeopleEnrichment200Response
     */
    missingRecords?: number;
    /**
     * 
     * @type {number}
     * @memberof BulkPeopleEnrichment200Response
     */
    creditsConsumed?: number;
    /**
     * 
     * @type {Array<BulkPeopleEnrichment200ResponseMatchesInner>}
     * @memberof BulkPeopleEnrichment200Response
     */
    matches?: Array<BulkPeopleEnrichment200ResponseMatchesInner>;
}

/**
 * Check if a given object implements the BulkPeopleEnrichment200Response interface.
 */
export function instanceOfBulkPeopleEnrichment200Response(value: object): value is BulkPeopleEnrichment200Response {
    return true;
}

export function BulkPeopleEnrichment200ResponseFromJSON(json: any): BulkPeopleEnrichment200Response {
    return BulkPeopleEnrichment200ResponseFromJSONTyped(json, false);
}

export function BulkPeopleEnrichment200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): BulkPeopleEnrichment200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'requestId': json['request_id'] == null ? undefined : json['request_id'],
        'status': json['status'] == null ? undefined : json['status'],
        'errorCode': json['error_code'] == null ? undefined : json['error_code'],
        'errorMessage': json['error_message'] == null ? undefined : json['error_message'],
        'totalRequestedEnrichments': json['total_requested_enrichments'] == null ? undefined : json['total_requested_enrichments'],
        'uniqueEnrichedRecords': json['unique_enriched_records'] == null ? undefined : json['unique_enriched_records'],
        'missingRecords': json['missing_records'] == null ? undefined : json['missing_records'],
        'creditsConsumed': json['credits_consumed'] == null ? undefined : json['credits_consumed'],
        'matches': json['matches'] == null ? undefined : ((json['matches'] as Array<any>).map(BulkPeopleEnrichment200ResponseMatchesInnerFromJSON)),
    };
}

export function BulkPeopleEnrichment200ResponseToJSON(json: any): BulkPeopleEnrichment200Response {
    return BulkPeopleEnrichment200ResponseToJSONTyped(json, false);
}

export function BulkPeopleEnrichment200ResponseToJSONTyped(value?: BulkPeopleEnrichment200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'request_id': value['requestId'],
        'status': value['status'],
        'error_code': value['errorCode'],
        'error_message': value['errorMessage'],
        'total_requested_enrichments': value['totalRequestedEnrichments'],
        'unique_enriched_records': value['uniqueEnrichedRecords'],
        'missing_records': value['missingRecords'],
        'credits_consumed': value['creditsConsumed'],
        'matches': value['matches'] == null ? undefined : ((value['matches'] as Array<any>).map(BulkPeopleEnrichment200ResponseMatchesInnerToJSON)),
    };
}

