/* tslint:disable */
/* eslint-disable */
/**
 * apollo-rest-api
 * The Apollo API provides programmatic access to [Apollo](https://www.apollo.io/), the all-in-one sales intelligence and engagement platform. Use it to enrich people and company data (individually or in bulk), search Apollo\'s database of over 230 million contacts and 30 million companies, and manage accounts, contacts, deals, sequences, tasks, calls, and conversations in your go-to-market workflows.  ## Base URL  All API requests are made to `https://api.apollo.io/api/v1`.  ## Authentication  - **Apollo users** authenticate with an API key passed in the `x-api-key` request header. See [Create API Keys](https://docs.apollo.io/docs/create-api-key). - **Apollo partners** building integrations on behalf of mutual users authenticate with the [OAuth 2.0 authorization flow](https://docs.apollo.io/docs/use-oauth-20-authorization-flow-to-access-apollo-user-information-partners).  ## Rate limits & credits  Rate limits and credit consumption depend on your [Apollo pricing plan](https://docs.apollo.io/docs/api-pricing). Check your current limits and usage with the [View API Usage Stats and Rate Limits](https://docs.apollo.io/reference/view-api-usage-stats) endpoint. For more details, see [Rate Limits](https://docs.apollo.io/reference/rate-limits) and the [API FAQs](https://docs.apollo.io/docs/apollo-api-faqs).  New to the API? Start with the [Apollo API Overview](https://docs.apollo.io/docs/apollo-api-overview).
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BulkUpdateAccountsRequestAccountAttributesInner } from './BulkUpdateAccountsRequestAccountAttributesInner';
import {
    BulkUpdateAccountsRequestAccountAttributesInnerFromJSON,
    BulkUpdateAccountsRequestAccountAttributesInnerFromJSONTyped,
    BulkUpdateAccountsRequestAccountAttributesInnerToJSON,
    BulkUpdateAccountsRequestAccountAttributesInnerToJSONTyped,
} from './BulkUpdateAccountsRequestAccountAttributesInner';

/**
 * 
 * @export
 * @interface BulkUpdateAccountsRequest
 */
export interface BulkUpdateAccountsRequest {
    /**
     * Array of account IDs to update with the same values. Use this for applying the same updates to multiple accounts.
     * @type {Array<string>}
     * @memberof BulkUpdateAccountsRequest
     */
    accountIds?: Array<string>;
    /**
     * Array of account objects with individual updates. Use this for applying different updates to each account.
     * @type {Array<BulkUpdateAccountsRequestAccountAttributesInner>}
     * @memberof BulkUpdateAccountsRequest
     */
    accountAttributes?: Array<BulkUpdateAccountsRequestAccountAttributesInner>;
    /**
     * When using account_ids, apply this name to all accounts
     * @type {string}
     * @memberof BulkUpdateAccountsRequest
     */
    name?: string;
    /**
     * When using account_ids, apply this owner to all accounts
     * @type {string}
     * @memberof BulkUpdateAccountsRequest
     */
    ownerId?: string;
    /**
     * When using account_ids, apply this account stage to all accounts
     * @type {string}
     * @memberof BulkUpdateAccountsRequest
     */
    accountStageId?: string;
    /**
     * Set to true to process updates asynchronously. Only available when using account_ids. Not supported with account_attributes.
     * @type {boolean}
     * @memberof BulkUpdateAccountsRequest
     */
    async?: boolean;
}

/**
 * Check if a given object implements the BulkUpdateAccountsRequest interface.
 */
export function instanceOfBulkUpdateAccountsRequest(value: object): value is BulkUpdateAccountsRequest {
    return true;
}

export function BulkUpdateAccountsRequestFromJSON(json: any): BulkUpdateAccountsRequest {
    return BulkUpdateAccountsRequestFromJSONTyped(json, false);
}

export function BulkUpdateAccountsRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): BulkUpdateAccountsRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'accountIds': json['account_ids'] == null ? undefined : json['account_ids'],
        'accountAttributes': json['account_attributes'] == null ? undefined : ((json['account_attributes'] as Array<any>).map(BulkUpdateAccountsRequestAccountAttributesInnerFromJSON)),
        'name': json['name'] == null ? undefined : json['name'],
        'ownerId': json['owner_id'] == null ? undefined : json['owner_id'],
        'accountStageId': json['account_stage_id'] == null ? undefined : json['account_stage_id'],
        'async': json['async'] == null ? undefined : json['async'],
    };
}

export function BulkUpdateAccountsRequestToJSON(json: any): BulkUpdateAccountsRequest {
    return BulkUpdateAccountsRequestToJSONTyped(json, false);
}

export function BulkUpdateAccountsRequestToJSONTyped(value?: BulkUpdateAccountsRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'account_ids': value['accountIds'],
        'account_attributes': value['accountAttributes'] == null ? undefined : ((value['accountAttributes'] as Array<any>).map(BulkUpdateAccountsRequestAccountAttributesInnerToJSON)),
        'name': value['name'],
        'owner_id': value['ownerId'],
        'account_stage_id': value['accountStageId'],
        'async': value['async'],
    };
}

