/* tslint:disable */
/* eslint-disable */
/**
 * apollo-rest-api
 * The Apollo API provides programmatic access to [Apollo](https://www.apollo.io/), the all-in-one sales intelligence and engagement platform. Use it to enrich people and company data (individually or in bulk), search Apollo\'s database of over 230 million contacts and 30 million companies, and manage accounts, contacts, deals, sequences, tasks, calls, and conversations in your go-to-market workflows.  ## Base URL  All API requests are made to `https://api.apollo.io/api/v1`.  ## Authentication  - **Apollo users** authenticate with an API key passed in the `x-api-key` request header. See [Create API Keys](https://docs.apollo.io/docs/create-api-key). - **Apollo partners** building integrations on behalf of mutual users authenticate with the [OAuth 2.0 authorization flow](https://docs.apollo.io/docs/use-oauth-20-authorization-flow-to-access-apollo-user-information-partners).  ## Rate limits & credits  Rate limits and credit consumption depend on your [Apollo pricing plan](https://docs.apollo.io/docs/api-pricing). Check your current limits and usage with the [View API Usage Stats and Rate Limits](https://docs.apollo.io/reference/view-api-usage-stats) endpoint. For more details, see [Rate Limits](https://docs.apollo.io/reference/rate-limits) and the [API FAQs](https://docs.apollo.io/docs/apollo-api-faqs).  New to the API? Start with the [Apollo API Overview](https://docs.apollo.io/docs/apollo-api-overview).
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BulkUpdateContacts200ResponseOneOfContactsInner
 */
export interface BulkUpdateContacts200ResponseOneOfContactsInner {
    /**
     * 
     * @type {string}
     * @memberof BulkUpdateContacts200ResponseOneOfContactsInner
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof BulkUpdateContacts200ResponseOneOfContactsInner
     */
    firstName?: string;
    /**
     * 
     * @type {string}
     * @memberof BulkUpdateContacts200ResponseOneOfContactsInner
     */
    lastName?: string;
    /**
     * 
     * @type {string}
     * @memberof BulkUpdateContacts200ResponseOneOfContactsInner
     */
    email?: string;
    /**
     * 
     * @type {string}
     * @memberof BulkUpdateContacts200ResponseOneOfContactsInner
     */
    title?: string;
    /**
     * 
     * @type {string}
     * @memberof BulkUpdateContacts200ResponseOneOfContactsInner
     */
    organizationName?: string;
    /**
     * 
     * @type {string}
     * @memberof BulkUpdateContacts200ResponseOneOfContactsInner
     */
    ownerId?: string;
    /**
     * 
     * @type {string}
     * @memberof BulkUpdateContacts200ResponseOneOfContactsInner
     */
    accountId?: string;
    /**
     * 
     * @type {string}
     * @memberof BulkUpdateContacts200ResponseOneOfContactsInner
     */
    presentRawAddress?: string;
    /**
     * 
     * @type {string}
     * @memberof BulkUpdateContacts200ResponseOneOfContactsInner
     */
    linkedinUrl?: string;
    /**
     * 
     * @type {Date}
     * @memberof BulkUpdateContacts200ResponseOneOfContactsInner
     */
    updatedAt?: Date;
}

/**
 * Check if a given object implements the BulkUpdateContacts200ResponseOneOfContactsInner interface.
 */
export function instanceOfBulkUpdateContacts200ResponseOneOfContactsInner(value: object): value is BulkUpdateContacts200ResponseOneOfContactsInner {
    return true;
}

export function BulkUpdateContacts200ResponseOneOfContactsInnerFromJSON(json: any): BulkUpdateContacts200ResponseOneOfContactsInner {
    return BulkUpdateContacts200ResponseOneOfContactsInnerFromJSONTyped(json, false);
}

export function BulkUpdateContacts200ResponseOneOfContactsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): BulkUpdateContacts200ResponseOneOfContactsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'firstName': json['first_name'] == null ? undefined : json['first_name'],
        'lastName': json['last_name'] == null ? undefined : json['last_name'],
        'email': json['email'] == null ? undefined : json['email'],
        'title': json['title'] == null ? undefined : json['title'],
        'organizationName': json['organization_name'] == null ? undefined : json['organization_name'],
        'ownerId': json['owner_id'] == null ? undefined : json['owner_id'],
        'accountId': json['account_id'] == null ? undefined : json['account_id'],
        'presentRawAddress': json['present_raw_address'] == null ? undefined : json['present_raw_address'],
        'linkedinUrl': json['linkedin_url'] == null ? undefined : json['linkedin_url'],
        'updatedAt': json['updated_at'] == null ? undefined : (new Date(json['updated_at'])),
    };
}

export function BulkUpdateContacts200ResponseOneOfContactsInnerToJSON(json: any): BulkUpdateContacts200ResponseOneOfContactsInner {
    return BulkUpdateContacts200ResponseOneOfContactsInnerToJSONTyped(json, false);
}

export function BulkUpdateContacts200ResponseOneOfContactsInnerToJSONTyped(value?: BulkUpdateContacts200ResponseOneOfContactsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'first_name': value['firstName'],
        'last_name': value['lastName'],
        'email': value['email'],
        'title': value['title'],
        'organization_name': value['organizationName'],
        'owner_id': value['ownerId'],
        'account_id': value['accountId'],
        'present_raw_address': value['presentRawAddress'],
        'linkedin_url': value['linkedinUrl'],
        'updated_at': value['updatedAt'] == null ? value['updatedAt'] : value['updatedAt'].toISOString(),
    };
}

