/* tslint:disable */
/* eslint-disable */
/**
 * apollo-rest-api
 * The Apollo API provides programmatic access to [Apollo](https://www.apollo.io/), the all-in-one sales intelligence and engagement platform. Use it to enrich people and company data (individually or in bulk), search Apollo\'s database of over 230 million contacts and 30 million companies, and manage accounts, contacts, deals, sequences, tasks, calls, and conversations in your go-to-market workflows.  ## Base URL  All API requests are made to `https://api.apollo.io/api/v1`.  ## Authentication  - **Apollo users** authenticate with an API key passed in the `x-api-key` request header. See [Create API Keys](https://docs.apollo.io/docs/create-api-key). - **Apollo partners** building integrations on behalf of mutual users authenticate with the [OAuth 2.0 authorization flow](https://docs.apollo.io/docs/use-oauth-20-authorization-flow-to-access-apollo-user-information-partners).  ## Rate limits & credits  Rate limits and credit consumption depend on your [Apollo pricing plan](https://docs.apollo.io/docs/api-pricing). Check your current limits and usage with the [View API Usage Stats and Rate Limits](https://docs.apollo.io/reference/view-api-usage-stats) endpoint. For more details, see [Rate Limits](https://docs.apollo.io/reference/rate-limits) and the [API FAQs](https://docs.apollo.io/docs/apollo-api-faqs).  New to the API? Start with the [Apollo API Overview](https://docs.apollo.io/docs/apollo-api-overview).
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BulkCreateContacts200ResponseCreatedContactsInner
 */
export interface BulkCreateContacts200ResponseCreatedContactsInner {
    /**
     * Contact ID
     * @type {string}
     * @memberof BulkCreateContacts200ResponseCreatedContactsInner
     */
    id?: string;
    /**
     * Contact's first name
     * @type {string}
     * @memberof BulkCreateContacts200ResponseCreatedContactsInner
     */
    firstName?: string;
    /**
     * Contact's last name
     * @type {string}
     * @memberof BulkCreateContacts200ResponseCreatedContactsInner
     */
    lastName?: string;
    /**
     * Contact's email address
     * @type {string}
     * @memberof BulkCreateContacts200ResponseCreatedContactsInner
     */
    email?: string;
    /**
     * Contact's job title
     * @type {string}
     * @memberof BulkCreateContacts200ResponseCreatedContactsInner
     */
    title?: string;
    /**
     * Company/organization name
     * @type {string}
     * @memberof BulkCreateContacts200ResponseCreatedContactsInner
     */
    organizationName?: string;
    /**
     * Team ID
     * @type {string}
     * @memberof BulkCreateContacts200ResponseCreatedContactsInner
     */
    teamId?: string;
    /**
     * Contact owner ID
     * @type {string}
     * @memberof BulkCreateContacts200ResponseCreatedContactsInner
     */
    ownerId?: string;
    /**
     * Contact stage ID
     * @type {string}
     * @memberof BulkCreateContacts200ResponseCreatedContactsInner
     */
    contactStageId?: string;
    /**
     * Contact creation timestamp
     * @type {Date}
     * @memberof BulkCreateContacts200ResponseCreatedContactsInner
     */
    createdAt?: Date;
    /**
     * Contact last update timestamp
     * @type {Date}
     * @memberof BulkCreateContacts200ResponseCreatedContactsInner
     */
    updatedAt?: Date;
}

/**
 * Check if a given object implements the BulkCreateContacts200ResponseCreatedContactsInner interface.
 */
export function instanceOfBulkCreateContacts200ResponseCreatedContactsInner(value: object): value is BulkCreateContacts200ResponseCreatedContactsInner {
    return true;
}

export function BulkCreateContacts200ResponseCreatedContactsInnerFromJSON(json: any): BulkCreateContacts200ResponseCreatedContactsInner {
    return BulkCreateContacts200ResponseCreatedContactsInnerFromJSONTyped(json, false);
}

export function BulkCreateContacts200ResponseCreatedContactsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): BulkCreateContacts200ResponseCreatedContactsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'firstName': json['first_name'] == null ? undefined : json['first_name'],
        'lastName': json['last_name'] == null ? undefined : json['last_name'],
        'email': json['email'] == null ? undefined : json['email'],
        'title': json['title'] == null ? undefined : json['title'],
        'organizationName': json['organization_name'] == null ? undefined : json['organization_name'],
        'teamId': json['team_id'] == null ? undefined : json['team_id'],
        'ownerId': json['owner_id'] == null ? undefined : json['owner_id'],
        'contactStageId': json['contact_stage_id'] == null ? undefined : json['contact_stage_id'],
        'createdAt': json['created_at'] == null ? undefined : (new Date(json['created_at'])),
        'updatedAt': json['updated_at'] == null ? undefined : (new Date(json['updated_at'])),
    };
}

export function BulkCreateContacts200ResponseCreatedContactsInnerToJSON(json: any): BulkCreateContacts200ResponseCreatedContactsInner {
    return BulkCreateContacts200ResponseCreatedContactsInnerToJSONTyped(json, false);
}

export function BulkCreateContacts200ResponseCreatedContactsInnerToJSONTyped(value?: BulkCreateContacts200ResponseCreatedContactsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'first_name': value['firstName'],
        'last_name': value['lastName'],
        'email': value['email'],
        'title': value['title'],
        'organization_name': value['organizationName'],
        'team_id': value['teamId'],
        'owner_id': value['ownerId'],
        'contact_stage_id': value['contactStageId'],
        'created_at': value['createdAt'] == null ? value['createdAt'] : value['createdAt'].toISOString(),
        'updated_at': value['updatedAt'] == null ? value['updatedAt'] : value['updatedAt'].toISOString(),
    };
}

