/* tslint:disable */
/* eslint-disable */
/**
 * apollo-rest-api
 * The Apollo API provides programmatic access to [Apollo](https://www.apollo.io/), the all-in-one sales intelligence and engagement platform. Use it to enrich people and company data (individually or in bulk), search Apollo\'s database of over 230 million contacts and 30 million companies, and manage accounts, contacts, deals, sequences, tasks, calls, and conversations in your go-to-market workflows.  ## Base URL  All API requests are made to `https://api.apollo.io/api/v1`.  ## Authentication  - **Apollo users** authenticate with an API key passed in the `x-api-key` request header. See [Create API Keys](https://docs.apollo.io/docs/create-api-key). - **Apollo partners** building integrations on behalf of mutual users authenticate with the [OAuth 2.0 authorization flow](https://docs.apollo.io/docs/use-oauth-20-authorization-flow-to-access-apollo-user-information-partners).  ## Rate limits & credits  Rate limits and credit consumption depend on your [Apollo pricing plan](https://docs.apollo.io/docs/api-pricing). Check your current limits and usage with the [View API Usage Stats and Rate Limits](https://docs.apollo.io/reference/view-api-usage-stats) endpoint. For more details, see [Rate Limits](https://docs.apollo.io/reference/rate-limits) and the [API FAQs](https://docs.apollo.io/docs/apollo-api-faqs).  New to the API? Start with the [Apollo API Overview](https://docs.apollo.io/docs/apollo-api-overview).
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ChooseValidSortByFieldOption
 */
export interface ChooseValidSortByFieldOption {
    /**
     * 
     * @type {string}
     * @memberof ChooseValidSortByFieldOption
     */
    error?: string;
    /**
     * 
     * @type {boolean}
     * @memberof ChooseValidSortByFieldOption
     */
    skipAlertDialog?: boolean;
}

/**
 * Check if a given object implements the ChooseValidSortByFieldOption interface.
 */
export function instanceOfChooseValidSortByFieldOption(value: object): value is ChooseValidSortByFieldOption {
    return true;
}

export function ChooseValidSortByFieldOptionFromJSON(json: any): ChooseValidSortByFieldOption {
    return ChooseValidSortByFieldOptionFromJSONTyped(json, false);
}

export function ChooseValidSortByFieldOptionFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChooseValidSortByFieldOption {
    if (json == null) {
        return json;
    }
    return {
        
        'error': json['error'] == null ? undefined : json['error'],
        'skipAlertDialog': json['skip_alert_dialog'] == null ? undefined : json['skip_alert_dialog'],
    };
}

export function ChooseValidSortByFieldOptionToJSON(json: any): ChooseValidSortByFieldOption {
    return ChooseValidSortByFieldOptionToJSONTyped(json, false);
}

export function ChooseValidSortByFieldOptionToJSONTyped(value?: ChooseValidSortByFieldOption | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'error': value['error'],
        'skip_alert_dialog': value['skipAlertDialog'],
    };
}

