/* tslint:disable */
/* eslint-disable */
/**
 * apollo-rest-api
 * The Apollo API provides programmatic access to [Apollo](https://www.apollo.io/), the all-in-one sales intelligence and engagement platform. Use it to enrich people and company data (individually or in bulk), search Apollo\'s database of over 230 million contacts and 30 million companies, and manage accounts, contacts, deals, sequences, tasks, calls, and conversations in your go-to-market workflows.  ## Base URL  All API requests are made to `https://api.apollo.io/api/v1`.  ## Authentication  - **Apollo users** authenticate with an API key passed in the `x-api-key` request header. See [Create API Keys](https://docs.apollo.io/docs/create-api-key). - **Apollo partners** building integrations on behalf of mutual users authenticate with the [OAuth 2.0 authorization flow](https://docs.apollo.io/docs/use-oauth-20-authorization-flow-to-access-apollo-user-information-partners).  ## Rate limits & credits  Rate limits and credit consumption depend on your [Apollo pricing plan](https://docs.apollo.io/docs/api-pricing). Check your current limits and usage with the [View API Usage Stats and Rate Limits](https://docs.apollo.io/reference/view-api-usage-stats) endpoint. For more details, see [Rate Limits](https://docs.apollo.io/reference/rate-limits) and the [API FAQs](https://docs.apollo.io/docs/apollo-api-faqs).  New to the API? Start with the [Apollo API Overview](https://docs.apollo.io/docs/apollo-api-overview).
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CompleteATask200ResponseTask } from './CompleteATask200ResponseTask';
import {
    CompleteATask200ResponseTaskFromJSON,
    CompleteATask200ResponseTaskFromJSONTyped,
    CompleteATask200ResponseTaskToJSON,
    CompleteATask200ResponseTaskToJSONTyped,
} from './CompleteATask200ResponseTask';
import type { GetATask200ResponseTaskContact } from './GetATask200ResponseTaskContact';
import {
    GetATask200ResponseTaskContactFromJSON,
    GetATask200ResponseTaskContactFromJSONTyped,
    GetATask200ResponseTaskContactToJSON,
    GetATask200ResponseTaskContactToJSONTyped,
} from './GetATask200ResponseTaskContact';

/**
 * 
 * @export
 * @interface CompleteATask200Response
 */
export interface CompleteATask200Response {
    /**
     * 
     * @type {CompleteATask200ResponseTask}
     * @memberof CompleteATask200Response
     */
    task?: CompleteATask200ResponseTask;
    /**
     * 
     * @type {GetATask200ResponseTaskContact}
     * @memberof CompleteATask200Response
     */
    contact?: GetATask200ResponseTaskContact;
}

/**
 * Check if a given object implements the CompleteATask200Response interface.
 */
export function instanceOfCompleteATask200Response(value: object): value is CompleteATask200Response {
    return true;
}

export function CompleteATask200ResponseFromJSON(json: any): CompleteATask200Response {
    return CompleteATask200ResponseFromJSONTyped(json, false);
}

export function CompleteATask200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CompleteATask200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'task': json['task'] == null ? undefined : CompleteATask200ResponseTaskFromJSON(json['task']),
        'contact': json['contact'] == null ? undefined : GetATask200ResponseTaskContactFromJSON(json['contact']),
    };
}

export function CompleteATask200ResponseToJSON(json: any): CompleteATask200Response {
    return CompleteATask200ResponseToJSONTyped(json, false);
}

export function CompleteATask200ResponseToJSONTyped(value?: CompleteATask200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'task': CompleteATask200ResponseTaskToJSON(value['task']),
        'contact': GetATask200ResponseTaskContactToJSON(value['contact']),
    };
}

