/* tslint:disable */
/* eslint-disable */
/**
 * apollo-rest-api
 * The Apollo API provides programmatic access to [Apollo](https://www.apollo.io/), the all-in-one sales intelligence and engagement platform. Use it to enrich people and company data (individually or in bulk), search Apollo\'s database of over 230 million contacts and 30 million companies, and manage accounts, contacts, deals, sequences, tasks, calls, and conversations in your go-to-market workflows.  ## Base URL  All API requests are made to `https://api.apollo.io/api/v1`.  ## Authentication  - **Apollo users** authenticate with an API key passed in the `x-api-key` request header. See [Create API Keys](https://docs.apollo.io/docs/create-api-key). - **Apollo partners** building integrations on behalf of mutual users authenticate with the [OAuth 2.0 authorization flow](https://docs.apollo.io/docs/use-oauth-20-authorization-flow-to-access-apollo-user-information-partners).  ## Rate limits & credits  Rate limits and credit consumption depend on your [Apollo pricing plan](https://docs.apollo.io/docs/api-pricing). Check your current limits and usage with the [View API Usage Stats and Rate Limits](https://docs.apollo.io/reference/view-api-usage-stats) endpoint. For more details, see [Rate Limits](https://docs.apollo.io/reference/rate-limits) and the [API FAQs](https://docs.apollo.io/docs/apollo-api-faqs).  New to the API? Start with the [Apollo API Overview](https://docs.apollo.io/docs/apollo-api-overview).
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateATaskRequest
 */
export interface CreateATaskRequest {
    /**
     * The ID for the task owner within your team's Apollo account. This is the user that will take action on the contacts. <br><br>Use the <a href="https://docs.apollo.io/reference/get-a-list-of-users" target="_blank">Get a List of Users endpoint</a> to retrieve IDs for all of the users within your Apollo account. <br><br>Example: `66302798d03b9601c7934ebf`
     * @type {string}
     * @memberof CreateATaskRequest
     */
    userId: string;
    /**
     * The Apollo ID for the contact that you want to be on the receiving end of the action. <br><br>To find contact IDs, call the <a href="https://docs.apollo.io/reference/search-for-contacts" target="_blank">Search for Contacts endpoint</a> and identify the `id` value for the contact. <br><br>Example: `66e34b81740c50074e3d1bd4`
     * @type {string}
     * @memberof CreateATaskRequest
     */
    contactId: string;
    /**
     * Set the task to be 1 of the following task types. This enables the task owner to know the type of action they need to take. <ul> <li> `call`: Call the contact. </li> <li> `outreach_manual_email`: Email the contact. </li> <li> `linkedin_step_connect`: Send a LinkedIn invitation to connect with the contact. </li> <li> `linkedin_step_message`: Send a direct message to the contact's LinkedIn profile. </li> <li> `linkedin_step_view_profile`: View the contact's LinkedIn profile. </li> <li> `linkedin_step_interact_post`: Interact with the contact's recent LinkedIn posts. </li> <li> `action_item`: Take generic action for the contact. If you use this task type, Apollo recommends using the `note` parameter too. </li> </ul>
     * @type {string}
     * @memberof CreateATaskRequest
     */
    type: string;
    /**
     * Assign a priority to the task you are creating: <ul> <li> `high` </li> <li> `medium` </li> <li> `low` </li> </ul>
     * @type {string}
     * @memberof CreateATaskRequest
     */
    priority?: string;
    /**
     * The status of the task being created. For future-facing tasks, you should use the `scheduled` status. <br><br>For tasks that are already completed, you can use `completed` or `skipped`. <br><br>Example: `scheduled`
     * @type {string}
     * @memberof CreateATaskRequest
     */
    status: string;
    /**
     * The full date and time when the task will be due. <br><br>Your entry should adhere to the <a href="https://www.rfc-editor.org/rfc/rfc3339#section-5.6" target="_blank">ISO 8601 date-time format</a>. Apollo uses Greenwich Mean Time (GMT) by default. If you do not account for time zone differences, you could add a task due date that falls on a different day than you intended. <br><br>The value you enter can either adhere to GMT, or you can adjust the time manually by specifying in hours and minutes how much you want to offset GMT.<br><br>Example: `2025-02-15T08:10:30Z`; `2025-03-25T10:15:30+05:00`
     * @type {Date}
     * @memberof CreateATaskRequest
     */
    dueAt: Date;
    /**
     * A title for the task. If omitted, Apollo will display an auto-generated title based on the task type and contact name. <br><br>Example: `Follow up on demo request`
     * @type {string}
     * @memberof CreateATaskRequest
     */
    title?: string;
    /**
     * Add a description for the task. This should be a human-readable message. <br><br>This parameter is not required, but it is recommended as it provides the task owner with more context on the action they need to take. <br><br>Example: `This contact expressed interest in the Sequences feature specifically. Be prepared to discuss.`
     * @type {string}
     * @memberof CreateATaskRequest
     */
    note?: string;
}

/**
 * Check if a given object implements the CreateATaskRequest interface.
 */
export function instanceOfCreateATaskRequest(value: object): value is CreateATaskRequest {
    if ((!('userId' in value) && !('user_id' in value)) || (value['userId'] === undefined && value['user_id'] === undefined)) return false;
    if ((!('contactId' in value) && !('contact_id' in value)) || (value['contactId'] === undefined && value['contact_id'] === undefined)) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if ((!('dueAt' in value) && !('due_at' in value)) || (value['dueAt'] === undefined && value['due_at'] === undefined)) return false;
    return true;
}

export function CreateATaskRequestFromJSON(json: any): CreateATaskRequest {
    return CreateATaskRequestFromJSONTyped(json, false);
}

export function CreateATaskRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateATaskRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'userId': json['user_id'],
        'contactId': json['contact_id'],
        'type': json['type'],
        'priority': json['priority'] == null ? undefined : json['priority'],
        'status': json['status'],
        'dueAt': (new Date(json['due_at'])),
        'title': json['title'] == null ? undefined : json['title'],
        'note': json['note'] == null ? undefined : json['note'],
    };
}

export function CreateATaskRequestToJSON(json: any): CreateATaskRequest {
    return CreateATaskRequestToJSONTyped(json, false);
}

export function CreateATaskRequestToJSONTyped(value?: CreateATaskRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'user_id': value['userId'],
        'contact_id': value['contactId'],
        'type': value['type'],
        'priority': value['priority'],
        'status': value['status'],
        'due_at': value['dueAt'].toISOString(),
        'title': value['title'],
        'note': value['note'],
    };
}

