/* tslint:disable */
/* eslint-disable */
/**
 * apollo-rest-api
 * The Apollo API provides programmatic access to [Apollo](https://www.apollo.io/), the all-in-one sales intelligence and engagement platform. Use it to enrich people and company data (individually or in bulk), search Apollo\'s database of over 230 million contacts and 30 million companies, and manage accounts, contacts, deals, sequences, tasks, calls, and conversations in your go-to-market workflows.  ## Base URL  All API requests are made to `https://api.apollo.io/api/v1`.  ## Authentication  - **Apollo users** authenticate with an API key passed in the `x-api-key` request header. See [Create API Keys](https://docs.apollo.io/docs/create-api-key). - **Apollo partners** building integrations on behalf of mutual users authenticate with the [OAuth 2.0 authorization flow](https://docs.apollo.io/docs/use-oauth-20-authorization-flow-to-access-apollo-user-information-partners).  ## Rate limits & credits  Rate limits and credit consumption depend on your [Apollo pricing plan](https://docs.apollo.io/docs/api-pricing). Check your current limits and usage with the [View API Usage Stats and Rate Limits](https://docs.apollo.io/reference/view-api-usage-stats) endpoint. For more details, see [Rate Limits](https://docs.apollo.io/reference/rate-limits) and the [API FAQs](https://docs.apollo.io/docs/apollo-api-faqs).  New to the API? Start with the [Apollo API Overview](https://docs.apollo.io/docs/apollo-api-overview).
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateSequence200ResponseEmailerTouchesInner
 */
export interface CreateSequence200ResponseEmailerTouchesInner {
    /**
     * 
     * @type {string}
     * @memberof CreateSequence200ResponseEmailerTouchesInner
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateSequence200ResponseEmailerTouchesInner
     */
    emailerStepId?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateSequence200ResponseEmailerTouchesInner
     */
    emailerTemplateId?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateSequence200ResponseEmailerTouchesInner
     */
    status?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateSequence200ResponseEmailerTouchesInner
     */
    type?: string;
}

/**
 * Check if a given object implements the CreateSequence200ResponseEmailerTouchesInner interface.
 */
export function instanceOfCreateSequence200ResponseEmailerTouchesInner(value: object): value is CreateSequence200ResponseEmailerTouchesInner {
    return true;
}

export function CreateSequence200ResponseEmailerTouchesInnerFromJSON(json: any): CreateSequence200ResponseEmailerTouchesInner {
    return CreateSequence200ResponseEmailerTouchesInnerFromJSONTyped(json, false);
}

export function CreateSequence200ResponseEmailerTouchesInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateSequence200ResponseEmailerTouchesInner {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'emailerStepId': json['emailer_step_id'] == null ? undefined : json['emailer_step_id'],
        'emailerTemplateId': json['emailer_template_id'] == null ? undefined : json['emailer_template_id'],
        'status': json['status'] == null ? undefined : json['status'],
        'type': json['type'] == null ? undefined : json['type'],
    };
}

export function CreateSequence200ResponseEmailerTouchesInnerToJSON(json: any): CreateSequence200ResponseEmailerTouchesInner {
    return CreateSequence200ResponseEmailerTouchesInnerToJSONTyped(json, false);
}

export function CreateSequence200ResponseEmailerTouchesInnerToJSONTyped(value?: CreateSequence200ResponseEmailerTouchesInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'emailer_step_id': value['emailerStepId'],
        'emailer_template_id': value['emailerTemplateId'],
        'status': value['status'],
        'type': value['type'],
    };
}

