/* tslint:disable */
/* eslint-disable */
/**
 * apollo-rest-api
 * The Apollo API provides programmatic access to [Apollo](https://www.apollo.io/), the all-in-one sales intelligence and engagement platform. Use it to enrich people and company data (individually or in bulk), search Apollo\'s database of over 230 million contacts and 30 million companies, and manage accounts, contacts, deals, sequences, tasks, calls, and conversations in your go-to-market workflows.  ## Base URL  All API requests are made to `https://api.apollo.io/api/v1`.  ## Authentication  - **Apollo users** authenticate with an API key passed in the `x-api-key` request header. See [Create API Keys](https://docs.apollo.io/docs/create-api-key). - **Apollo partners** building integrations on behalf of mutual users authenticate with the [OAuth 2.0 authorization flow](https://docs.apollo.io/docs/use-oauth-20-authorization-flow-to-access-apollo-user-information-partners).  ## Rate limits & credits  Rate limits and credit consumption depend on your [Apollo pricing plan](https://docs.apollo.io/docs/api-pricing). Check your current limits and usage with the [View API Usage Stats and Rate Limits](https://docs.apollo.io/reference/view-api-usage-stats) endpoint. For more details, see [Rate Limits](https://docs.apollo.io/reference/rate-limits) and the [API FAQs](https://docs.apollo.io/docs/apollo-api-faqs).  New to the API? Start with the [Apollo API Overview](https://docs.apollo.io/docs/apollo-api-overview).
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateAContactRequest
 */
export interface CreateAContactRequest {
    /**
     * The first name of the contact you want to create. Example: `Tim`
     * @type {string}
     * @memberof CreateAContactRequest
     */
    firstName?: string;
    /**
     * The last name of the contact you want to create. Example: `Zheng`
     * @type {string}
     * @memberof CreateAContactRequest
     */
    lastName?: string;
    /**
     * The name of the contact's employer (company). Example: `apollo`
     * @type {string}
     * @memberof CreateAContactRequest
     */
    organizationName?: string;
    /**
     * The current job title that the contact holds. Example: `senior research analyst`
     * @type {string}
     * @memberof CreateAContactRequest
     */
    title?: string;
    /**
     * The Apollo ID for the account. Example: `63f53afe4ceeca00016bdd2f`
     * @type {string}
     * @memberof CreateAContactRequest
     */
    accountId?: string;
    /**
     * The email address of the contact. Example: `example@email.com`
     * @type {string}
     * @memberof CreateAContactRequest
     */
    email?: string;
    /**
     * The corporate website URL. Example: `https://www.apollo.io/`
     * @type {string}
     * @memberof CreateAContactRequest
     */
    websiteUrl?: string;
    /**
     * Lists to which the contact belongs.
     * @type {Array<string>}
     * @memberof CreateAContactRequest
     */
    labelNames?: Array<string>;
    /**
     * The Apollo ID for the contact stage. Example: `6095a710bd01d100a506d4ae`
     * @type {string}
     * @memberof CreateAContactRequest
     */
    contactStageId?: string;
    /**
     * The personal location for the contact. Example: `Atlanta, United States`
     * @type {string}
     * @memberof CreateAContactRequest
     */
    presentRawAddress?: string;
    /**
     * The primary phone number. Example: `555-555-0133`
     * @type {string}
     * @memberof CreateAContactRequest
     */
    directPhone?: string;
    /**
     * The work/office phone number. Example: `+44 7700 900852`
     * @type {string}
     * @memberof CreateAContactRequest
     */
    corporatePhone?: string;
    /**
     * The mobile phone number. Example: `555-555-0133`
     * @type {string}
     * @memberof CreateAContactRequest
     */
    mobilePhone?: string;
    /**
     * The home phone number. Example: `555-555-0133`
     * @type {string}
     * @memberof CreateAContactRequest
     */
    homePhone?: string;
    /**
     * Alternative phone number. Example: `555-555-0133`
     * @type {string}
     * @memberof CreateAContactRequest
     */
    otherPhone?: string;
    /**
     * Add information to <a href="https://knowledge.apollo.io/hc/en-us/articles/4412498825869-Create-Custom-Contact-Fields" target="_blank">custom fields</a> in Apollo. <br><br><b>Your custom fields are unique to your team's Apollo account. This means that the examples in this documentation may not work for your testing purposes.</b> <br><br>To utilize this parameter successfully, call the <a href="https://docs.apollo.io/reference/get-a-list-of-all-custom-fields">Get a List of All Custom Fields</a> endpoint and identify the `id` value for the custom field, as well as the appropriate data type. For example, if a custom field accepts picklist entries, you need to pass the accompanying `id` value for the picklist entry that you want to use as the input value. <br><br><b>Example</b>: When the <a href="https://docs.apollo.io/reference/get-a-list-of-all-custom-fields">Get a List of All Custom Fields</a> endpoint returns an `id` of field: 
     *  * `"60c39ed82bd02f01154c470a"` (datetime) 
     *  
     * 
     *  then the value passed should be: 
     * 
     *  `{"60c39ed82bd02f01154c470a": "2025-08-07"}`
     * @type {{ [key: string]: string; }}
     * @memberof CreateAContactRequest
     */
    typedCustomFields?: { [key: string]: string; };
    /**
     * Set to `true` to enable deduplication logic that prevents creating duplicate contacts. When enabled, Apollo will check for existing contacts with matching email addresses, names, or other identifying information and return the existing contact instead of creating a duplicate. The default value is `false`. <br><br>When deduplication is enabled, performance may be slightly impacted due to the additional validation checks, but this ensures data integrity and prevents duplicate entries in your database.
     * @type {boolean}
     * @memberof CreateAContactRequest
     */
    runDedupe?: boolean;
}

/**
 * Check if a given object implements the CreateAContactRequest interface.
 */
export function instanceOfCreateAContactRequest(value: object): value is CreateAContactRequest {
    return true;
}

export function CreateAContactRequestFromJSON(json: any): CreateAContactRequest {
    return CreateAContactRequestFromJSONTyped(json, false);
}

export function CreateAContactRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateAContactRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'firstName': json['first_name'] == null ? undefined : json['first_name'],
        'lastName': json['last_name'] == null ? undefined : json['last_name'],
        'organizationName': json['organization_name'] == null ? undefined : json['organization_name'],
        'title': json['title'] == null ? undefined : json['title'],
        'accountId': json['account_id'] == null ? undefined : json['account_id'],
        'email': json['email'] == null ? undefined : json['email'],
        'websiteUrl': json['website_url'] == null ? undefined : json['website_url'],
        'labelNames': json['label_names'] == null ? undefined : json['label_names'],
        'contactStageId': json['contact_stage_id'] == null ? undefined : json['contact_stage_id'],
        'presentRawAddress': json['present_raw_address'] == null ? undefined : json['present_raw_address'],
        'directPhone': json['direct_phone'] == null ? undefined : json['direct_phone'],
        'corporatePhone': json['corporate_phone'] == null ? undefined : json['corporate_phone'],
        'mobilePhone': json['mobile_phone'] == null ? undefined : json['mobile_phone'],
        'homePhone': json['home_phone'] == null ? undefined : json['home_phone'],
        'otherPhone': json['other_phone'] == null ? undefined : json['other_phone'],
        'typedCustomFields': json['typed_custom_fields'] == null ? undefined : json['typed_custom_fields'],
        'runDedupe': json['run_dedupe'] == null ? undefined : json['run_dedupe'],
    };
}

export function CreateAContactRequestToJSON(json: any): CreateAContactRequest {
    return CreateAContactRequestToJSONTyped(json, false);
}

export function CreateAContactRequestToJSONTyped(value?: CreateAContactRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'first_name': value['firstName'],
        'last_name': value['lastName'],
        'organization_name': value['organizationName'],
        'title': value['title'],
        'account_id': value['accountId'],
        'email': value['email'],
        'website_url': value['websiteUrl'],
        'label_names': value['labelNames'],
        'contact_stage_id': value['contactStageId'],
        'present_raw_address': value['presentRawAddress'],
        'direct_phone': value['directPhone'],
        'corporate_phone': value['corporatePhone'],
        'mobile_phone': value['mobilePhone'],
        'home_phone': value['homePhone'],
        'other_phone': value['otherPhone'],
        'typed_custom_fields': value['typedCustomFields'],
        'run_dedupe': value['runDedupe'],
    };
}

