/* tslint:disable */
/* eslint-disable */
/**
 * apollo-rest-api
 * The Apollo API provides programmatic access to [Apollo](https://www.apollo.io/), the all-in-one sales intelligence and engagement platform. Use it to enrich people and company data (individually or in bulk), search Apollo\'s database of over 230 million contacts and 30 million companies, and manage accounts, contacts, deals, sequences, tasks, calls, and conversations in your go-to-market workflows.  ## Base URL  All API requests are made to `https://api.apollo.io/api/v1`.  ## Authentication  - **Apollo users** authenticate with an API key passed in the `x-api-key` request header. See [Create API Keys](https://docs.apollo.io/docs/create-api-key). - **Apollo partners** building integrations on behalf of mutual users authenticate with the [OAuth 2.0 authorization flow](https://docs.apollo.io/docs/use-oauth-20-authorization-flow-to-access-apollo-user-information-partners).  ## Rate limits & credits  Rate limits and credit consumption depend on your [Apollo pricing plan](https://docs.apollo.io/docs/api-pricing). Check your current limits and usage with the [View API Usage Stats and Rate Limits](https://docs.apollo.io/reference/view-api-usage-stats) endpoint. For more details, see [Rate Limits](https://docs.apollo.io/reference/rate-limits) and the [API FAQs](https://docs.apollo.io/docs/apollo-api-faqs).  New to the API? Start with the [Apollo API Overview](https://docs.apollo.io/docs/apollo-api-overview).
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ViewAssociatedDeals200ResponseOpportunitiesInnerCurrency } from './ViewAssociatedDeals200ResponseOpportunitiesInnerCurrency';
import {
    ViewAssociatedDeals200ResponseOpportunitiesInnerCurrencyFromJSON,
    ViewAssociatedDeals200ResponseOpportunitiesInnerCurrencyFromJSONTyped,
    ViewAssociatedDeals200ResponseOpportunitiesInnerCurrencyToJSON,
    ViewAssociatedDeals200ResponseOpportunitiesInnerCurrencyToJSONTyped,
} from './ViewAssociatedDeals200ResponseOpportunitiesInnerCurrency';
import type { CreateATask200ResponseTaskOpportunityOpportunityContactRolesInner } from './CreateATask200ResponseTaskOpportunityOpportunityContactRolesInner';
import {
    CreateATask200ResponseTaskOpportunityOpportunityContactRolesInnerFromJSON,
    CreateATask200ResponseTaskOpportunityOpportunityContactRolesInnerFromJSONTyped,
    CreateATask200ResponseTaskOpportunityOpportunityContactRolesInnerToJSON,
    CreateATask200ResponseTaskOpportunityOpportunityContactRolesInnerToJSONTyped,
} from './CreateATask200ResponseTaskOpportunityOpportunityContactRolesInner';
import type { CreateATask200ResponseTaskOpportunityTypedCustomFields } from './CreateATask200ResponseTaskOpportunityTypedCustomFields';
import {
    CreateATask200ResponseTaskOpportunityTypedCustomFieldsFromJSON,
    CreateATask200ResponseTaskOpportunityTypedCustomFieldsFromJSONTyped,
    CreateATask200ResponseTaskOpportunityTypedCustomFieldsToJSON,
    CreateATask200ResponseTaskOpportunityTypedCustomFieldsToJSONTyped,
} from './CreateATask200ResponseTaskOpportunityTypedCustomFields';
import type { CreateATask200ResponseTaskOpportunityAccount } from './CreateATask200ResponseTaskOpportunityAccount';
import {
    CreateATask200ResponseTaskOpportunityAccountFromJSON,
    CreateATask200ResponseTaskOpportunityAccountFromJSONTyped,
    CreateATask200ResponseTaskOpportunityAccountToJSON,
    CreateATask200ResponseTaskOpportunityAccountToJSONTyped,
} from './CreateATask200ResponseTaskOpportunityAccount';

/**
 * 
 * @export
 * @interface CreateATask200ResponseTaskOpportunity
 */
export interface CreateATask200ResponseTaskOpportunity {
    /**
     * 
     * @type {string}
     * @memberof CreateATask200ResponseTaskOpportunity
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateATask200ResponseTaskOpportunity
     */
    teamId?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateATask200ResponseTaskOpportunity
     */
    ownerId?: string;
    /**
     * 
     * @type {any}
     * @memberof CreateATask200ResponseTaskOpportunity
     */
    salesforceOwnerId?: any | null;
    /**
     * 
     * @type {number}
     * @memberof CreateATask200ResponseTaskOpportunity
     */
    amount?: number;
    /**
     * 
     * @type {string}
     * @memberof CreateATask200ResponseTaskOpportunity
     */
    closedDate?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateATask200ResponseTaskOpportunity
     */
    accountId?: string;
    /**
     * 
     * @type {any}
     * @memberof CreateATask200ResponseTaskOpportunity
     */
    description?: any | null;
    /**
     * 
     * @type {boolean}
     * @memberof CreateATask200ResponseTaskOpportunity
     */
    isClosed?: boolean;
    /**
     * 
     * @type {any}
     * @memberof CreateATask200ResponseTaskOpportunity
     */
    isWon?: any | null;
    /**
     * 
     * @type {string}
     * @memberof CreateATask200ResponseTaskOpportunity
     */
    name?: string;
    /**
     * 
     * @type {any}
     * @memberof CreateATask200ResponseTaskOpportunity
     */
    stageName?: any | null;
    /**
     * 
     * @type {string}
     * @memberof CreateATask200ResponseTaskOpportunity
     */
    opportunityStageId?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateATask200ResponseTaskOpportunity
     */
    source?: string;
    /**
     * 
     * @type {any}
     * @memberof CreateATask200ResponseTaskOpportunity
     */
    salesforceId?: any | null;
    /**
     * 
     * @type {string}
     * @memberof CreateATask200ResponseTaskOpportunity
     */
    createdAt?: string;
    /**
     * 
     * @type {any}
     * @memberof CreateATask200ResponseTaskOpportunity
     */
    actualCloseDate?: any | null;
    /**
     * 
     * @type {string}
     * @memberof CreateATask200ResponseTaskOpportunity
     */
    nextStep?: string;
    /**
     * 
     * @type {any}
     * @memberof CreateATask200ResponseTaskOpportunity
     */
    nextStepDate?: any | null;
    /**
     * 
     * @type {any}
     * @memberof CreateATask200ResponseTaskOpportunity
     */
    closedLostReason?: any | null;
    /**
     * 
     * @type {any}
     * @memberof CreateATask200ResponseTaskOpportunity
     */
    closedWonReason?: any | null;
    /**
     * 
     * @type {string}
     * @memberof CreateATask200ResponseTaskOpportunity
     */
    forecastCategory?: string;
    /**
     * 
     * @type {number}
     * @memberof CreateATask200ResponseTaskOpportunity
     */
    dealProbability?: number;
    /**
     * 
     * @type {string}
     * @memberof CreateATask200ResponseTaskOpportunity
     */
    createdById?: string;
    /**
     * 
     * @type {any}
     * @memberof CreateATask200ResponseTaskOpportunity
     */
    currentSolutions?: any | null;
    /**
     * 
     * @type {any}
     * @memberof CreateATask200ResponseTaskOpportunity
     */
    dealSource?: any | null;
    /**
     * 
     * @type {any}
     * @memberof CreateATask200ResponseTaskOpportunity
     */
    manuallyUpdatedProbability?: any | null;
    /**
     * 
     * @type {any}
     * @memberof CreateATask200ResponseTaskOpportunity
     */
    manuallyUpdatedForecast?: any | null;
    /**
     * 
     * @type {any}
     * @memberof CreateATask200ResponseTaskOpportunity
     */
    crmId?: any | null;
    /**
     * 
     * @type {any}
     * @memberof CreateATask200ResponseTaskOpportunity
     */
    crmRecordUrl?: any | null;
    /**
     * 
     * @type {any}
     * @memberof CreateATask200ResponseTaskOpportunity
     */
    crmOwnerId?: any | null;
    /**
     * 
     * @type {any}
     * @memberof CreateATask200ResponseTaskOpportunity
     */
    probability?: any | null;
    /**
     * 
     * @type {string}
     * @memberof CreateATask200ResponseTaskOpportunity
     */
    opportunityPipelineId?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateATask200ResponseTaskOpportunity
     */
    stageUpdatedAt?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateATask200ResponseTaskOpportunity
     */
    nextStepLastUpdatedAt?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateATask200ResponseTaskOpportunity
     */
    exchangeRateCode?: string;
    /**
     * 
     * @type {number}
     * @memberof CreateATask200ResponseTaskOpportunity
     */
    exchangeRateValue?: number;
    /**
     * 
     * @type {number}
     * @memberof CreateATask200ResponseTaskOpportunity
     */
    amountInTeamCurrency?: number;
    /**
     * 
     * @type {number}
     * @memberof CreateATask200ResponseTaskOpportunity
     */
    forecastedRevenue?: number;
    /**
     * 
     * @type {string}
     * @memberof CreateATask200ResponseTaskOpportunity
     */
    lastActivityDate?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateATask200ResponseTaskOpportunity
     */
    existenceLevel?: string;
    /**
     * 
     * @type {CreateATask200ResponseTaskOpportunityTypedCustomFields}
     * @memberof CreateATask200ResponseTaskOpportunity
     */
    typedCustomFields?: CreateATask200ResponseTaskOpportunityTypedCustomFields;
    /**
     * 
     * @type {Array<any>}
     * @memberof CreateATask200ResponseTaskOpportunity
     */
    opportunityRuleConfigStatuses?: Array<any>;
    /**
     * 
     * @type {Array<CreateATask200ResponseTaskOpportunityOpportunityContactRolesInner>}
     * @memberof CreateATask200ResponseTaskOpportunity
     */
    opportunityContactRoles?: Array<CreateATask200ResponseTaskOpportunityOpportunityContactRolesInner>;
    /**
     * 
     * @type {ViewAssociatedDeals200ResponseOpportunitiesInnerCurrency}
     * @memberof CreateATask200ResponseTaskOpportunity
     */
    currency?: ViewAssociatedDeals200ResponseOpportunitiesInnerCurrency;
    /**
     * 
     * @type {CreateATask200ResponseTaskOpportunityAccount}
     * @memberof CreateATask200ResponseTaskOpportunity
     */
    account?: CreateATask200ResponseTaskOpportunityAccount;
}

/**
 * Check if a given object implements the CreateATask200ResponseTaskOpportunity interface.
 */
export function instanceOfCreateATask200ResponseTaskOpportunity(value: object): value is CreateATask200ResponseTaskOpportunity {
    return true;
}

export function CreateATask200ResponseTaskOpportunityFromJSON(json: any): CreateATask200ResponseTaskOpportunity {
    return CreateATask200ResponseTaskOpportunityFromJSONTyped(json, false);
}

export function CreateATask200ResponseTaskOpportunityFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateATask200ResponseTaskOpportunity {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'teamId': json['team_id'] == null ? undefined : json['team_id'],
        'ownerId': json['owner_id'] == null ? undefined : json['owner_id'],
        'salesforceOwnerId': json['salesforce_owner_id'] == null ? undefined : json['salesforce_owner_id'],
        'amount': json['amount'] == null ? undefined : json['amount'],
        'closedDate': json['closed_date'] == null ? undefined : json['closed_date'],
        'accountId': json['account_id'] == null ? undefined : json['account_id'],
        'description': json['description'] == null ? undefined : json['description'],
        'isClosed': json['is_closed'] == null ? undefined : json['is_closed'],
        'isWon': json['is_won'] == null ? undefined : json['is_won'],
        'name': json['name'] == null ? undefined : json['name'],
        'stageName': json['stage_name'] == null ? undefined : json['stage_name'],
        'opportunityStageId': json['opportunity_stage_id'] == null ? undefined : json['opportunity_stage_id'],
        'source': json['source'] == null ? undefined : json['source'],
        'salesforceId': json['salesforce_id'] == null ? undefined : json['salesforce_id'],
        'createdAt': json['created_at'] == null ? undefined : json['created_at'],
        'actualCloseDate': json['actual_close_date'] == null ? undefined : json['actual_close_date'],
        'nextStep': json['next_step'] == null ? undefined : json['next_step'],
        'nextStepDate': json['next_step_date'] == null ? undefined : json['next_step_date'],
        'closedLostReason': json['closed_lost_reason'] == null ? undefined : json['closed_lost_reason'],
        'closedWonReason': json['closed_won_reason'] == null ? undefined : json['closed_won_reason'],
        'forecastCategory': json['forecast_category'] == null ? undefined : json['forecast_category'],
        'dealProbability': json['deal_probability'] == null ? undefined : json['deal_probability'],
        'createdById': json['created_by_id'] == null ? undefined : json['created_by_id'],
        'currentSolutions': json['current_solutions'] == null ? undefined : json['current_solutions'],
        'dealSource': json['deal_source'] == null ? undefined : json['deal_source'],
        'manuallyUpdatedProbability': json['manually_updated_probability'] == null ? undefined : json['manually_updated_probability'],
        'manuallyUpdatedForecast': json['manually_updated_forecast'] == null ? undefined : json['manually_updated_forecast'],
        'crmId': json['crm_id'] == null ? undefined : json['crm_id'],
        'crmRecordUrl': json['crm_record_url'] == null ? undefined : json['crm_record_url'],
        'crmOwnerId': json['crm_owner_id'] == null ? undefined : json['crm_owner_id'],
        'probability': json['probability'] == null ? undefined : json['probability'],
        'opportunityPipelineId': json['opportunity_pipeline_id'] == null ? undefined : json['opportunity_pipeline_id'],
        'stageUpdatedAt': json['stage_updated_at'] == null ? undefined : json['stage_updated_at'],
        'nextStepLastUpdatedAt': json['next_step_last_updated_at'] == null ? undefined : json['next_step_last_updated_at'],
        'exchangeRateCode': json['exchange_rate_code'] == null ? undefined : json['exchange_rate_code'],
        'exchangeRateValue': json['exchange_rate_value'] == null ? undefined : json['exchange_rate_value'],
        'amountInTeamCurrency': json['amount_in_team_currency'] == null ? undefined : json['amount_in_team_currency'],
        'forecastedRevenue': json['forecasted_revenue'] == null ? undefined : json['forecasted_revenue'],
        'lastActivityDate': json['last_activity_date'] == null ? undefined : json['last_activity_date'],
        'existenceLevel': json['existence_level'] == null ? undefined : json['existence_level'],
        'typedCustomFields': json['typed_custom_fields'] == null ? undefined : CreateATask200ResponseTaskOpportunityTypedCustomFieldsFromJSON(json['typed_custom_fields']),
        'opportunityRuleConfigStatuses': json['opportunity_rule_config_statuses'] == null ? undefined : json['opportunity_rule_config_statuses'],
        'opportunityContactRoles': json['opportunity_contact_roles'] == null ? undefined : ((json['opportunity_contact_roles'] as Array<any>).map(CreateATask200ResponseTaskOpportunityOpportunityContactRolesInnerFromJSON)),
        'currency': json['currency'] == null ? undefined : ViewAssociatedDeals200ResponseOpportunitiesInnerCurrencyFromJSON(json['currency']),
        'account': json['account'] == null ? undefined : CreateATask200ResponseTaskOpportunityAccountFromJSON(json['account']),
    };
}

export function CreateATask200ResponseTaskOpportunityToJSON(json: any): CreateATask200ResponseTaskOpportunity {
    return CreateATask200ResponseTaskOpportunityToJSONTyped(json, false);
}

export function CreateATask200ResponseTaskOpportunityToJSONTyped(value?: CreateATask200ResponseTaskOpportunity | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'team_id': value['teamId'],
        'owner_id': value['ownerId'],
        'salesforce_owner_id': value['salesforceOwnerId'],
        'amount': value['amount'],
        'closed_date': value['closedDate'],
        'account_id': value['accountId'],
        'description': value['description'],
        'is_closed': value['isClosed'],
        'is_won': value['isWon'],
        'name': value['name'],
        'stage_name': value['stageName'],
        'opportunity_stage_id': value['opportunityStageId'],
        'source': value['source'],
        'salesforce_id': value['salesforceId'],
        'created_at': value['createdAt'],
        'actual_close_date': value['actualCloseDate'],
        'next_step': value['nextStep'],
        'next_step_date': value['nextStepDate'],
        'closed_lost_reason': value['closedLostReason'],
        'closed_won_reason': value['closedWonReason'],
        'forecast_category': value['forecastCategory'],
        'deal_probability': value['dealProbability'],
        'created_by_id': value['createdById'],
        'current_solutions': value['currentSolutions'],
        'deal_source': value['dealSource'],
        'manually_updated_probability': value['manuallyUpdatedProbability'],
        'manually_updated_forecast': value['manuallyUpdatedForecast'],
        'crm_id': value['crmId'],
        'crm_record_url': value['crmRecordUrl'],
        'crm_owner_id': value['crmOwnerId'],
        'probability': value['probability'],
        'opportunity_pipeline_id': value['opportunityPipelineId'],
        'stage_updated_at': value['stageUpdatedAt'],
        'next_step_last_updated_at': value['nextStepLastUpdatedAt'],
        'exchange_rate_code': value['exchangeRateCode'],
        'exchange_rate_value': value['exchangeRateValue'],
        'amount_in_team_currency': value['amountInTeamCurrency'],
        'forecasted_revenue': value['forecastedRevenue'],
        'last_activity_date': value['lastActivityDate'],
        'existence_level': value['existenceLevel'],
        'typed_custom_fields': CreateATask200ResponseTaskOpportunityTypedCustomFieldsToJSON(value['typedCustomFields']),
        'opportunity_rule_config_statuses': value['opportunityRuleConfigStatuses'],
        'opportunity_contact_roles': value['opportunityContactRoles'] == null ? undefined : ((value['opportunityContactRoles'] as Array<any>).map(CreateATask200ResponseTaskOpportunityOpportunityContactRolesInnerToJSON)),
        'currency': ViewAssociatedDeals200ResponseOpportunitiesInnerCurrencyToJSON(value['currency']),
        'account': CreateATask200ResponseTaskOpportunityAccountToJSON(value['account']),
    };
}

