/* tslint:disable */
/* eslint-disable */
/**
 * apollo-rest-api
 * The Apollo API provides programmatic access to [Apollo](https://www.apollo.io/), the all-in-one sales intelligence and engagement platform. Use it to enrich people and company data (individually or in bulk), search Apollo\'s database of over 230 million contacts and 30 million companies, and manage accounts, contacts, deals, sequences, tasks, calls, and conversations in your go-to-market workflows.  ## Base URL  All API requests are made to `https://api.apollo.io/api/v1`.  ## Authentication  - **Apollo users** authenticate with an API key passed in the `x-api-key` request header. See [Create API Keys](https://docs.apollo.io/docs/create-api-key). - **Apollo partners** building integrations on behalf of mutual users authenticate with the [OAuth 2.0 authorization flow](https://docs.apollo.io/docs/use-oauth-20-authorization-flow-to-access-apollo-user-information-partners).  ## Rate limits & credits  Rate limits and credit consumption depend on your [Apollo pricing plan](https://docs.apollo.io/docs/api-pricing). Check your current limits and usage with the [View API Usage Stats and Rate Limits](https://docs.apollo.io/reference/view-api-usage-stats) endpoint. For more details, see [Rate Limits](https://docs.apollo.io/reference/rate-limits) and the [API FAQs](https://docs.apollo.io/docs/apollo-api-faqs).  New to the API? Start with the [Apollo API Overview](https://docs.apollo.io/docs/apollo-api-overview).
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BulkPeopleEnrichment200ResponseMatchesInnerAccountAccountRuleConfigStatusesInner } from './BulkPeopleEnrichment200ResponseMatchesInnerAccountAccountRuleConfigStatusesInner';
import {
    BulkPeopleEnrichment200ResponseMatchesInnerAccountAccountRuleConfigStatusesInnerFromJSON,
    BulkPeopleEnrichment200ResponseMatchesInnerAccountAccountRuleConfigStatusesInnerFromJSONTyped,
    BulkPeopleEnrichment200ResponseMatchesInnerAccountAccountRuleConfigStatusesInnerToJSON,
    BulkPeopleEnrichment200ResponseMatchesInnerAccountAccountRuleConfigStatusesInnerToJSONTyped,
} from './BulkPeopleEnrichment200ResponseMatchesInnerAccountAccountRuleConfigStatusesInner';

/**
 * 
 * @export
 * @interface CreateATask200ResponseTaskOpportunityAccount
 */
export interface CreateATask200ResponseTaskOpportunityAccount {
    /**
     * 
     * @type {string}
     * @memberof CreateATask200ResponseTaskOpportunityAccount
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateATask200ResponseTaskOpportunityAccount
     */
    domain?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateATask200ResponseTaskOpportunityAccount
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateATask200ResponseTaskOpportunityAccount
     */
    teamId?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateATask200ResponseTaskOpportunityAccount
     */
    organizationId?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateATask200ResponseTaskOpportunityAccount
     */
    accountStageId?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateATask200ResponseTaskOpportunityAccount
     */
    source?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateATask200ResponseTaskOpportunityAccount
     */
    originalSource?: string;
    /**
     * 
     * @type {any}
     * @memberof CreateATask200ResponseTaskOpportunityAccount
     */
    creatorId?: any | null;
    /**
     * 
     * @type {any}
     * @memberof CreateATask200ResponseTaskOpportunityAccount
     */
    ownerId?: any | null;
    /**
     * 
     * @type {string}
     * @memberof CreateATask200ResponseTaskOpportunityAccount
     */
    createdAt?: string;
    /**
     * 
     * @type {any}
     * @memberof CreateATask200ResponseTaskOpportunityAccount
     */
    phone?: any | null;
    /**
     * 
     * @type {string}
     * @memberof CreateATask200ResponseTaskOpportunityAccount
     */
    phoneStatus?: string;
    /**
     * 
     * @type {any}
     * @memberof CreateATask200ResponseTaskOpportunityAccount
     */
    hubspotId?: any | null;
    /**
     * 
     * @type {any}
     * @memberof CreateATask200ResponseTaskOpportunityAccount
     */
    salesforceId?: any | null;
    /**
     * 
     * @type {any}
     * @memberof CreateATask200ResponseTaskOpportunityAccount
     */
    crmOwnerId?: any | null;
    /**
     * 
     * @type {any}
     * @memberof CreateATask200ResponseTaskOpportunityAccount
     */
    parentAccountId?: any | null;
    /**
     * 
     * @type {any}
     * @memberof CreateATask200ResponseTaskOpportunityAccount
     */
    linkedinUrl?: any | null;
    /**
     * 
     * @type {Array<any>}
     * @memberof CreateATask200ResponseTaskOpportunityAccount
     */
    accountPlaybookStatuses?: Array<any>;
    /**
     * 
     * @type {Array<BulkPeopleEnrichment200ResponseMatchesInnerAccountAccountRuleConfigStatusesInner>}
     * @memberof CreateATask200ResponseTaskOpportunityAccount
     */
    accountRuleConfigStatuses?: Array<BulkPeopleEnrichment200ResponseMatchesInnerAccountAccountRuleConfigStatusesInner>;
    /**
     * 
     * @type {string}
     * @memberof CreateATask200ResponseTaskOpportunityAccount
     */
    existenceLevel?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof CreateATask200ResponseTaskOpportunityAccount
     */
    labelIds?: Array<string>;
    /**
     * 
     * @type {object}
     * @memberof CreateATask200ResponseTaskOpportunityAccount
     */
    typedCustomFields?: object;
    /**
     * 
     * @type {any}
     * @memberof CreateATask200ResponseTaskOpportunityAccount
     */
    customFieldErrors?: any | null;
    /**
     * 
     * @type {string}
     * @memberof CreateATask200ResponseTaskOpportunityAccount
     */
    modality?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateATask200ResponseTaskOpportunityAccount
     */
    sourceDisplayName?: string;
    /**
     * 
     * @type {any}
     * @memberof CreateATask200ResponseTaskOpportunityAccount
     */
    crmRecordUrl?: any | null;
    /**
     * 
     * @type {Array<any>}
     * @memberof CreateATask200ResponseTaskOpportunityAccount
     */
    contactEmailerCampaignIds?: Array<any>;
    /**
     * 
     * @type {object}
     * @memberof CreateATask200ResponseTaskOpportunityAccount
     */
    contactCampaignStatusTally?: object;
    /**
     * 
     * @type {number}
     * @memberof CreateATask200ResponseTaskOpportunityAccount
     */
    numContacts?: number;
    /**
     * 
     * @type {any}
     * @memberof CreateATask200ResponseTaskOpportunityAccount
     */
    lastActivityDate?: any | null;
}

/**
 * Check if a given object implements the CreateATask200ResponseTaskOpportunityAccount interface.
 */
export function instanceOfCreateATask200ResponseTaskOpportunityAccount(value: object): value is CreateATask200ResponseTaskOpportunityAccount {
    return true;
}

export function CreateATask200ResponseTaskOpportunityAccountFromJSON(json: any): CreateATask200ResponseTaskOpportunityAccount {
    return CreateATask200ResponseTaskOpportunityAccountFromJSONTyped(json, false);
}

export function CreateATask200ResponseTaskOpportunityAccountFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateATask200ResponseTaskOpportunityAccount {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'domain': json['domain'] == null ? undefined : json['domain'],
        'name': json['name'] == null ? undefined : json['name'],
        'teamId': json['team_id'] == null ? undefined : json['team_id'],
        'organizationId': json['organization_id'] == null ? undefined : json['organization_id'],
        'accountStageId': json['account_stage_id'] == null ? undefined : json['account_stage_id'],
        'source': json['source'] == null ? undefined : json['source'],
        'originalSource': json['original_source'] == null ? undefined : json['original_source'],
        'creatorId': json['creator_id'] == null ? undefined : json['creator_id'],
        'ownerId': json['owner_id'] == null ? undefined : json['owner_id'],
        'createdAt': json['created_at'] == null ? undefined : json['created_at'],
        'phone': json['phone'] == null ? undefined : json['phone'],
        'phoneStatus': json['phone_status'] == null ? undefined : json['phone_status'],
        'hubspotId': json['hubspot_id'] == null ? undefined : json['hubspot_id'],
        'salesforceId': json['salesforce_id'] == null ? undefined : json['salesforce_id'],
        'crmOwnerId': json['crm_owner_id'] == null ? undefined : json['crm_owner_id'],
        'parentAccountId': json['parent_account_id'] == null ? undefined : json['parent_account_id'],
        'linkedinUrl': json['linkedin_url'] == null ? undefined : json['linkedin_url'],
        'accountPlaybookStatuses': json['account_playbook_statuses'] == null ? undefined : json['account_playbook_statuses'],
        'accountRuleConfigStatuses': json['account_rule_config_statuses'] == null ? undefined : ((json['account_rule_config_statuses'] as Array<any>).map(BulkPeopleEnrichment200ResponseMatchesInnerAccountAccountRuleConfigStatusesInnerFromJSON)),
        'existenceLevel': json['existence_level'] == null ? undefined : json['existence_level'],
        'labelIds': json['label_ids'] == null ? undefined : json['label_ids'],
        'typedCustomFields': json['typed_custom_fields'] == null ? undefined : json['typed_custom_fields'],
        'customFieldErrors': json['custom_field_errors'] == null ? undefined : json['custom_field_errors'],
        'modality': json['modality'] == null ? undefined : json['modality'],
        'sourceDisplayName': json['source_display_name'] == null ? undefined : json['source_display_name'],
        'crmRecordUrl': json['crm_record_url'] == null ? undefined : json['crm_record_url'],
        'contactEmailerCampaignIds': json['contact_emailer_campaign_ids'] == null ? undefined : json['contact_emailer_campaign_ids'],
        'contactCampaignStatusTally': json['contact_campaign_status_tally'] == null ? undefined : json['contact_campaign_status_tally'],
        'numContacts': json['num_contacts'] == null ? undefined : json['num_contacts'],
        'lastActivityDate': json['last_activity_date'] == null ? undefined : json['last_activity_date'],
    };
}

export function CreateATask200ResponseTaskOpportunityAccountToJSON(json: any): CreateATask200ResponseTaskOpportunityAccount {
    return CreateATask200ResponseTaskOpportunityAccountToJSONTyped(json, false);
}

export function CreateATask200ResponseTaskOpportunityAccountToJSONTyped(value?: CreateATask200ResponseTaskOpportunityAccount | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'domain': value['domain'],
        'name': value['name'],
        'team_id': value['teamId'],
        'organization_id': value['organizationId'],
        'account_stage_id': value['accountStageId'],
        'source': value['source'],
        'original_source': value['originalSource'],
        'creator_id': value['creatorId'],
        'owner_id': value['ownerId'],
        'created_at': value['createdAt'],
        'phone': value['phone'],
        'phone_status': value['phoneStatus'],
        'hubspot_id': value['hubspotId'],
        'salesforce_id': value['salesforceId'],
        'crm_owner_id': value['crmOwnerId'],
        'parent_account_id': value['parentAccountId'],
        'linkedin_url': value['linkedinUrl'],
        'account_playbook_statuses': value['accountPlaybookStatuses'],
        'account_rule_config_statuses': value['accountRuleConfigStatuses'] == null ? undefined : ((value['accountRuleConfigStatuses'] as Array<any>).map(BulkPeopleEnrichment200ResponseMatchesInnerAccountAccountRuleConfigStatusesInnerToJSON)),
        'existence_level': value['existenceLevel'],
        'label_ids': value['labelIds'],
        'typed_custom_fields': value['typedCustomFields'],
        'custom_field_errors': value['customFieldErrors'],
        'modality': value['modality'],
        'source_display_name': value['sourceDisplayName'],
        'crm_record_url': value['crmRecordUrl'],
        'contact_emailer_campaign_ids': value['contactEmailerCampaignIds'],
        'contact_campaign_status_tally': value['contactCampaignStatusTally'],
        'num_contacts': value['numContacts'],
        'last_activity_date': value['lastActivityDate'],
    };
}

