/* tslint:disable */
/* eslint-disable */
/**
 * apollo-rest-api
 * The Apollo API provides programmatic access to [Apollo](https://www.apollo.io/), the all-in-one sales intelligence and engagement platform. Use it to enrich people and company data (individually or in bulk), search Apollo\'s database of over 230 million contacts and 30 million companies, and manage accounts, contacts, deals, sequences, tasks, calls, and conversations in your go-to-market workflows.  ## Base URL  All API requests are made to `https://api.apollo.io/api/v1`.  ## Authentication  - **Apollo users** authenticate with an API key passed in the `x-api-key` request header. See [Create API Keys](https://docs.apollo.io/docs/create-api-key). - **Apollo partners** building integrations on behalf of mutual users authenticate with the [OAuth 2.0 authorization flow](https://docs.apollo.io/docs/use-oauth-20-authorization-flow-to-access-apollo-user-information-partners).  ## Rate limits & credits  Rate limits and credit consumption depend on your [Apollo pricing plan](https://docs.apollo.io/docs/api-pricing). Check your current limits and usage with the [View API Usage Stats and Rate Limits](https://docs.apollo.io/reference/view-api-usage-stats) endpoint. For more details, see [Rate Limits](https://docs.apollo.io/reference/rate-limits) and the [API FAQs](https://docs.apollo.io/docs/apollo-api-faqs).  New to the API? Start with the [Apollo API Overview](https://docs.apollo.io/docs/apollo-api-overview).
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateAnAccountRequest
 */
export interface CreateAnAccountRequest {
    /**
     * Name the account that you are creating. This should be a human-readable name. <br><br>Example: `The Irish Copywriters`
     * @type {string}
     * @memberof CreateAnAccountRequest
     */
    name?: string;
    /**
     * The domain name for the account. <br><br>Do not include `www.` or similar. <br><br>Example: `apollo.io` or `microsoft.com`
     * @type {string}
     * @memberof CreateAnAccountRequest
     */
    domain?: string;
    /**
     * The ID for the account owner within your team's Apollo account. <br><br>Use the <a href="https://docs.apollo.io/reference/get-a-list-of-users" target="_blank">Get a List of Users endpoint</a> to retrieve IDs for all of the users within your Apollo account. <br><br>Example: `66302798d03b9601c7934ebf`
     * @type {string}
     * @memberof CreateAnAccountRequest
     */
    ownerId?: string;
    /**
     * The Apollo ID for the account stage to which you want to assign the account. Call the <a href="https://docs.apollo.io/reference/list-account-stages" target="_blank">List Account Stages endpoint</a> to retrieve a list of all the account stage IDs available in your Apollo account. <br><br>If you do not specify the account stage, Apollo automatically assigns the account to a stage as determined by your team's Apollo account. To change the order of account stages, launch the Apollo product and go to <b>Settings</b> > <b>Objects</b> > <a href="https://app.apollo.io/#/settings/accounts/stages" target="_blank"><b>Accounts</b></a>. Then, access the <b>Triggers</b> tab and change the stage for when an account is created.<br><br>Example: `6095a710bd01d100a506d4b9`
     * @type {string}
     * @memberof CreateAnAccountRequest
     */
    accountStageId?: string;
    /**
     * The primary phone number for the account. <br><br>This can be the phone number for the corporate headquarters, a branch location, or a direct dial to the primary point of contact for the account. <br><br>Apollo sanitizes phone numbers, so you can enter them in any format. The sanitized number can be viewed in the endpoint response. <br><br>Examples: `555-555-0133`; `+44 7700 900852`
     * @type {string}
     * @memberof CreateAnAccountRequest
     */
    phone?: string;
    /**
     * The corporate location for the account. This can include a city, US state, and country. <br><br>Apollo matches the location you provide to the most applicable pre-defined location. <br><br>Examples: `Belfield, Dublin 4, Ireland`; `Dallas, United States`
     * @type {string}
     * @memberof CreateAnAccountRequest
     */
    rawAddress?: string;
    /**
     * Add information to <a href="https://knowledge.apollo.io/hc/en-us/articles/4412498754445-Create-Custom-Account-Fields" target="_blank">custom fields</a> in Apollo. <br><br><b>Your custom fields are unique to your team's Apollo account. This means that the examples in this documentation may not work for your testing purposes.</b> <br><br>To utilize this parameter successfully, call the <a href="https://docs.apollo.io/reference/get-a-list-of-all-custom-fields">Get a List of All Custom Fields</a> endpoint and identify the `id` value for the custom field, as well as the appropriate data type. For example, if a custom field accepts picklist entries, you need to pass the accompanying `id` value for the picklist entry that you want to use as the input value. <br><br><b>Example</b>: When the <a href="https://docs.apollo.io/reference/get-a-list-of-all-custom-fields">Get a List of All Custom Fields</a> endpoint returns an `id` of field: 
     *  * `"60c39ed82bd02f01154c470a"` (datetime) 
     *  
     * 
     *  then the value passed should be: 
     * 
     *  `{"60c39ed82bd02f01154c470a": "2025-08-07"}`
     * @type {{ [key: string]: string; }}
     * @memberof CreateAnAccountRequest
     */
    typedCustomFields?: { [key: string]: string; };
}

/**
 * Check if a given object implements the CreateAnAccountRequest interface.
 */
export function instanceOfCreateAnAccountRequest(value: object): value is CreateAnAccountRequest {
    return true;
}

export function CreateAnAccountRequestFromJSON(json: any): CreateAnAccountRequest {
    return CreateAnAccountRequestFromJSONTyped(json, false);
}

export function CreateAnAccountRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateAnAccountRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'domain': json['domain'] == null ? undefined : json['domain'],
        'ownerId': json['owner_id'] == null ? undefined : json['owner_id'],
        'accountStageId': json['account_stage_id'] == null ? undefined : json['account_stage_id'],
        'phone': json['phone'] == null ? undefined : json['phone'],
        'rawAddress': json['raw_address'] == null ? undefined : json['raw_address'],
        'typedCustomFields': json['typed_custom_fields'] == null ? undefined : json['typed_custom_fields'],
    };
}

export function CreateAnAccountRequestToJSON(json: any): CreateAnAccountRequest {
    return CreateAnAccountRequestToJSONTyped(json, false);
}

export function CreateAnAccountRequestToJSONTyped(value?: CreateAnAccountRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'domain': value['domain'],
        'owner_id': value['ownerId'],
        'account_stage_id': value['accountStageId'],
        'phone': value['phone'],
        'raw_address': value['rawAddress'],
        'typed_custom_fields': value['typedCustomFields'],
    };
}

