/* tslint:disable */
/* eslint-disable */
/**
 * apollo-rest-api
 * The Apollo API provides programmatic access to [Apollo](https://www.apollo.io/), the all-in-one sales intelligence and engagement platform. Use it to enrich people and company data (individually or in bulk), search Apollo\'s database of over 230 million contacts and 30 million companies, and manage accounts, contacts, deals, sequences, tasks, calls, and conversations in your go-to-market workflows.  ## Base URL  All API requests are made to `https://api.apollo.io/api/v1`.  ## Authentication  - **Apollo users** authenticate with an API key passed in the `x-api-key` request header. See [Create API Keys](https://docs.apollo.io/docs/create-api-key). - **Apollo partners** building integrations on behalf of mutual users authenticate with the [OAuth 2.0 authorization flow](https://docs.apollo.io/docs/use-oauth-20-authorization-flow-to-access-apollo-user-information-partners).  ## Rate limits & credits  Rate limits and credit consumption depend on your [Apollo pricing plan](https://docs.apollo.io/docs/api-pricing). Check your current limits and usage with the [View API Usage Stats and Rate Limits](https://docs.apollo.io/reference/view-api-usage-stats) endpoint. For more details, see [Rate Limits](https://docs.apollo.io/reference/rate-limits) and the [API FAQs](https://docs.apollo.io/docs/apollo-api-faqs).  New to the API? Start with the [Apollo API Overview](https://docs.apollo.io/docs/apollo-api-overview).
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CreateAnEmailDraftRequestRecipientsInner } from './CreateAnEmailDraftRequestRecipientsInner';
import {
    CreateAnEmailDraftRequestRecipientsInnerFromJSON,
    CreateAnEmailDraftRequestRecipientsInnerFromJSONTyped,
    CreateAnEmailDraftRequestRecipientsInnerToJSON,
    CreateAnEmailDraftRequestRecipientsInnerToJSONTyped,
} from './CreateAnEmailDraftRequestRecipientsInner';

/**
 * 
 * @export
 * @interface CreateAnEmailDraftRequest
 */
export interface CreateAnEmailDraftRequest {
    /**
     * The Apollo ID for the contact that will receive the email. <br><br>This is required unless you provide `in_response_to_emailer_message_id`, in which case the contact is inferred from the parent message. <br><br>To find contact IDs, call the <a href="https://docs.apollo.io/reference/search-for-contacts" target="_blank">Search for Contacts endpoint</a> and identify the `id` value for the contact. <br><br>Example: `66e34b81740c50074e3d1bd4`
     * @type {string}
     * @memberof CreateAnEmailDraftRequest
     */
    contactId: string;
    /**
     * The subject line of the email. <br><br>Example: `Quick question about your team's workflow`
     * @type {string}
     * @memberof CreateAnEmailDraftRequest
     */
    subject?: string;
    /**
     * The body of the email as HTML. The content is sanitized by Apollo before it is saved. <br><br>Example: `<p>Hi there, I wanted to reach out about...</p>`
     * @type {string}
     * @memberof CreateAnEmailDraftRequest
     */
    bodyHtml?: string;
    /**
     * The list of recipients for the email. Use this to set the `to`, `cc`, and `bcc` recipients. If you do not provide a `to` recipient, Apollo keeps the existing `to` recipients (if any). <br><br>All recipient emails must be valid, otherwise the request fails and the email is not saved.
     * @type {Array<CreateAnEmailDraftRequestRecipientsInner>}
     * @memberof CreateAnEmailDraftRequest
     */
    recipients?: Array<CreateAnEmailDraftRequestRecipientsInner>;
    /**
     * The Apollo ID of an existing email message that this draft is replying to. When provided, Apollo infers the contact and builds the recipients from the parent message, so you do not need to provide `contact_id`. <br><br>Example: `66e8cc45028aed019c25d724`
     * @type {string}
     * @memberof CreateAnEmailDraftRequest
     */
    inResponseToEmailerMessageId?: string;
    /**
     * The Apollo ID of an email template to associate with the draft. <br><br>Example: `66e8cc45028aed019c25d725`
     * @type {string}
     * @memberof CreateAnEmailDraftRequest
     */
    emailerTemplateId?: string;
    /**
     * The Apollo IDs of the attachments to include with the email.
     * @type {Array<string>}
     * @memberof CreateAnEmailDraftRequest
     */
    attachmentIds?: Array<string>;
    /**
     * Set to `true` to enable open and click tracking for the email. This is only applied if your team is permitted to track emails. <br><br>Example: `true`
     * @type {boolean}
     * @memberof CreateAnEmailDraftRequest
     */
    enableTracking?: boolean;
    /**
     * The Apollo ID of an outreach task to associate with the draft. If a drafted email already exists for this task, Apollo links to that draft instead of creating a new one. <br><br>Example: `66e8cc45028aed019c25d726`
     * @type {string}
     * @memberof CreateAnEmailDraftRequest
     */
    outreachTaskId?: string;
}

/**
 * Check if a given object implements the CreateAnEmailDraftRequest interface.
 */
export function instanceOfCreateAnEmailDraftRequest(value: object): value is CreateAnEmailDraftRequest {
    if ((!('contactId' in value) && !('contact_id' in value)) || (value['contactId'] === undefined && value['contact_id'] === undefined)) return false;
    return true;
}

export function CreateAnEmailDraftRequestFromJSON(json: any): CreateAnEmailDraftRequest {
    return CreateAnEmailDraftRequestFromJSONTyped(json, false);
}

export function CreateAnEmailDraftRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateAnEmailDraftRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'contactId': json['contact_id'],
        'subject': json['subject'] == null ? undefined : json['subject'],
        'bodyHtml': json['body_html'] == null ? undefined : json['body_html'],
        'recipients': json['recipients'] == null ? undefined : ((json['recipients'] as Array<any>).map(CreateAnEmailDraftRequestRecipientsInnerFromJSON)),
        'inResponseToEmailerMessageId': json['in_response_to_emailer_message_id'] == null ? undefined : json['in_response_to_emailer_message_id'],
        'emailerTemplateId': json['emailer_template_id'] == null ? undefined : json['emailer_template_id'],
        'attachmentIds': json['attachment_ids'] == null ? undefined : json['attachment_ids'],
        'enableTracking': json['enable_tracking'] == null ? undefined : json['enable_tracking'],
        'outreachTaskId': json['outreach_task_id'] == null ? undefined : json['outreach_task_id'],
    };
}

export function CreateAnEmailDraftRequestToJSON(json: any): CreateAnEmailDraftRequest {
    return CreateAnEmailDraftRequestToJSONTyped(json, false);
}

export function CreateAnEmailDraftRequestToJSONTyped(value?: CreateAnEmailDraftRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'contact_id': value['contactId'],
        'subject': value['subject'],
        'body_html': value['bodyHtml'],
        'recipients': value['recipients'] == null ? undefined : ((value['recipients'] as Array<any>).map(CreateAnEmailDraftRequestRecipientsInnerToJSON)),
        'in_response_to_emailer_message_id': value['inResponseToEmailerMessageId'],
        'emailer_template_id': value['emailerTemplateId'],
        'attachment_ids': value['attachmentIds'],
        'enable_tracking': value['enableTracking'],
        'outreach_task_id': value['outreachTaskId'],
    };
}

