/* tslint:disable */
/* eslint-disable */
/**
 * apollo-rest-api
 * The Apollo API provides programmatic access to [Apollo](https://www.apollo.io/), the all-in-one sales intelligence and engagement platform. Use it to enrich people and company data (individually or in bulk), search Apollo\'s database of over 230 million contacts and 30 million companies, and manage accounts, contacts, deals, sequences, tasks, calls, and conversations in your go-to-market workflows.  ## Base URL  All API requests are made to `https://api.apollo.io/api/v1`.  ## Authentication  - **Apollo users** authenticate with an API key passed in the `x-api-key` request header. See [Create API Keys](https://docs.apollo.io/docs/create-api-key). - **Apollo partners** building integrations on behalf of mutual users authenticate with the [OAuth 2.0 authorization flow](https://docs.apollo.io/docs/use-oauth-20-authorization-flow-to-access-apollo-user-information-partners).  ## Rate limits & credits  Rate limits and credit consumption depend on your [Apollo pricing plan](https://docs.apollo.io/docs/api-pricing). Check your current limits and usage with the [View API Usage Stats and Rate Limits](https://docs.apollo.io/reference/view-api-usage-stats) endpoint. For more details, see [Rate Limits](https://docs.apollo.io/reference/rate-limits) and the [API FAQs](https://docs.apollo.io/docs/apollo-api-faqs).  New to the API? Start with the [Apollo API Overview](https://docs.apollo.io/docs/apollo-api-overview).
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetAListOfUsers200ResponsePagination
 */
export interface GetAListOfUsers200ResponsePagination {
    /**
     * 
     * @type {string}
     * @memberof GetAListOfUsers200ResponsePagination
     */
    page?: string;
    /**
     * 
     * @type {string}
     * @memberof GetAListOfUsers200ResponsePagination
     */
    perPage?: string;
    /**
     * 
     * @type {number}
     * @memberof GetAListOfUsers200ResponsePagination
     */
    totalEntries?: number;
    /**
     * 
     * @type {number}
     * @memberof GetAListOfUsers200ResponsePagination
     */
    totalPages?: number;
}

/**
 * Check if a given object implements the GetAListOfUsers200ResponsePagination interface.
 */
export function instanceOfGetAListOfUsers200ResponsePagination(value: object): value is GetAListOfUsers200ResponsePagination {
    return true;
}

export function GetAListOfUsers200ResponsePaginationFromJSON(json: any): GetAListOfUsers200ResponsePagination {
    return GetAListOfUsers200ResponsePaginationFromJSONTyped(json, false);
}

export function GetAListOfUsers200ResponsePaginationFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetAListOfUsers200ResponsePagination {
    if (json == null) {
        return json;
    }
    return {
        
        'page': json['page'] == null ? undefined : json['page'],
        'perPage': json['per_page'] == null ? undefined : json['per_page'],
        'totalEntries': json['total_entries'] == null ? undefined : json['total_entries'],
        'totalPages': json['total_pages'] == null ? undefined : json['total_pages'],
    };
}

export function GetAListOfUsers200ResponsePaginationToJSON(json: any): GetAListOfUsers200ResponsePagination {
    return GetAListOfUsers200ResponsePaginationToJSONTyped(json, false);
}

export function GetAListOfUsers200ResponsePaginationToJSONTyped(value?: GetAListOfUsers200ResponsePagination | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'page': value['page'],
        'per_page': value['perPage'],
        'total_entries': value['totalEntries'],
        'total_pages': value['totalPages'],
    };
}

