/* tslint:disable */
/* eslint-disable */
/**
 * apollo-rest-api
 * The Apollo API provides programmatic access to [Apollo](https://www.apollo.io/), the all-in-one sales intelligence and engagement platform. Use it to enrich people and company data (individually or in bulk), search Apollo\'s database of over 230 million contacts and 30 million companies, and manage accounts, contacts, deals, sequences, tasks, calls, and conversations in your go-to-market workflows.  ## Base URL  All API requests are made to `https://api.apollo.io/api/v1`.  ## Authentication  - **Apollo users** authenticate with an API key passed in the `x-api-key` request header. See [Create API Keys](https://docs.apollo.io/docs/create-api-key). - **Apollo partners** building integrations on behalf of mutual users authenticate with the [OAuth 2.0 authorization flow](https://docs.apollo.io/docs/use-oauth-20-authorization-flow-to-access-apollo-user-information-partners).  ## Rate limits & credits  Rate limits and credit consumption depend on your [Apollo pricing plan](https://docs.apollo.io/docs/api-pricing). Check your current limits and usage with the [View API Usage Stats and Rate Limits](https://docs.apollo.io/reference/view-api-usage-stats) endpoint. For more details, see [Rate Limits](https://docs.apollo.io/reference/rate-limits) and the [API FAQs](https://docs.apollo.io/docs/apollo-api-faqs).  New to the API? Start with the [Apollo API Overview](https://docs.apollo.io/docs/apollo-api-overview).
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetAListOfUsers200ResponseUsersInnerAssistantSetting
 */
export interface GetAListOfUsers200ResponseUsersInnerAssistantSetting {
    /**
     * 
     * @type {string}
     * @memberof GetAListOfUsers200ResponseUsersInnerAssistantSetting
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof GetAListOfUsers200ResponseUsersInnerAssistantSetting
     */
    dealSizeMetric?: string;
    /**
     * 
     * @type {Array<any>}
     * @memberof GetAListOfUsers200ResponseUsersInnerAssistantSetting
     */
    inactiveAccountStageIds?: Array<any>;
    /**
     * 
     * @type {Array<any>}
     * @memberof GetAListOfUsers200ResponseUsersInnerAssistantSetting
     */
    inactiveContactStageIds?: Array<any>;
    /**
     * 
     * @type {object}
     * @memberof GetAListOfUsers200ResponseUsersInnerAssistantSetting
     */
    insightDealSizeSignals?: object;
    /**
     * 
     * @type {object}
     * @memberof GetAListOfUsers200ResponseUsersInnerAssistantSetting
     */
    insightSaleCycleSignals?: object;
    /**
     * 
     * @type {object}
     * @memberof GetAListOfUsers200ResponseUsersInnerAssistantSetting
     */
    insightWinRateSignals?: object;
    /**
     * 
     * @type {boolean}
     * @memberof GetAListOfUsers200ResponseUsersInnerAssistantSetting
     */
    isPersonaRecommendationRequested?: boolean;
    /**
     * 
     * @type {Array<any>}
     * @memberof GetAListOfUsers200ResponseUsersInnerAssistantSetting
     */
    jobPostingLocations?: Array<any>;
    /**
     * 
     * @type {Array<any>}
     * @memberof GetAListOfUsers200ResponseUsersInnerAssistantSetting
     */
    jobPostingTitles?: Array<any>;
    /**
     * 
     * @type {number}
     * @memberof GetAListOfUsers200ResponseUsersInnerAssistantSetting
     */
    latestFundingDays?: number;
    /**
     * 
     * @type {number}
     * @memberof GetAListOfUsers200ResponseUsersInnerAssistantSetting
     */
    maxNumActiveAccounts?: number;
    /**
     * 
     * @type {number}
     * @memberof GetAListOfUsers200ResponseUsersInnerAssistantSetting
     */
    maxPeopleInSequencePerAccount?: number;
    /**
     * 
     * @type {number}
     * @memberof GetAListOfUsers200ResponseUsersInnerAssistantSetting
     */
    numInactiveDaysToReEngage?: number;
    /**
     * 
     * @type {Array<string>}
     * @memberof GetAListOfUsers200ResponseUsersInnerAssistantSetting
     */
    personaIds?: Array<string>;
    /**
     * 
     * @type {boolean}
     * @memberof GetAListOfUsers200ResponseUsersInnerAssistantSetting
     */
    shouldShowPersonaBanner?: boolean;
    /**
     * 
     * @type {Array<any>}
     * @memberof GetAListOfUsers200ResponseUsersInnerAssistantSetting
     */
    successCaseAccountStageIds?: Array<any>;
    /**
     * 
     * @type {string}
     * @memberof GetAListOfUsers200ResponseUsersInnerAssistantSetting
     */
    teamId?: string;
    /**
     * 
     * @type {Array<any>}
     * @memberof GetAListOfUsers200ResponseUsersInnerAssistantSetting
     */
    technologyUids?: Array<any>;
    /**
     * 
     * @type {Array<any>}
     * @memberof GetAListOfUsers200ResponseUsersInnerAssistantSetting
     */
    territoryCompanySizeRanges?: Array<any>;
    /**
     * 
     * @type {boolean}
     * @memberof GetAListOfUsers200ResponseUsersInnerAssistantSetting
     */
    territoryLocationOverride?: boolean;
    /**
     * 
     * @type {Array<string>}
     * @memberof GetAListOfUsers200ResponseUsersInnerAssistantSetting
     */
    territoryLocations?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof GetAListOfUsers200ResponseUsersInnerAssistantSetting
     */
    territoryPersonLocations?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof GetAListOfUsers200ResponseUsersInnerAssistantSetting
     */
    userId?: string;
    /**
     * 
     * @type {string}
     * @memberof GetAListOfUsers200ResponseUsersInnerAssistantSetting
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof GetAListOfUsers200ResponseUsersInnerAssistantSetting
     */
    key?: string;
}

/**
 * Check if a given object implements the GetAListOfUsers200ResponseUsersInnerAssistantSetting interface.
 */
export function instanceOfGetAListOfUsers200ResponseUsersInnerAssistantSetting(value: object): value is GetAListOfUsers200ResponseUsersInnerAssistantSetting {
    return true;
}

export function GetAListOfUsers200ResponseUsersInnerAssistantSettingFromJSON(json: any): GetAListOfUsers200ResponseUsersInnerAssistantSetting {
    return GetAListOfUsers200ResponseUsersInnerAssistantSettingFromJSONTyped(json, false);
}

export function GetAListOfUsers200ResponseUsersInnerAssistantSettingFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetAListOfUsers200ResponseUsersInnerAssistantSetting {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['_id'] == null ? undefined : json['_id'],
        'dealSizeMetric': json['deal_size_metric'] == null ? undefined : json['deal_size_metric'],
        'inactiveAccountStageIds': json['inactive_account_stage_ids'] == null ? undefined : json['inactive_account_stage_ids'],
        'inactiveContactStageIds': json['inactive_contact_stage_ids'] == null ? undefined : json['inactive_contact_stage_ids'],
        'insightDealSizeSignals': json['insight_deal_size_signals'] == null ? undefined : json['insight_deal_size_signals'],
        'insightSaleCycleSignals': json['insight_sale_cycle_signals'] == null ? undefined : json['insight_sale_cycle_signals'],
        'insightWinRateSignals': json['insight_win_rate_signals'] == null ? undefined : json['insight_win_rate_signals'],
        'isPersonaRecommendationRequested': json['is_persona_recommendation_requested'] == null ? undefined : json['is_persona_recommendation_requested'],
        'jobPostingLocations': json['job_posting_locations'] == null ? undefined : json['job_posting_locations'],
        'jobPostingTitles': json['job_posting_titles'] == null ? undefined : json['job_posting_titles'],
        'latestFundingDays': json['latest_funding_days'] == null ? undefined : json['latest_funding_days'],
        'maxNumActiveAccounts': json['max_num_active_accounts'] == null ? undefined : json['max_num_active_accounts'],
        'maxPeopleInSequencePerAccount': json['max_people_in_sequence_per_account'] == null ? undefined : json['max_people_in_sequence_per_account'],
        'numInactiveDaysToReEngage': json['num_inactive_days_to_re_engage'] == null ? undefined : json['num_inactive_days_to_re_engage'],
        'personaIds': json['persona_ids'] == null ? undefined : json['persona_ids'],
        'shouldShowPersonaBanner': json['should_show_persona_banner'] == null ? undefined : json['should_show_persona_banner'],
        'successCaseAccountStageIds': json['success_case_account_stage_ids'] == null ? undefined : json['success_case_account_stage_ids'],
        'teamId': json['team_id'] == null ? undefined : json['team_id'],
        'technologyUids': json['technology_uids'] == null ? undefined : json['technology_uids'],
        'territoryCompanySizeRanges': json['territory_company_size_ranges'] == null ? undefined : json['territory_company_size_ranges'],
        'territoryLocationOverride': json['territory_location_override'] == null ? undefined : json['territory_location_override'],
        'territoryLocations': json['territory_locations'] == null ? undefined : json['territory_locations'],
        'territoryPersonLocations': json['territory_person_locations'] == null ? undefined : json['territory_person_locations'],
        'userId': json['user_id'] == null ? undefined : json['user_id'],
        'id': json['id'] == null ? undefined : json['id'],
        'key': json['key'] == null ? undefined : json['key'],
    };
}

export function GetAListOfUsers200ResponseUsersInnerAssistantSettingToJSON(json: any): GetAListOfUsers200ResponseUsersInnerAssistantSetting {
    return GetAListOfUsers200ResponseUsersInnerAssistantSettingToJSONTyped(json, false);
}

export function GetAListOfUsers200ResponseUsersInnerAssistantSettingToJSONTyped(value?: GetAListOfUsers200ResponseUsersInnerAssistantSetting | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        '_id': value['id'],
        'deal_size_metric': value['dealSizeMetric'],
        'inactive_account_stage_ids': value['inactiveAccountStageIds'],
        'inactive_contact_stage_ids': value['inactiveContactStageIds'],
        'insight_deal_size_signals': value['insightDealSizeSignals'],
        'insight_sale_cycle_signals': value['insightSaleCycleSignals'],
        'insight_win_rate_signals': value['insightWinRateSignals'],
        'is_persona_recommendation_requested': value['isPersonaRecommendationRequested'],
        'job_posting_locations': value['jobPostingLocations'],
        'job_posting_titles': value['jobPostingTitles'],
        'latest_funding_days': value['latestFundingDays'],
        'max_num_active_accounts': value['maxNumActiveAccounts'],
        'max_people_in_sequence_per_account': value['maxPeopleInSequencePerAccount'],
        'num_inactive_days_to_re_engage': value['numInactiveDaysToReEngage'],
        'persona_ids': value['personaIds'],
        'should_show_persona_banner': value['shouldShowPersonaBanner'],
        'success_case_account_stage_ids': value['successCaseAccountStageIds'],
        'team_id': value['teamId'],
        'technology_uids': value['technologyUids'],
        'territory_company_size_ranges': value['territoryCompanySizeRanges'],
        'territory_location_override': value['territoryLocationOverride'],
        'territory_locations': value['territoryLocations'],
        'territory_person_locations': value['territoryPersonLocations'],
        'user_id': value['userId'],
        'id': value['id'],
        'key': value['key'],
    };
}

