/* tslint:disable */
/* eslint-disable */
/**
 * apollo-rest-api
 * The Apollo API provides programmatic access to [Apollo](https://www.apollo.io/), the all-in-one sales intelligence and engagement platform. Use it to enrich people and company data (individually or in bulk), search Apollo\'s database of over 230 million contacts and 30 million companies, and manage accounts, contacts, deals, sequences, tasks, calls, and conversations in your go-to-market workflows.  ## Base URL  All API requests are made to `https://api.apollo.io/api/v1`.  ## Authentication  - **Apollo users** authenticate with an API key passed in the `x-api-key` request header. See [Create API Keys](https://docs.apollo.io/docs/create-api-key). - **Apollo partners** building integrations on behalf of mutual users authenticate with the [OAuth 2.0 authorization flow](https://docs.apollo.io/docs/use-oauth-20-authorization-flow-to-access-apollo-user-information-partners).  ## Rate limits & credits  Rate limits and credit consumption depend on your [Apollo pricing plan](https://docs.apollo.io/docs/api-pricing). Check your current limits and usage with the [View API Usage Stats and Rate Limits](https://docs.apollo.io/reference/view-api-usage-stats) endpoint. For more details, see [Rate Limits](https://docs.apollo.io/reference/rate-limits) and the [API FAQs](https://docs.apollo.io/docs/apollo-api-faqs).  New to the API? Start with the [Apollo API Overview](https://docs.apollo.io/docs/apollo-api-overview).
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GetAListOfEmailAccounts200ResponseEmailAccountsInnerDeliverabilityScore } from './GetAListOfEmailAccounts200ResponseEmailAccountsInnerDeliverabilityScore';
import {
    GetAListOfEmailAccounts200ResponseEmailAccountsInnerDeliverabilityScoreFromJSON,
    GetAListOfEmailAccounts200ResponseEmailAccountsInnerDeliverabilityScoreFromJSONTyped,
    GetAListOfEmailAccounts200ResponseEmailAccountsInnerDeliverabilityScoreToJSON,
    GetAListOfEmailAccounts200ResponseEmailAccountsInnerDeliverabilityScoreToJSONTyped,
} from './GetAListOfEmailAccounts200ResponseEmailAccountsInnerDeliverabilityScore';
import type { GetAListOfEmailAccounts200ResponseEmailAccountsInnerTrueWarmupThresholds } from './GetAListOfEmailAccounts200ResponseEmailAccountsInnerTrueWarmupThresholds';
import {
    GetAListOfEmailAccounts200ResponseEmailAccountsInnerTrueWarmupThresholdsFromJSON,
    GetAListOfEmailAccounts200ResponseEmailAccountsInnerTrueWarmupThresholdsFromJSONTyped,
    GetAListOfEmailAccounts200ResponseEmailAccountsInnerTrueWarmupThresholdsToJSON,
    GetAListOfEmailAccounts200ResponseEmailAccountsInnerTrueWarmupThresholdsToJSONTyped,
} from './GetAListOfEmailAccounts200ResponseEmailAccountsInnerTrueWarmupThresholds';

/**
 * 
 * @export
 * @interface GetAListOfEmailAccounts200ResponseEmailAccountsInner
 */
export interface GetAListOfEmailAccounts200ResponseEmailAccountsInner {
    /**
     * 
     * @type {Array<string>}
     * @memberof GetAListOfEmailAccounts200ResponseEmailAccountsInner
     */
    aliases?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof GetAListOfEmailAccounts200ResponseEmailAccountsInner
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof GetAListOfEmailAccounts200ResponseEmailAccountsInner
     */
    userId?: string;
    /**
     * 
     * @type {string}
     * @memberof GetAListOfEmailAccounts200ResponseEmailAccountsInner
     */
    email?: string;
    /**
     * 
     * @type {string}
     * @memberof GetAListOfEmailAccounts200ResponseEmailAccountsInner
     */
    type?: string;
    /**
     * 
     * @type {boolean}
     * @memberof GetAListOfEmailAccounts200ResponseEmailAccountsInner
     */
    active?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof GetAListOfEmailAccounts200ResponseEmailAccountsInner
     */
    _default?: boolean;
    /**
     * 
     * @type {number}
     * @memberof GetAListOfEmailAccounts200ResponseEmailAccountsInner
     */
    secondsDelayBetweenEmails?: number;
    /**
     * 
     * @type {string}
     * @memberof GetAListOfEmailAccounts200ResponseEmailAccountsInner
     */
    providerDisplayName?: string;
    /**
     * 
     * @type {any}
     * @memberof GetAListOfEmailAccounts200ResponseEmailAccountsInner
     */
    nylasProvider?: any | null;
    /**
     * 
     * @type {string}
     * @memberof GetAListOfEmailAccounts200ResponseEmailAccountsInner
     */
    lastSyncedAt?: string;
    /**
     * 
     * @type {string}
     * @memberof GetAListOfEmailAccounts200ResponseEmailAccountsInner
     */
    emailSendingPolicyCd?: string;
    /**
     * 
     * @type {any}
     * @memberof GetAListOfEmailAccounts200ResponseEmailAccountsInner
     */
    sendgridApiUser?: any | null;
    /**
     * 
     * @type {any}
     * @memberof GetAListOfEmailAccounts200ResponseEmailAccountsInner
     */
    mailgunDomains?: any | null;
    /**
     * 
     * @type {any}
     * @memberof GetAListOfEmailAccounts200ResponseEmailAccountsInner
     */
    nylasApiVersion?: any | null;
    /**
     * 
     * @type {boolean}
     * @memberof GetAListOfEmailAccounts200ResponseEmailAccountsInner
     */
    signatureEditDisabled?: boolean;
    /**
     * 
     * @type {any}
     * @memberof GetAListOfEmailAccounts200ResponseEmailAccountsInner
     */
    revokedAt?: any | null;
    /**
     * 
     * @type {any}
     * @memberof GetAListOfEmailAccounts200ResponseEmailAccountsInner
     */
    inactiveReason?: any | null;
    /**
     * 
     * @type {string}
     * @memberof GetAListOfEmailAccounts200ResponseEmailAccountsInner
     */
    createdAt?: string;
    /**
     * 
     * @type {any}
     * @memberof GetAListOfEmailAccounts200ResponseEmailAccountsInner
     */
    sendgridApiKeyV3?: any | null;
    /**
     * 
     * @type {number}
     * @memberof GetAListOfEmailAccounts200ResponseEmailAccountsInner
     */
    emailDailyThreshold?: number;
    /**
     * 
     * @type {GetAListOfEmailAccounts200ResponseEmailAccountsInnerDeliverabilityScore}
     * @memberof GetAListOfEmailAccounts200ResponseEmailAccountsInner
     */
    deliverabilityScore?: GetAListOfEmailAccounts200ResponseEmailAccountsInnerDeliverabilityScore;
    /**
     * 
     * @type {number}
     * @memberof GetAListOfEmailAccounts200ResponseEmailAccountsInner
     */
    maxOutboundEmailsPerHour?: number;
    /**
     * 
     * @type {boolean}
     * @memberof GetAListOfEmailAccounts200ResponseEmailAccountsInner
     */
    limitsEditable?: boolean;
    /**
     * 
     * @type {any}
     * @memberof GetAListOfEmailAccounts200ResponseEmailAccountsInner
     */
    isOptedInMailwarming?: any | null;
    /**
     * 
     * @type {number}
     * @memberof GetAListOfEmailAccounts200ResponseEmailAccountsInner
     */
    mailwarmingMax?: number;
    /**
     * 
     * @type {number}
     * @memberof GetAListOfEmailAccounts200ResponseEmailAccountsInner
     */
    mailwarmingToSendDaily?: number;
    /**
     * 
     * @type {number}
     * @memberof GetAListOfEmailAccounts200ResponseEmailAccountsInner
     */
    mailwarmingToSendIncrementor?: number;
    /**
     * 
     * @type {string}
     * @memberof GetAListOfEmailAccounts200ResponseEmailAccountsInner
     */
    mailwarmingStatus?: string;
    /**
     * 
     * @type {any}
     * @memberof GetAListOfEmailAccounts200ResponseEmailAccountsInner
     */
    mailwarmingEta?: any | null;
    /**
     * 
     * @type {any}
     * @memberof GetAListOfEmailAccounts200ResponseEmailAccountsInner
     */
    mailwarmingSubjectToken?: any | null;
    /**
     * 
     * @type {number}
     * @memberof GetAListOfEmailAccounts200ResponseEmailAccountsInner
     */
    mailwarmingScore?: number;
    /**
     * 
     * @type {string}
     * @memberof GetAListOfEmailAccounts200ResponseEmailAccountsInner
     */
    mailwarmingScoreBanner?: string;
    /**
     * 
     * @type {boolean}
     * @memberof GetAListOfEmailAccounts200ResponseEmailAccountsInner
     */
    mailwarmingOnWeekdaysOnly?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof GetAListOfEmailAccounts200ResponseEmailAccountsInner
     */
    trueWarmupEnabled?: boolean;
    /**
     * 
     * @type {number}
     * @memberof GetAListOfEmailAccounts200ResponseEmailAccountsInner
     */
    trueWarmupDailyLimit?: number;
    /**
     * 
     * @type {number}
     * @memberof GetAListOfEmailAccounts200ResponseEmailAccountsInner
     */
    trueWarmupProgress?: number;
    /**
     * 
     * @type {any}
     * @memberof GetAListOfEmailAccounts200ResponseEmailAccountsInner
     */
    trueWarmupStatus?: any | null;
    /**
     * 
     * @type {any}
     * @memberof GetAListOfEmailAccounts200ResponseEmailAccountsInner
     */
    trueWarmupApproximateEndDate?: any | null;
    /**
     * 
     * @type {any}
     * @memberof GetAListOfEmailAccounts200ResponseEmailAccountsInner
     */
    trueWarmupLastThrottledAt?: any | null;
    /**
     * 
     * @type {boolean}
     * @memberof GetAListOfEmailAccounts200ResponseEmailAccountsInner
     */
    trueWarmupEnableThresholds?: boolean;
    /**
     * 
     * @type {GetAListOfEmailAccounts200ResponseEmailAccountsInnerTrueWarmupThresholds}
     * @memberof GetAListOfEmailAccounts200ResponseEmailAccountsInner
     */
    trueWarmupThresholds?: GetAListOfEmailAccounts200ResponseEmailAccountsInnerTrueWarmupThresholds;
    /**
     * 
     * @type {number}
     * @memberof GetAListOfEmailAccounts200ResponseEmailAccountsInner
     */
    activeCampaignsCount?: number;
    /**
     * 
     * @type {boolean}
     * @memberof GetAListOfEmailAccounts200ResponseEmailAccountsInner
     */
    nudgeUserToSendMails?: boolean;
    /**
     * 
     * @type {string}
     * @memberof GetAListOfEmailAccounts200ResponseEmailAccountsInner
     */
    signatureHtml?: string;
    /**
     * 
     * @type {boolean}
     * @memberof GetAListOfEmailAccounts200ResponseEmailAccountsInner
     */
    fieldsFullyLoaded?: boolean;
}

/**
 * Check if a given object implements the GetAListOfEmailAccounts200ResponseEmailAccountsInner interface.
 */
export function instanceOfGetAListOfEmailAccounts200ResponseEmailAccountsInner(value: object): value is GetAListOfEmailAccounts200ResponseEmailAccountsInner {
    return true;
}

export function GetAListOfEmailAccounts200ResponseEmailAccountsInnerFromJSON(json: any): GetAListOfEmailAccounts200ResponseEmailAccountsInner {
    return GetAListOfEmailAccounts200ResponseEmailAccountsInnerFromJSONTyped(json, false);
}

export function GetAListOfEmailAccounts200ResponseEmailAccountsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetAListOfEmailAccounts200ResponseEmailAccountsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'aliases': json['aliases'] == null ? undefined : json['aliases'],
        'id': json['id'] == null ? undefined : json['id'],
        'userId': json['user_id'] == null ? undefined : json['user_id'],
        'email': json['email'] == null ? undefined : json['email'],
        'type': json['type'] == null ? undefined : json['type'],
        'active': json['active'] == null ? undefined : json['active'],
        '_default': json['default'] == null ? undefined : json['default'],
        'secondsDelayBetweenEmails': json['seconds_delay_between_emails'] == null ? undefined : json['seconds_delay_between_emails'],
        'providerDisplayName': json['provider_display_name'] == null ? undefined : json['provider_display_name'],
        'nylasProvider': json['nylas_provider'] == null ? undefined : json['nylas_provider'],
        'lastSyncedAt': json['last_synced_at'] == null ? undefined : json['last_synced_at'],
        'emailSendingPolicyCd': json['email_sending_policy_cd'] == null ? undefined : json['email_sending_policy_cd'],
        'sendgridApiUser': json['sendgrid_api_user'] == null ? undefined : json['sendgrid_api_user'],
        'mailgunDomains': json['mailgun_domains'] == null ? undefined : json['mailgun_domains'],
        'nylasApiVersion': json['nylas_api_version'] == null ? undefined : json['nylas_api_version'],
        'signatureEditDisabled': json['signature_edit_disabled'] == null ? undefined : json['signature_edit_disabled'],
        'revokedAt': json['revoked_at'] == null ? undefined : json['revoked_at'],
        'inactiveReason': json['inactive_reason'] == null ? undefined : json['inactive_reason'],
        'createdAt': json['created_at'] == null ? undefined : json['created_at'],
        'sendgridApiKeyV3': json['sendgrid_api_key_v3'] == null ? undefined : json['sendgrid_api_key_v3'],
        'emailDailyThreshold': json['email_daily_threshold'] == null ? undefined : json['email_daily_threshold'],
        'deliverabilityScore': json['deliverability_score'] == null ? undefined : GetAListOfEmailAccounts200ResponseEmailAccountsInnerDeliverabilityScoreFromJSON(json['deliverability_score']),
        'maxOutboundEmailsPerHour': json['max_outbound_emails_per_hour'] == null ? undefined : json['max_outbound_emails_per_hour'],
        'limitsEditable': json['limits_editable'] == null ? undefined : json['limits_editable'],
        'isOptedInMailwarming': json['is_opted_in_mailwarming'] == null ? undefined : json['is_opted_in_mailwarming'],
        'mailwarmingMax': json['mailwarming_max'] == null ? undefined : json['mailwarming_max'],
        'mailwarmingToSendDaily': json['mailwarming_to_send_daily'] == null ? undefined : json['mailwarming_to_send_daily'],
        'mailwarmingToSendIncrementor': json['mailwarming_to_send_incrementor'] == null ? undefined : json['mailwarming_to_send_incrementor'],
        'mailwarmingStatus': json['mailwarming_status'] == null ? undefined : json['mailwarming_status'],
        'mailwarmingEta': json['mailwarming_eta'] == null ? undefined : json['mailwarming_eta'],
        'mailwarmingSubjectToken': json['mailwarming_subject_token'] == null ? undefined : json['mailwarming_subject_token'],
        'mailwarmingScore': json['mailwarming_score'] == null ? undefined : json['mailwarming_score'],
        'mailwarmingScoreBanner': json['mailwarming_score_banner'] == null ? undefined : json['mailwarming_score_banner'],
        'mailwarmingOnWeekdaysOnly': json['mailwarming_on_weekdays_only'] == null ? undefined : json['mailwarming_on_weekdays_only'],
        'trueWarmupEnabled': json['true_warmup_enabled'] == null ? undefined : json['true_warmup_enabled'],
        'trueWarmupDailyLimit': json['true_warmup_daily_limit'] == null ? undefined : json['true_warmup_daily_limit'],
        'trueWarmupProgress': json['true_warmup_progress'] == null ? undefined : json['true_warmup_progress'],
        'trueWarmupStatus': json['true_warmup_status'] == null ? undefined : json['true_warmup_status'],
        'trueWarmupApproximateEndDate': json['true_warmup_approximate_end_date'] == null ? undefined : json['true_warmup_approximate_end_date'],
        'trueWarmupLastThrottledAt': json['true_warmup_last_throttled_at'] == null ? undefined : json['true_warmup_last_throttled_at'],
        'trueWarmupEnableThresholds': json['true_warmup_enable_thresholds'] == null ? undefined : json['true_warmup_enable_thresholds'],
        'trueWarmupThresholds': json['true_warmup_thresholds'] == null ? undefined : GetAListOfEmailAccounts200ResponseEmailAccountsInnerTrueWarmupThresholdsFromJSON(json['true_warmup_thresholds']),
        'activeCampaignsCount': json['active_campaigns_count'] == null ? undefined : json['active_campaigns_count'],
        'nudgeUserToSendMails': json['nudge_user_to_send_mails'] == null ? undefined : json['nudge_user_to_send_mails'],
        'signatureHtml': json['signature_html'] == null ? undefined : json['signature_html'],
        'fieldsFullyLoaded': json['fields_fully_loaded'] == null ? undefined : json['fields_fully_loaded'],
    };
}

export function GetAListOfEmailAccounts200ResponseEmailAccountsInnerToJSON(json: any): GetAListOfEmailAccounts200ResponseEmailAccountsInner {
    return GetAListOfEmailAccounts200ResponseEmailAccountsInnerToJSONTyped(json, false);
}

export function GetAListOfEmailAccounts200ResponseEmailAccountsInnerToJSONTyped(value?: GetAListOfEmailAccounts200ResponseEmailAccountsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'aliases': value['aliases'],
        'id': value['id'],
        'user_id': value['userId'],
        'email': value['email'],
        'type': value['type'],
        'active': value['active'],
        'default': value['_default'],
        'seconds_delay_between_emails': value['secondsDelayBetweenEmails'],
        'provider_display_name': value['providerDisplayName'],
        'nylas_provider': value['nylasProvider'],
        'last_synced_at': value['lastSyncedAt'],
        'email_sending_policy_cd': value['emailSendingPolicyCd'],
        'sendgrid_api_user': value['sendgridApiUser'],
        'mailgun_domains': value['mailgunDomains'],
        'nylas_api_version': value['nylasApiVersion'],
        'signature_edit_disabled': value['signatureEditDisabled'],
        'revoked_at': value['revokedAt'],
        'inactive_reason': value['inactiveReason'],
        'created_at': value['createdAt'],
        'sendgrid_api_key_v3': value['sendgridApiKeyV3'],
        'email_daily_threshold': value['emailDailyThreshold'],
        'deliverability_score': GetAListOfEmailAccounts200ResponseEmailAccountsInnerDeliverabilityScoreToJSON(value['deliverabilityScore']),
        'max_outbound_emails_per_hour': value['maxOutboundEmailsPerHour'],
        'limits_editable': value['limitsEditable'],
        'is_opted_in_mailwarming': value['isOptedInMailwarming'],
        'mailwarming_max': value['mailwarmingMax'],
        'mailwarming_to_send_daily': value['mailwarmingToSendDaily'],
        'mailwarming_to_send_incrementor': value['mailwarmingToSendIncrementor'],
        'mailwarming_status': value['mailwarmingStatus'],
        'mailwarming_eta': value['mailwarmingEta'],
        'mailwarming_subject_token': value['mailwarmingSubjectToken'],
        'mailwarming_score': value['mailwarmingScore'],
        'mailwarming_score_banner': value['mailwarmingScoreBanner'],
        'mailwarming_on_weekdays_only': value['mailwarmingOnWeekdaysOnly'],
        'true_warmup_enabled': value['trueWarmupEnabled'],
        'true_warmup_daily_limit': value['trueWarmupDailyLimit'],
        'true_warmup_progress': value['trueWarmupProgress'],
        'true_warmup_status': value['trueWarmupStatus'],
        'true_warmup_approximate_end_date': value['trueWarmupApproximateEndDate'],
        'true_warmup_last_throttled_at': value['trueWarmupLastThrottledAt'],
        'true_warmup_enable_thresholds': value['trueWarmupEnableThresholds'],
        'true_warmup_thresholds': GetAListOfEmailAccounts200ResponseEmailAccountsInnerTrueWarmupThresholdsToJSON(value['trueWarmupThresholds']),
        'active_campaigns_count': value['activeCampaignsCount'],
        'nudge_user_to_send_mails': value['nudgeUserToSendMails'],
        'signature_html': value['signatureHtml'],
        'fields_fully_loaded': value['fieldsFullyLoaded'],
    };
}

