/* tslint:disable */
/* eslint-disable */
/**
 * apollo-rest-api
 * The Apollo API provides programmatic access to [Apollo](https://www.apollo.io/), the all-in-one sales intelligence and engagement platform. Use it to enrich people and company data (individually or in bulk), search Apollo\'s database of over 230 million contacts and 30 million companies, and manage accounts, contacts, deals, sequences, tasks, calls, and conversations in your go-to-market workflows.  ## Base URL  All API requests are made to `https://api.apollo.io/api/v1`.  ## Authentication  - **Apollo users** authenticate with an API key passed in the `x-api-key` request header. See [Create API Keys](https://docs.apollo.io/docs/create-api-key). - **Apollo partners** building integrations on behalf of mutual users authenticate with the [OAuth 2.0 authorization flow](https://docs.apollo.io/docs/use-oauth-20-authorization-flow-to-access-apollo-user-information-partners).  ## Rate limits & credits  Rate limits and credit consumption depend on your [Apollo pricing plan](https://docs.apollo.io/docs/api-pricing). Check your current limits and usage with the [View API Usage Stats and Rate Limits](https://docs.apollo.io/reference/view-api-usage-stats) endpoint. For more details, see [Rate Limits](https://docs.apollo.io/reference/rate-limits) and the [API FAQs](https://docs.apollo.io/docs/apollo-api-faqs).  New to the API? Start with the [Apollo API Overview](https://docs.apollo.io/docs/apollo-api-overview).
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * The contact associated with this task, when the task has one. Includes the same fields as the <a href="https://docs.apollo.io/reference/view-a-contact">View a Contact</a> endpoint's response.
 * @export
 * @interface GetATask200ResponseTaskContact
 */
export interface GetATask200ResponseTaskContact {
    /**
     * 
     * @type {string}
     * @memberof GetATask200ResponseTaskContact
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof GetATask200ResponseTaskContact
     */
    firstName?: string;
    /**
     * 
     * @type {string}
     * @memberof GetATask200ResponseTaskContact
     */
    lastName?: string;
    /**
     * 
     * @type {string}
     * @memberof GetATask200ResponseTaskContact
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof GetATask200ResponseTaskContact
     */
    email?: string;
    /**
     * 
     * @type {string}
     * @memberof GetATask200ResponseTaskContact
     */
    title?: string;
    /**
     * 
     * @type {string}
     * @memberof GetATask200ResponseTaskContact
     */
    organizationName?: string;
    /**
     * 
     * @type {string}
     * @memberof GetATask200ResponseTaskContact
     */
    accountId?: string;
    /**
     * 
     * @type {string}
     * @memberof GetATask200ResponseTaskContact
     */
    ownerId?: string;
    /**
     * 
     * @type {any}
     * @memberof GetATask200ResponseTaskContact
     */
    contactStageId?: any | null;
    /**
     * 
     * @type {string}
     * @memberof GetATask200ResponseTaskContact
     */
    linkedinUrl?: string;
    /**
     * 
     * @type {Array<any>}
     * @memberof GetATask200ResponseTaskContact
     */
    phoneNumbers?: Array<any>;
    /**
     * All known email addresses for this contact, with per-address verification status.
     * @type {Array<any>}
     * @memberof GetATask200ResponseTaskContact
     */
    contactEmails?: Array<any>;
    /**
     * 
     * @type {object}
     * @memberof GetATask200ResponseTaskContact
     */
    typedCustomFields?: object;
    /**
     * 
     * @type {Array<any>}
     * @memberof GetATask200ResponseTaskContact
     */
    labelIds?: Array<any>;
    /**
     * 
     * @type {string}
     * @memberof GetATask200ResponseTaskContact
     */
    createdAt?: string;
    /**
     * 
     * @type {string}
     * @memberof GetATask200ResponseTaskContact
     */
    updatedAt?: string;
}

/**
 * Check if a given object implements the GetATask200ResponseTaskContact interface.
 */
export function instanceOfGetATask200ResponseTaskContact(value: object): value is GetATask200ResponseTaskContact {
    return true;
}

export function GetATask200ResponseTaskContactFromJSON(json: any): GetATask200ResponseTaskContact {
    return GetATask200ResponseTaskContactFromJSONTyped(json, false);
}

export function GetATask200ResponseTaskContactFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetATask200ResponseTaskContact {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'firstName': json['first_name'] == null ? undefined : json['first_name'],
        'lastName': json['last_name'] == null ? undefined : json['last_name'],
        'name': json['name'] == null ? undefined : json['name'],
        'email': json['email'] == null ? undefined : json['email'],
        'title': json['title'] == null ? undefined : json['title'],
        'organizationName': json['organization_name'] == null ? undefined : json['organization_name'],
        'accountId': json['account_id'] == null ? undefined : json['account_id'],
        'ownerId': json['owner_id'] == null ? undefined : json['owner_id'],
        'contactStageId': json['contact_stage_id'] == null ? undefined : json['contact_stage_id'],
        'linkedinUrl': json['linkedin_url'] == null ? undefined : json['linkedin_url'],
        'phoneNumbers': json['phone_numbers'] == null ? undefined : json['phone_numbers'],
        'contactEmails': json['contact_emails'] == null ? undefined : json['contact_emails'],
        'typedCustomFields': json['typed_custom_fields'] == null ? undefined : json['typed_custom_fields'],
        'labelIds': json['label_ids'] == null ? undefined : json['label_ids'],
        'createdAt': json['created_at'] == null ? undefined : json['created_at'],
        'updatedAt': json['updated_at'] == null ? undefined : json['updated_at'],
    };
}

export function GetATask200ResponseTaskContactToJSON(json: any): GetATask200ResponseTaskContact {
    return GetATask200ResponseTaskContactToJSONTyped(json, false);
}

export function GetATask200ResponseTaskContactToJSONTyped(value?: GetATask200ResponseTaskContact | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'first_name': value['firstName'],
        'last_name': value['lastName'],
        'name': value['name'],
        'email': value['email'],
        'title': value['title'],
        'organization_name': value['organizationName'],
        'account_id': value['accountId'],
        'owner_id': value['ownerId'],
        'contact_stage_id': value['contactStageId'],
        'linkedin_url': value['linkedinUrl'],
        'phone_numbers': value['phoneNumbers'],
        'contact_emails': value['contactEmails'],
        'typed_custom_fields': value['typedCustomFields'],
        'label_ids': value['labelIds'],
        'created_at': value['createdAt'],
        'updated_at': value['updatedAt'],
    };
}

