/* tslint:disable */
/* eslint-disable */
/**
 * apollo-rest-api
 * The Apollo API provides programmatic access to [Apollo](https://www.apollo.io/), the all-in-one sales intelligence and engagement platform. Use it to enrich people and company data (individually or in bulk), search Apollo\'s database of over 230 million contacts and 30 million companies, and manage accounts, contacts, deals, sequences, tasks, calls, and conversations in your go-to-market workflows.  ## Base URL  All API requests are made to `https://api.apollo.io/api/v1`.  ## Authentication  - **Apollo users** authenticate with an API key passed in the `x-api-key` request header. See [Create API Keys](https://docs.apollo.io/docs/create-api-key). - **Apollo partners** building integrations on behalf of mutual users authenticate with the [OAuth 2.0 authorization flow](https://docs.apollo.io/docs/use-oauth-20-authorization-flow-to-access-apollo-user-information-partners).  ## Rate limits & credits  Rate limits and credit consumption depend on your [Apollo pricing plan](https://docs.apollo.io/docs/api-pricing). Check your current limits and usage with the [View API Usage Stats and Rate Limits](https://docs.apollo.io/reference/view-api-usage-stats) endpoint. For more details, see [Rate Limits](https://docs.apollo.io/reference/rate-limits) and the [API FAQs](https://docs.apollo.io/docs/apollo-api-faqs).  New to the API? Start with the [Apollo API Overview](https://docs.apollo.io/docs/apollo-api-overview).
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GetConversationsInfo200ResponseOpportunitiesInnerAccount } from './GetConversationsInfo200ResponseOpportunitiesInnerAccount';
import {
    GetConversationsInfo200ResponseOpportunitiesInnerAccountFromJSON,
    GetConversationsInfo200ResponseOpportunitiesInnerAccountFromJSONTyped,
    GetConversationsInfo200ResponseOpportunitiesInnerAccountToJSON,
    GetConversationsInfo200ResponseOpportunitiesInnerAccountToJSONTyped,
} from './GetConversationsInfo200ResponseOpportunitiesInnerAccount';

/**
 * 
 * @export
 * @interface GetConversationsInfo200ResponseOpportunitiesInner
 */
export interface GetConversationsInfo200ResponseOpportunitiesInner {
    /**
     * Opportunity ID.
     * @type {string}
     * @memberof GetConversationsInfo200ResponseOpportunitiesInner
     */
    id?: string;
    /**
     * Opportunity name.
     * @type {string}
     * @memberof GetConversationsInfo200ResponseOpportunitiesInner
     */
    name?: string;
    /**
     * Opportunity amount.
     * @type {number}
     * @memberof GetConversationsInfo200ResponseOpportunitiesInner
     */
    amount?: number;
    /**
     * Close date (ISO 8601).
     * @type {string}
     * @memberof GetConversationsInfo200ResponseOpportunitiesInner
     */
    closedDate?: string;
    /**
     * Creation timestamp (ISO 8601).
     * @type {string}
     * @memberof GetConversationsInfo200ResponseOpportunitiesInner
     */
    createdAt?: string;
    /**
     * Last CRM sync timestamp (ISO 8601).
     * @type {string}
     * @memberof GetConversationsInfo200ResponseOpportunitiesInner
     */
    lastSync?: string;
    /**
     * 
     * @type {GetConversationsInfo200ResponseOpportunitiesInnerAccount}
     * @memberof GetConversationsInfo200ResponseOpportunitiesInner
     */
    account?: GetConversationsInfo200ResponseOpportunitiesInnerAccount;
    /**
     * Deep link to the opportunity in the connected CRM.
     * @type {string}
     * @memberof GetConversationsInfo200ResponseOpportunitiesInner
     */
    crmRecordUrl?: string;
    /**
     * Opportunity ID in the connected CRM.
     * @type {string}
     * @memberof GetConversationsInfo200ResponseOpportunitiesInner
     */
    opportunityCrmId?: string;
    /**
     * ID of the opportunity stage.
     * @type {string}
     * @memberof GetConversationsInfo200ResponseOpportunitiesInner
     */
    opportunityStageId?: string;
    /**
     * Display name of the opportunity stage.
     * @type {string}
     * @memberof GetConversationsInfo200ResponseOpportunitiesInner
     */
    stageName?: string;
    /**
     * User ID of the opportunity owner.
     * @type {string}
     * @memberof GetConversationsInfo200ResponseOpportunitiesInner
     */
    ownerId?: string;
    /**
     * Original opportunity stage ID when the conversation was first associated.
     * @type {string}
     * @memberof GetConversationsInfo200ResponseOpportunitiesInner
     */
    initialOpportunityStageId?: string;
}

/**
 * Check if a given object implements the GetConversationsInfo200ResponseOpportunitiesInner interface.
 */
export function instanceOfGetConversationsInfo200ResponseOpportunitiesInner(value: object): value is GetConversationsInfo200ResponseOpportunitiesInner {
    return true;
}

export function GetConversationsInfo200ResponseOpportunitiesInnerFromJSON(json: any): GetConversationsInfo200ResponseOpportunitiesInner {
    return GetConversationsInfo200ResponseOpportunitiesInnerFromJSONTyped(json, false);
}

export function GetConversationsInfo200ResponseOpportunitiesInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetConversationsInfo200ResponseOpportunitiesInner {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'amount': json['amount'] == null ? undefined : json['amount'],
        'closedDate': json['closed_date'] == null ? undefined : json['closed_date'],
        'createdAt': json['created_at'] == null ? undefined : json['created_at'],
        'lastSync': json['last_sync'] == null ? undefined : json['last_sync'],
        'account': json['account'] == null ? undefined : GetConversationsInfo200ResponseOpportunitiesInnerAccountFromJSON(json['account']),
        'crmRecordUrl': json['crm_record_url'] == null ? undefined : json['crm_record_url'],
        'opportunityCrmId': json['opportunity_crm_id'] == null ? undefined : json['opportunity_crm_id'],
        'opportunityStageId': json['opportunity_stage_id'] == null ? undefined : json['opportunity_stage_id'],
        'stageName': json['stage_name'] == null ? undefined : json['stage_name'],
        'ownerId': json['owner_id'] == null ? undefined : json['owner_id'],
        'initialOpportunityStageId': json['initial_opportunity_stage_id'] == null ? undefined : json['initial_opportunity_stage_id'],
    };
}

export function GetConversationsInfo200ResponseOpportunitiesInnerToJSON(json: any): GetConversationsInfo200ResponseOpportunitiesInner {
    return GetConversationsInfo200ResponseOpportunitiesInnerToJSONTyped(json, false);
}

export function GetConversationsInfo200ResponseOpportunitiesInnerToJSONTyped(value?: GetConversationsInfo200ResponseOpportunitiesInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'amount': value['amount'],
        'closed_date': value['closedDate'],
        'created_at': value['createdAt'],
        'last_sync': value['lastSync'],
        'account': GetConversationsInfo200ResponseOpportunitiesInnerAccountToJSON(value['account']),
        'crm_record_url': value['crmRecordUrl'],
        'opportunity_crm_id': value['opportunityCrmId'],
        'opportunity_stage_id': value['opportunityStageId'],
        'stage_name': value['stageName'],
        'owner_id': value['ownerId'],
        'initial_opportunity_stage_id': value['initialOpportunityStageId'],
    };
}

