/* tslint:disable */
/* eslint-disable */
/**
 * apollo-rest-api
 * The Apollo API provides programmatic access to [Apollo](https://www.apollo.io/), the all-in-one sales intelligence and engagement platform. Use it to enrich people and company data (individually or in bulk), search Apollo\'s database of over 230 million contacts and 30 million companies, and manage accounts, contacts, deals, sequences, tasks, calls, and conversations in your go-to-market workflows.  ## Base URL  All API requests are made to `https://api.apollo.io/api/v1`.  ## Authentication  - **Apollo users** authenticate with an API key passed in the `x-api-key` request header. See [Create API Keys](https://docs.apollo.io/docs/create-api-key). - **Apollo partners** building integrations on behalf of mutual users authenticate with the [OAuth 2.0 authorization flow](https://docs.apollo.io/docs/use-oauth-20-authorization-flow-to-access-apollo-user-information-partners).  ## Rate limits & credits  Rate limits and credit consumption depend on your [Apollo pricing plan](https://docs.apollo.io/docs/api-pricing). Check your current limits and usage with the [View API Usage Stats and Rate Limits](https://docs.apollo.io/reference/view-api-usage-stats) endpoint. For more details, see [Rate Limits](https://docs.apollo.io/reference/rate-limits) and the [API FAQs](https://docs.apollo.io/docs/apollo-api-faqs).  New to the API? Start with the [Apollo API Overview](https://docs.apollo.io/docs/apollo-api-overview).
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GetConversationsInfo200ResponseOpportunitiesInner } from './GetConversationsInfo200ResponseOpportunitiesInner';
import {
    GetConversationsInfo200ResponseOpportunitiesInnerFromJSON,
    GetConversationsInfo200ResponseOpportunitiesInnerFromJSONTyped,
    GetConversationsInfo200ResponseOpportunitiesInnerToJSON,
    GetConversationsInfo200ResponseOpportunitiesInnerToJSONTyped,
} from './GetConversationsInfo200ResponseOpportunitiesInner';
import type { GetConversationsInfo200ResponseAudioRecording } from './GetConversationsInfo200ResponseAudioRecording';
import {
    GetConversationsInfo200ResponseAudioRecordingFromJSON,
    GetConversationsInfo200ResponseAudioRecordingFromJSONTyped,
    GetConversationsInfo200ResponseAudioRecordingToJSON,
    GetConversationsInfo200ResponseAudioRecordingToJSONTyped,
} from './GetConversationsInfo200ResponseAudioRecording';
import type { GetConversationsInfo200ResponseVideoRecording } from './GetConversationsInfo200ResponseVideoRecording';
import {
    GetConversationsInfo200ResponseVideoRecordingFromJSON,
    GetConversationsInfo200ResponseVideoRecordingFromJSONTyped,
    GetConversationsInfo200ResponseVideoRecordingToJSON,
    GetConversationsInfo200ResponseVideoRecordingToJSONTyped,
} from './GetConversationsInfo200ResponseVideoRecording';
import type { GetConversationsInfo200ResponseParticipants } from './GetConversationsInfo200ResponseParticipants';
import {
    GetConversationsInfo200ResponseParticipantsFromJSON,
    GetConversationsInfo200ResponseParticipantsFromJSONTyped,
    GetConversationsInfo200ResponseParticipantsToJSON,
    GetConversationsInfo200ResponseParticipantsToJSONTyped,
} from './GetConversationsInfo200ResponseParticipants';

/**
 * 
 * @export
 * @interface GetConversationsInfo200Response
 */
export interface GetConversationsInfo200Response {
    /**
     * Unique conversation ID.
     * @type {string}
     * @memberof GetConversationsInfo200Response
     */
    id?: string;
    /**
     * Conversation topic or title.
     * @type {string}
     * @memberof GetConversationsInfo200Response
     */
    topic?: string;
    /**
     * Conversation start time (ISO 8601). Apollo uses Greenwich Mean Time (GMT) for all date and time values.
     * @type {string}
     * @memberof GetConversationsInfo200Response
     */
    startTime?: string;
    /**
     * Duration of the conversation in seconds.
     * @type {number}
     * @memberof GetConversationsInfo200Response
     */
    duration?: number;
    /**
     * Current processing state of the conversation.
     * @type {string}
     * @memberof GetConversationsInfo200Response
     */
    state?: string;
    /**
     * Name of the conversation host.
     * @type {string}
     * @memberof GetConversationsInfo200Response
     */
    host?: string;
    /**
     * User ID of the conversation host.
     * @type {string}
     * @memberof GetConversationsInfo200Response
     */
    hostId?: string;
    /**
     * Privacy setting of the conversation.
     * @type {boolean}
     * @memberof GetConversationsInfo200Response
     */
    isPrivate?: boolean;
    /**
     * Whether the conversation has been pushed to a CRM.
     * @type {boolean}
     * @memberof GetConversationsInfo200Response
     */
    pushedToCrm?: boolean;
    /**
     * IDs of accounts associated with the conversation.
     * @type {Array<string>}
     * @memberof GetConversationsInfo200Response
     */
    accountIds?: Array<string>;
    /**
     * Map of label IDs to label names associated with the conversation.
     * @type {Array<string>}
     * @memberof GetConversationsInfo200Response
     */
    labelIdNames?: Array<string>;
    /**
     * Whether the conversation has been shared.
     * @type {boolean}
     * @memberof GetConversationsInfo200Response
     */
    isSharedConversation?: boolean;
    /**
     * IDs of opportunities associated with the conversation.
     * @type {Array<string>}
     * @memberof GetConversationsInfo200Response
     */
    opportunityIds?: Array<string>;
    /**
     * Number of comments on the conversation.
     * @type {number}
     * @memberof GetConversationsInfo200Response
     */
    commentCount?: number;
    /**
     * Error code if the conversation processing failed. Returns <code>null</code> if no failure occurred.
     * @type {string}
     * @memberof GetConversationsInfo200Response
     */
    failureCode?: string;
    /**
     * Reason the bot call ended. Returns <code>null</code> if not applicable.
     * @type {string}
     * @memberof GetConversationsInfo200Response
     */
    botCallEndedReason?: string;
    /**
     * Type of conversation.
     * @type {GetConversationsInfo200ResponseConversationTypeEnum}
     * @memberof GetConversationsInfo200Response
     */
    conversationType?: GetConversationsInfo200ResponseConversationTypeEnum;
    /**
     * Whether the conversation is a clip.
     * @type {boolean}
     * @memberof GetConversationsInfo200Response
     */
    isClip?: boolean;
    /**
     * 
     * @type {GetConversationsInfo200ResponseVideoRecording}
     * @memberof GetConversationsInfo200Response
     */
    videoRecording?: GetConversationsInfo200ResponseVideoRecording;
    /**
     * 
     * @type {GetConversationsInfo200ResponseAudioRecording}
     * @memberof GetConversationsInfo200Response
     */
    audioRecording?: GetConversationsInfo200ResponseAudioRecording;
    /**
     * Transcript of the conversation.
     * @type {Array<object>}
     * @memberof GetConversationsInfo200Response
     */
    transcript?: Array<object>;
    /**
     * 
     * @type {GetConversationsInfo200ResponseParticipants}
     * @memberof GetConversationsInfo200Response
     */
    participants?: GetConversationsInfo200ResponseParticipants;
    /**
     * Opportunities associated with the conversation.
     * @type {Array<GetConversationsInfo200ResponseOpportunitiesInner>}
     * @memberof GetConversationsInfo200Response
     */
    opportunities?: Array<GetConversationsInfo200ResponseOpportunitiesInner>;
    /**
     * IDs of the playlist clips associated with the conversation.
     * @type {Array<string>}
     * @memberof GetConversationsInfo200Response
     */
    playlistClipIds?: Array<string>;
}


/**
 * @export
 */
export const GetConversationsInfo200ResponseConversationTypeEnum = {
    VideoConference: 'video_conference',
    PhoneCall: 'phone_call'
} as const;
export type GetConversationsInfo200ResponseConversationTypeEnum = typeof GetConversationsInfo200ResponseConversationTypeEnum[keyof typeof GetConversationsInfo200ResponseConversationTypeEnum];


/**
 * Check if a given object implements the GetConversationsInfo200Response interface.
 */
export function instanceOfGetConversationsInfo200Response(value: object): value is GetConversationsInfo200Response {
    return true;
}

export function GetConversationsInfo200ResponseFromJSON(json: any): GetConversationsInfo200Response {
    return GetConversationsInfo200ResponseFromJSONTyped(json, false);
}

export function GetConversationsInfo200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetConversationsInfo200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'topic': json['topic'] == null ? undefined : json['topic'],
        'startTime': json['start_time'] == null ? undefined : json['start_time'],
        'duration': json['duration'] == null ? undefined : json['duration'],
        'state': json['state'] == null ? undefined : json['state'],
        'host': json['host'] == null ? undefined : json['host'],
        'hostId': json['host_id'] == null ? undefined : json['host_id'],
        'isPrivate': json['is_private'] == null ? undefined : json['is_private'],
        'pushedToCrm': json['pushed_to_crm'] == null ? undefined : json['pushed_to_crm'],
        'accountIds': json['account_ids'] == null ? undefined : json['account_ids'],
        'labelIdNames': json['label_id_names'] == null ? undefined : json['label_id_names'],
        'isSharedConversation': json['is_shared_conversation'] == null ? undefined : json['is_shared_conversation'],
        'opportunityIds': json['opportunity_ids'] == null ? undefined : json['opportunity_ids'],
        'commentCount': json['comment_count'] == null ? undefined : json['comment_count'],
        'failureCode': json['failure_code'] == null ? undefined : json['failure_code'],
        'botCallEndedReason': json['bot_call_ended_reason'] == null ? undefined : json['bot_call_ended_reason'],
        'conversationType': json['conversation_type'] == null ? undefined : json['conversation_type'],
        'isClip': json['is_clip'] == null ? undefined : json['is_clip'],
        'videoRecording': json['video_recording'] == null ? undefined : GetConversationsInfo200ResponseVideoRecordingFromJSON(json['video_recording']),
        'audioRecording': json['audio_recording'] == null ? undefined : GetConversationsInfo200ResponseAudioRecordingFromJSON(json['audio_recording']),
        'transcript': json['transcript'] == null ? undefined : json['transcript'],
        'participants': json['participants'] == null ? undefined : GetConversationsInfo200ResponseParticipantsFromJSON(json['participants']),
        'opportunities': json['opportunities'] == null ? undefined : ((json['opportunities'] as Array<any>).map(GetConversationsInfo200ResponseOpportunitiesInnerFromJSON)),
        'playlistClipIds': json['playlist_clip_ids'] == null ? undefined : json['playlist_clip_ids'],
    };
}

export function GetConversationsInfo200ResponseToJSON(json: any): GetConversationsInfo200Response {
    return GetConversationsInfo200ResponseToJSONTyped(json, false);
}

export function GetConversationsInfo200ResponseToJSONTyped(value?: GetConversationsInfo200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'topic': value['topic'],
        'start_time': value['startTime'],
        'duration': value['duration'],
        'state': value['state'],
        'host': value['host'],
        'host_id': value['hostId'],
        'is_private': value['isPrivate'],
        'pushed_to_crm': value['pushedToCrm'],
        'account_ids': value['accountIds'],
        'label_id_names': value['labelIdNames'],
        'is_shared_conversation': value['isSharedConversation'],
        'opportunity_ids': value['opportunityIds'],
        'comment_count': value['commentCount'],
        'failure_code': value['failureCode'],
        'bot_call_ended_reason': value['botCallEndedReason'],
        'conversation_type': value['conversationType'],
        'is_clip': value['isClip'],
        'video_recording': GetConversationsInfo200ResponseVideoRecordingToJSON(value['videoRecording']),
        'audio_recording': GetConversationsInfo200ResponseAudioRecordingToJSON(value['audioRecording']),
        'transcript': value['transcript'],
        'participants': GetConversationsInfo200ResponseParticipantsToJSON(value['participants']),
        'opportunities': value['opportunities'] == null ? undefined : ((value['opportunities'] as Array<any>).map(GetConversationsInfo200ResponseOpportunitiesInnerToJSON)),
        'playlist_clip_ids': value['playlistClipIds'],
    };
}

