/* tslint:disable */
/* eslint-disable */
/**
 * apollo-rest-api
 * The Apollo API provides programmatic access to [Apollo](https://www.apollo.io/), the all-in-one sales intelligence and engagement platform. Use it to enrich people and company data (individually or in bulk), search Apollo\'s database of over 230 million contacts and 30 million companies, and manage accounts, contacts, deals, sequences, tasks, calls, and conversations in your go-to-market workflows.  ## Base URL  All API requests are made to `https://api.apollo.io/api/v1`.  ## Authentication  - **Apollo users** authenticate with an API key passed in the `x-api-key` request header. See [Create API Keys](https://docs.apollo.io/docs/create-api-key). - **Apollo partners** building integrations on behalf of mutual users authenticate with the [OAuth 2.0 authorization flow](https://docs.apollo.io/docs/use-oauth-20-authorization-flow-to-access-apollo-user-information-partners).  ## Rate limits & credits  Rate limits and credit consumption depend on your [Apollo pricing plan](https://docs.apollo.io/docs/api-pricing). Check your current limits and usage with the [View API Usage Stats and Rate Limits](https://docs.apollo.io/reference/view-api-usage-stats) endpoint. For more details, see [Rate Limits](https://docs.apollo.io/reference/rate-limits) and the [API FAQs](https://docs.apollo.io/docs/apollo-api-faqs).  New to the API? Start with the [Apollo API Overview](https://docs.apollo.io/docs/apollo-api-overview).
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PeopleApiSearch200ResponsePeopleInnerOrganization } from './PeopleApiSearch200ResponsePeopleInnerOrganization';
import {
    PeopleApiSearch200ResponsePeopleInnerOrganizationFromJSON,
    PeopleApiSearch200ResponsePeopleInnerOrganizationFromJSONTyped,
    PeopleApiSearch200ResponsePeopleInnerOrganizationToJSON,
    PeopleApiSearch200ResponsePeopleInnerOrganizationToJSONTyped,
} from './PeopleApiSearch200ResponsePeopleInnerOrganization';

/**
 * 
 * @export
 * @interface PeopleApiSearch200ResponsePeopleInner
 */
export interface PeopleApiSearch200ResponsePeopleInner {
    /**
     * The Apollo ID for the person.
     * @type {string}
     * @memberof PeopleApiSearch200ResponsePeopleInner
     */
    id?: string;
    /**
     * The first name of the person.
     * @type {string}
     * @memberof PeopleApiSearch200ResponsePeopleInner
     */
    firstName?: string;
    /**
     * The last name of the person with the middle characters obfuscated for privacy. The format shows the first 2 characters, followed by asterisks, and then the last character.
     * @type {string}
     * @memberof PeopleApiSearch200ResponsePeopleInner
     */
    lastNameObfuscated?: string;
    /**
     * The job title of the person. This field may be null if the person's title is not available.
     * @type {string}
     * @memberof PeopleApiSearch200ResponsePeopleInner
     */
    title?: string | null;
    /**
     * The date and time when the person's data was last refreshed in Apollo's database.
     * @type {Date}
     * @memberof PeopleApiSearch200ResponsePeopleInner
     */
    lastRefreshedAt?: Date;
    /**
     * Indicates whether Apollo has a verified email address for this person.
     * @type {boolean}
     * @memberof PeopleApiSearch200ResponsePeopleInner
     */
    hasEmail?: boolean;
    /**
     * Indicates whether Apollo has city location data for this person.
     * @type {boolean}
     * @memberof PeopleApiSearch200ResponsePeopleInner
     */
    hasCity?: boolean;
    /**
     * Indicates whether Apollo has state location data for this person.
     * @type {boolean}
     * @memberof PeopleApiSearch200ResponsePeopleInner
     */
    hasState?: boolean;
    /**
     * Indicates whether Apollo has country location data for this person.
     * @type {boolean}
     * @memberof PeopleApiSearch200ResponsePeopleInner
     */
    hasCountry?: boolean;
    /**
     * Indicates whether Apollo has direct phone number data for this person. Returns `Yes` if available, or `Maybe: please request direct dial via people/bulk_match` if uncertain.
     * @type {string}
     * @memberof PeopleApiSearch200ResponsePeopleInner
     */
    hasDirectPhone?: string;
    /**
     * 
     * @type {PeopleApiSearch200ResponsePeopleInnerOrganization}
     * @memberof PeopleApiSearch200ResponsePeopleInner
     */
    organization?: PeopleApiSearch200ResponsePeopleInnerOrganization;
}

/**
 * Check if a given object implements the PeopleApiSearch200ResponsePeopleInner interface.
 */
export function instanceOfPeopleApiSearch200ResponsePeopleInner(value: object): value is PeopleApiSearch200ResponsePeopleInner {
    return true;
}

export function PeopleApiSearch200ResponsePeopleInnerFromJSON(json: any): PeopleApiSearch200ResponsePeopleInner {
    return PeopleApiSearch200ResponsePeopleInnerFromJSONTyped(json, false);
}

export function PeopleApiSearch200ResponsePeopleInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): PeopleApiSearch200ResponsePeopleInner {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'firstName': json['first_name'] == null ? undefined : json['first_name'],
        'lastNameObfuscated': json['last_name_obfuscated'] == null ? undefined : json['last_name_obfuscated'],
        'title': json['title'] == null ? undefined : json['title'],
        'lastRefreshedAt': json['last_refreshed_at'] == null ? undefined : (new Date(json['last_refreshed_at'])),
        'hasEmail': json['has_email'] == null ? undefined : json['has_email'],
        'hasCity': json['has_city'] == null ? undefined : json['has_city'],
        'hasState': json['has_state'] == null ? undefined : json['has_state'],
        'hasCountry': json['has_country'] == null ? undefined : json['has_country'],
        'hasDirectPhone': json['has_direct_phone'] == null ? undefined : json['has_direct_phone'],
        'organization': json['organization'] == null ? undefined : PeopleApiSearch200ResponsePeopleInnerOrganizationFromJSON(json['organization']),
    };
}

export function PeopleApiSearch200ResponsePeopleInnerToJSON(json: any): PeopleApiSearch200ResponsePeopleInner {
    return PeopleApiSearch200ResponsePeopleInnerToJSONTyped(json, false);
}

export function PeopleApiSearch200ResponsePeopleInnerToJSONTyped(value?: PeopleApiSearch200ResponsePeopleInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'first_name': value['firstName'],
        'last_name_obfuscated': value['lastNameObfuscated'],
        'title': value['title'],
        'last_refreshed_at': value['lastRefreshedAt'] == null ? value['lastRefreshedAt'] : value['lastRefreshedAt'].toISOString(),
        'has_email': value['hasEmail'],
        'has_city': value['hasCity'],
        'has_state': value['hasState'],
        'has_country': value['hasCountry'],
        'has_direct_phone': value['hasDirectPhone'],
        'organization': PeopleApiSearch200ResponsePeopleInnerOrganizationToJSON(value['organization']),
    };
}

