/* tslint:disable */
/* eslint-disable */
/**
 * apollo-rest-api
 * The Apollo API provides programmatic access to [Apollo](https://www.apollo.io/), the all-in-one sales intelligence and engagement platform. Use it to enrich people and company data (individually or in bulk), search Apollo\'s database of over 230 million contacts and 30 million companies, and manage accounts, contacts, deals, sequences, tasks, calls, and conversations in your go-to-market workflows.  ## Base URL  All API requests are made to `https://api.apollo.io/api/v1`.  ## Authentication  - **Apollo users** authenticate with an API key passed in the `x-api-key` request header. See [Create API Keys](https://docs.apollo.io/docs/create-api-key). - **Apollo partners** building integrations on behalf of mutual users authenticate with the [OAuth 2.0 authorization flow](https://docs.apollo.io/docs/use-oauth-20-authorization-flow-to-access-apollo-user-information-partners).  ## Rate limits & credits  Rate limits and credit consumption depend on your [Apollo pricing plan](https://docs.apollo.io/docs/api-pricing). Check your current limits and usage with the [View API Usage Stats and Rate Limits](https://docs.apollo.io/reference/view-api-usage-stats) endpoint. For more details, see [Rate Limits](https://docs.apollo.io/reference/rate-limits) and the [API FAQs](https://docs.apollo.io/docs/apollo-api-faqs).  New to the API? Start with the [Apollo API Overview](https://docs.apollo.io/docs/apollo-api-overview).
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PeopleEnrichment200ResponsePerson } from './PeopleEnrichment200ResponsePerson';
import {
    PeopleEnrichment200ResponsePersonFromJSON,
    PeopleEnrichment200ResponsePersonFromJSONTyped,
    PeopleEnrichment200ResponsePersonToJSON,
    PeopleEnrichment200ResponsePersonToJSONTyped,
} from './PeopleEnrichment200ResponsePerson';

/**
 * 
 * @export
 * @interface PeopleEnrichment200Response
 */
export interface PeopleEnrichment200Response {
    /**
     * The request ID for the enrichment request. Save this ID to map this request with the corresponding webhook result.
     * @type {number}
     * @memberof PeopleEnrichment200Response
     */
    requestId?: number;
    /**
     * 
     * @type {PeopleEnrichment200ResponsePerson}
     * @memberof PeopleEnrichment200Response
     */
    person?: PeopleEnrichment200ResponsePerson;
}

/**
 * Check if a given object implements the PeopleEnrichment200Response interface.
 */
export function instanceOfPeopleEnrichment200Response(value: object): value is PeopleEnrichment200Response {
    return true;
}

export function PeopleEnrichment200ResponseFromJSON(json: any): PeopleEnrichment200Response {
    return PeopleEnrichment200ResponseFromJSONTyped(json, false);
}

export function PeopleEnrichment200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PeopleEnrichment200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'requestId': json['request_id'] == null ? undefined : json['request_id'],
        'person': json['person'] == null ? undefined : PeopleEnrichment200ResponsePersonFromJSON(json['person']),
    };
}

export function PeopleEnrichment200ResponseToJSON(json: any): PeopleEnrichment200Response {
    return PeopleEnrichment200ResponseToJSONTyped(json, false);
}

export function PeopleEnrichment200ResponseToJSONTyped(value?: PeopleEnrichment200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'request_id': value['requestId'],
        'person': PeopleEnrichment200ResponsePersonToJSON(value['person']),
    };
}

