/* tslint:disable */
/* eslint-disable */
/**
 * apollo-rest-api
 * The Apollo API provides programmatic access to [Apollo](https://www.apollo.io/), the all-in-one sales intelligence and engagement platform. Use it to enrich people and company data (individually or in bulk), search Apollo\'s database of over 230 million contacts and 30 million companies, and manage accounts, contacts, deals, sequences, tasks, calls, and conversations in your go-to-market workflows.  ## Base URL  All API requests are made to `https://api.apollo.io/api/v1`.  ## Authentication  - **Apollo users** authenticate with an API key passed in the `x-api-key` request header. See [Create API Keys](https://docs.apollo.io/docs/create-api-key). - **Apollo partners** building integrations on behalf of mutual users authenticate with the [OAuth 2.0 authorization flow](https://docs.apollo.io/docs/use-oauth-20-authorization-flow-to-access-apollo-user-information-partners).  ## Rate limits & credits  Rate limits and credit consumption depend on your [Apollo pricing plan](https://docs.apollo.io/docs/api-pricing). Check your current limits and usage with the [View API Usage Stats and Rate Limits](https://docs.apollo.io/reference/view-api-usage-stats) endpoint. For more details, see [Rate Limits](https://docs.apollo.io/reference/rate-limits) and the [API FAQs](https://docs.apollo.io/docs/apollo-api-faqs).  New to the API? Start with the [Apollo API Overview](https://docs.apollo.io/docs/apollo-api-overview).
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PollWebhookResult200Response
 */
export interface PollWebhookResult200Response {
    /**
     * Echoes the <code>request_id</code> from the URL.
     * @type {string}
     * @memberof PollWebhookResult200Response
     */
    requestId?: string;
    /**
     * The current webhook status.
     * @type {PollWebhookResult200ResponseWebhookStatusEnum}
     * @memberof PollWebhookResult200Response
     */
    webhookStatus?: PollWebhookResult200ResponseWebhookStatusEnum;
    /**
     * The enrichment request type.
     * @type {PollWebhookResult200ResponseRequestTypeEnum}
     * @memberof PollWebhookResult200Response
     */
    requestType?: PollWebhookResult200ResponseRequestTypeEnum;
    /**
     * ISO 8601 UTC timestamp of the last webhook <code>POST</code> attempt. Returns <code>null</code> until Apollo makes the first dispatch attempt.
     * @type {string}
     * @memberof PollWebhookResult200Response
     */
    lastDispatchedAt?: string;
    /**
     * The error message from the last failed dispatch. This field is populated when <code>webhook_status</code> is <code>failed</code>.
     * @type {string}
     * @memberof PollWebhookResult200Response
     */
    failureReason?: string;
    /**
     * The original webhook payload that Apollo delivered, or would have delivered, to the customer webhook URL. The shape varies by <code>request_type</code>.
     * @type {{ [key: string]: any; }}
     * @memberof PollWebhookResult200Response
     */
    webhookResult?: { [key: string]: any; };
}


/**
 * @export
 */
export const PollWebhookResult200ResponseWebhookStatusEnum = {
    InProgress: 'in_progress',
    Success: 'success',
    Failed: 'failed'
} as const;
export type PollWebhookResult200ResponseWebhookStatusEnum = typeof PollWebhookResult200ResponseWebhookStatusEnum[keyof typeof PollWebhookResult200ResponseWebhookStatusEnum];

/**
 * @export
 */
export const PollWebhookResult200ResponseRequestTypeEnum = {
    Email: 'email',
    Phone: 'phone',
    Waterfall: 'waterfall'
} as const;
export type PollWebhookResult200ResponseRequestTypeEnum = typeof PollWebhookResult200ResponseRequestTypeEnum[keyof typeof PollWebhookResult200ResponseRequestTypeEnum];


/**
 * Check if a given object implements the PollWebhookResult200Response interface.
 */
export function instanceOfPollWebhookResult200Response(value: object): value is PollWebhookResult200Response {
    return true;
}

export function PollWebhookResult200ResponseFromJSON(json: any): PollWebhookResult200Response {
    return PollWebhookResult200ResponseFromJSONTyped(json, false);
}

export function PollWebhookResult200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PollWebhookResult200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'requestId': json['request_id'] == null ? undefined : json['request_id'],
        'webhookStatus': json['webhook_status'] == null ? undefined : json['webhook_status'],
        'requestType': json['request_type'] == null ? undefined : json['request_type'],
        'lastDispatchedAt': json['last_dispatched_at'] == null ? undefined : json['last_dispatched_at'],
        'failureReason': json['failure_reason'] == null ? undefined : json['failure_reason'],
        'webhookResult': json['webhook_result'] == null ? undefined : json['webhook_result'],
    };
}

export function PollWebhookResult200ResponseToJSON(json: any): PollWebhookResult200Response {
    return PollWebhookResult200ResponseToJSONTyped(json, false);
}

export function PollWebhookResult200ResponseToJSONTyped(value?: PollWebhookResult200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'request_id': value['requestId'],
        'webhook_status': value['webhookStatus'],
        'request_type': value['requestType'],
        'last_dispatched_at': value['lastDispatchedAt'],
        'failure_reason': value['failureReason'],
        'webhook_result': value['webhookResult'],
    };
}

