/* tslint:disable */
/* eslint-disable */
/**
 * apollo-rest-api
 * The Apollo API provides programmatic access to [Apollo](https://www.apollo.io/), the all-in-one sales intelligence and engagement platform. Use it to enrich people and company data (individually or in bulk), search Apollo\'s database of over 230 million contacts and 30 million companies, and manage accounts, contacts, deals, sequences, tasks, calls, and conversations in your go-to-market workflows.  ## Base URL  All API requests are made to `https://api.apollo.io/api/v1`.  ## Authentication  - **Apollo users** authenticate with an API key passed in the `x-api-key` request header. See [Create API Keys](https://docs.apollo.io/docs/create-api-key). - **Apollo partners** building integrations on behalf of mutual users authenticate with the [OAuth 2.0 authorization flow](https://docs.apollo.io/docs/use-oauth-20-authorization-flow-to-access-apollo-user-information-partners).  ## Rate limits & credits  Rate limits and credit consumption depend on your [Apollo pricing plan](https://docs.apollo.io/docs/api-pricing). Check your current limits and usage with the [View API Usage Stats and Rate Limits](https://docs.apollo.io/reference/view-api-usage-stats) endpoint. For more details, see [Rate Limits](https://docs.apollo.io/reference/rate-limits) and the [API FAQs](https://docs.apollo.io/docs/apollo-api-faqs).  New to the API? Start with the [Apollo API Overview](https://docs.apollo.io/docs/apollo-api-overview).
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { OrganizationSearch200ResponseBreadcrumbsInner } from './OrganizationSearch200ResponseBreadcrumbsInner';
import {
    OrganizationSearch200ResponseBreadcrumbsInnerFromJSON,
    OrganizationSearch200ResponseBreadcrumbsInnerFromJSONTyped,
    OrganizationSearch200ResponseBreadcrumbsInnerToJSON,
    OrganizationSearch200ResponseBreadcrumbsInnerToJSONTyped,
} from './OrganizationSearch200ResponseBreadcrumbsInner';
import type { OrganizationSearch200ResponsePagination } from './OrganizationSearch200ResponsePagination';
import {
    OrganizationSearch200ResponsePaginationFromJSON,
    OrganizationSearch200ResponsePaginationFromJSONTyped,
    OrganizationSearch200ResponsePaginationToJSON,
    OrganizationSearch200ResponsePaginationToJSONTyped,
} from './OrganizationSearch200ResponsePagination';
import type { SearchForSequences200ResponseEmailerCampaignsInner } from './SearchForSequences200ResponseEmailerCampaignsInner';
import {
    SearchForSequences200ResponseEmailerCampaignsInnerFromJSON,
    SearchForSequences200ResponseEmailerCampaignsInnerFromJSONTyped,
    SearchForSequences200ResponseEmailerCampaignsInnerToJSON,
    SearchForSequences200ResponseEmailerCampaignsInnerToJSONTyped,
} from './SearchForSequences200ResponseEmailerCampaignsInner';

/**
 * 
 * @export
 * @interface SearchForSequences200Response
 */
export interface SearchForSequences200Response {
    /**
     * 
     * @type {OrganizationSearch200ResponsePagination}
     * @memberof SearchForSequences200Response
     */
    pagination?: OrganizationSearch200ResponsePagination;
    /**
     * 
     * @type {Array<OrganizationSearch200ResponseBreadcrumbsInner>}
     * @memberof SearchForSequences200Response
     */
    breadcrumbs?: Array<OrganizationSearch200ResponseBreadcrumbsInner>;
    /**
     * 
     * @type {Array<SearchForSequences200ResponseEmailerCampaignsInner>}
     * @memberof SearchForSequences200Response
     */
    emailerCampaigns?: Array<SearchForSequences200ResponseEmailerCampaignsInner>;
    /**
     * 
     * @type {any}
     * @memberof SearchForSequences200Response
     */
    numFetchResult?: any | null;
}

/**
 * Check if a given object implements the SearchForSequences200Response interface.
 */
export function instanceOfSearchForSequences200Response(value: object): value is SearchForSequences200Response {
    return true;
}

export function SearchForSequences200ResponseFromJSON(json: any): SearchForSequences200Response {
    return SearchForSequences200ResponseFromJSONTyped(json, false);
}

export function SearchForSequences200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SearchForSequences200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'pagination': json['pagination'] == null ? undefined : OrganizationSearch200ResponsePaginationFromJSON(json['pagination']),
        'breadcrumbs': json['breadcrumbs'] == null ? undefined : ((json['breadcrumbs'] as Array<any>).map(OrganizationSearch200ResponseBreadcrumbsInnerFromJSON)),
        'emailerCampaigns': json['emailer_campaigns'] == null ? undefined : ((json['emailer_campaigns'] as Array<any>).map(SearchForSequences200ResponseEmailerCampaignsInnerFromJSON)),
        'numFetchResult': json['num_fetch_result'] == null ? undefined : json['num_fetch_result'],
    };
}

export function SearchForSequences200ResponseToJSON(json: any): SearchForSequences200Response {
    return SearchForSequences200ResponseToJSONTyped(json, false);
}

export function SearchForSequences200ResponseToJSONTyped(value?: SearchForSequences200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'pagination': OrganizationSearch200ResponsePaginationToJSON(value['pagination']),
        'breadcrumbs': value['breadcrumbs'] == null ? undefined : ((value['breadcrumbs'] as Array<any>).map(OrganizationSearch200ResponseBreadcrumbsInnerToJSON)),
        'emailer_campaigns': value['emailerCampaigns'] == null ? undefined : ((value['emailerCampaigns'] as Array<any>).map(SearchForSequences200ResponseEmailerCampaignsInnerToJSON)),
        'num_fetch_result': value['numFetchResult'],
    };
}

