/* tslint:disable */
/* eslint-disable */
/**
 * apollo-rest-api
 * The Apollo API provides programmatic access to [Apollo](https://www.apollo.io/), the all-in-one sales intelligence and engagement platform. Use it to enrich people and company data (individually or in bulk), search Apollo\'s database of over 230 million contacts and 30 million companies, and manage accounts, contacts, deals, sequences, tasks, calls, and conversations in your go-to-market workflows.  ## Base URL  All API requests are made to `https://api.apollo.io/api/v1`.  ## Authentication  - **Apollo users** authenticate with an API key passed in the `x-api-key` request header. See [Create API Keys](https://docs.apollo.io/docs/create-api-key). - **Apollo partners** building integrations on behalf of mutual users authenticate with the [OAuth 2.0 authorization flow](https://docs.apollo.io/docs/use-oauth-20-authorization-flow-to-access-apollo-user-information-partners).  ## Rate limits & credits  Rate limits and credit consumption depend on your [Apollo pricing plan](https://docs.apollo.io/docs/api-pricing). Check your current limits and usage with the [View API Usage Stats and Rate Limits](https://docs.apollo.io/reference/view-api-usage-stats) endpoint. For more details, see [Rate Limits](https://docs.apollo.io/reference/rate-limits) and the [API FAQs](https://docs.apollo.io/docs/apollo-api-faqs).  New to the API? Start with the [Apollo API Overview](https://docs.apollo.io/docs/apollo-api-overview).
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { CheckAccountStageIDs } from './CheckAccountStageIDs';
import {
    instanceOfCheckAccountStageIDs,
    CheckAccountStageIDsFromJSON,
    CheckAccountStageIDsFromJSONTyped,
    CheckAccountStageIDsToJSON,
} from './CheckAccountStageIDs';
import type { ChooseValidSortByFieldOption } from './ChooseValidSortByFieldOption';
import {
    instanceOfChooseValidSortByFieldOption,
    ChooseValidSortByFieldOptionFromJSON,
    ChooseValidSortByFieldOptionFromJSONTyped,
    ChooseValidSortByFieldOptionToJSON,
} from './ChooseValidSortByFieldOption';

/**
 * @type SearchForAccounts422Response
 * 
 * @export
 */
export type SearchForAccounts422Response = CheckAccountStageIDs | ChooseValidSortByFieldOption;

export function SearchForAccounts422ResponseFromJSON(json: any): SearchForAccounts422Response {
    return SearchForAccounts422ResponseFromJSONTyped(json, false);
}

export function SearchForAccounts422ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SearchForAccounts422Response {
    if (json == null) {
        return json;
    }
    if (typeof json !== 'object') {
        return json;
    }
    if (instanceOfCheckAccountStageIDs(json)) {
        return CheckAccountStageIDsFromJSONTyped(json, true);
    }
    if (instanceOfChooseValidSortByFieldOption(json)) {
        return ChooseValidSortByFieldOptionFromJSONTyped(json, true);
    }
    return {} as any;
}

export function SearchForAccounts422ResponseToJSON(json: any): any {
    return SearchForAccounts422ResponseToJSONTyped(json, false);
}

export function SearchForAccounts422ResponseToJSONTyped(value?: SearchForAccounts422Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    if (typeof value !== 'object') {
        return value;
    }
    if (instanceOfCheckAccountStageIDs(value)) {
        return CheckAccountStageIDsToJSON(value as CheckAccountStageIDs);
    }
    if (instanceOfChooseValidSortByFieldOption(value)) {
        return ChooseValidSortByFieldOptionToJSON(value as ChooseValidSortByFieldOption);
    }
    return {};
}

