/* tslint:disable */
/* eslint-disable */
/**
 * apollo-rest-api
 * The Apollo API provides programmatic access to [Apollo](https://www.apollo.io/), the all-in-one sales intelligence and engagement platform. Use it to enrich people and company data (individually or in bulk), search Apollo\'s database of over 230 million contacts and 30 million companies, and manage accounts, contacts, deals, sequences, tasks, calls, and conversations in your go-to-market workflows.  ## Base URL  All API requests are made to `https://api.apollo.io/api/v1`.  ## Authentication  - **Apollo users** authenticate with an API key passed in the `x-api-key` request header. See [Create API Keys](https://docs.apollo.io/docs/create-api-key). - **Apollo partners** building integrations on behalf of mutual users authenticate with the [OAuth 2.0 authorization flow](https://docs.apollo.io/docs/use-oauth-20-authorization-flow-to-access-apollo-user-information-partners).  ## Rate limits & credits  Rate limits and credit consumption depend on your [Apollo pricing plan](https://docs.apollo.io/docs/api-pricing). Check your current limits and usage with the [View API Usage Stats and Rate Limits](https://docs.apollo.io/reference/view-api-usage-stats) endpoint. For more details, see [Rate Limits](https://docs.apollo.io/reference/rate-limits) and the [API FAQs](https://docs.apollo.io/docs/apollo-api-faqs).  New to the API? Start with the [Apollo API Overview](https://docs.apollo.io/docs/apollo-api-overview).
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SearchTasks200ResponseFacetingTaskTypesInner } from './SearchTasks200ResponseFacetingTaskTypesInner';
import {
    SearchTasks200ResponseFacetingTaskTypesInnerFromJSON,
    SearchTasks200ResponseFacetingTaskTypesInnerFromJSONTyped,
    SearchTasks200ResponseFacetingTaskTypesInnerToJSON,
    SearchTasks200ResponseFacetingTaskTypesInnerToJSONTyped,
} from './SearchTasks200ResponseFacetingTaskTypesInner';

/**
 * 
 * @export
 * @interface SearchTasks200ResponseFaceting
 */
export interface SearchTasks200ResponseFaceting {
    /**
     * 
     * @type {Array<any>}
     * @memberof SearchTasks200ResponseFaceting
     */
    playbookStepFacets?: Array<any>;
    /**
     * 
     * @type {Array<any>}
     * @memberof SearchTasks200ResponseFaceting
     */
    personFunctionFacets?: Array<any>;
    /**
     * 
     * @type {Array<any>}
     * @memberof SearchTasks200ResponseFaceting
     */
    personSeniorityFacets?: Array<any>;
    /**
     * 
     * @type {Array<any>}
     * @memberof SearchTasks200ResponseFaceting
     */
    normalizedPersonTitleFacets?: Array<any>;
    /**
     * 
     * @type {Array<any>}
     * @memberof SearchTasks200ResponseFaceting
     */
    organizationIdsFacets?: Array<any>;
    /**
     * 
     * @type {Array<any>}
     * @memberof SearchTasks200ResponseFaceting
     */
    organizationIdsInQueryFacets?: Array<any>;
    /**
     * 
     * @type {Array<any>}
     * @memberof SearchTasks200ResponseFaceting
     */
    personPersonaFacets?: Array<any>;
    /**
     * 
     * @type {Array<any>}
     * @memberof SearchTasks200ResponseFaceting
     */
    organizationKeywordsFacets?: Array<any>;
    /**
     * 
     * @type {Array<any>}
     * @memberof SearchTasks200ResponseFaceting
     */
    linkedinIndustryFacets?: Array<any>;
    /**
     * 
     * @type {Array<any>}
     * @memberof SearchTasks200ResponseFaceting
     */
    numEmployeesFacets?: Array<any>;
    /**
     * 
     * @type {Array<any>}
     * @memberof SearchTasks200ResponseFaceting
     */
    revenuesFacets?: Array<any>;
    /**
     * 
     * @type {Array<any>}
     * @memberof SearchTasks200ResponseFaceting
     */
    currentlyUsingAnyOfTechnologyUidsFacets?: Array<any>;
    /**
     * 
     * @type {Array<any>}
     * @memberof SearchTasks200ResponseFaceting
     */
    currentlyUsingAllOfTechnologyUidsFacets?: Array<any>;
    /**
     * 
     * @type {Array<any>}
     * @memberof SearchTasks200ResponseFaceting
     */
    currentlyNotUsingAnyOfTechnologyUidsFacets?: Array<any>;
    /**
     * 
     * @type {Array<any>}
     * @memberof SearchTasks200ResponseFaceting
     */
    addedTechnologyUidsFacets?: Array<any>;
    /**
     * 
     * @type {Array<any>}
     * @memberof SearchTasks200ResponseFaceting
     */
    droppedTechnologyUidsFacets?: Array<any>;
    /**
     * 
     * @type {Array<any>}
     * @memberof SearchTasks200ResponseFaceting
     */
    latestFundingStageFacets?: Array<any>;
    /**
     * 
     * @type {Array<any>}
     * @memberof SearchTasks200ResponseFaceting
     */
    organizationTradingStatusFacets?: Array<any>;
    /**
     * 
     * @type {Array<any>}
     * @memberof SearchTasks200ResponseFaceting
     */
    personCityFacets?: Array<any>;
    /**
     * 
     * @type {Array<any>}
     * @memberof SearchTasks200ResponseFaceting
     */
    personStateFacets?: Array<any>;
    /**
     * 
     * @type {Array<any>}
     * @memberof SearchTasks200ResponseFaceting
     */
    personCountryFacets?: Array<any>;
    /**
     * 
     * @type {Array<any>}
     * @memberof SearchTasks200ResponseFaceting
     */
    organizationHqCityFacets?: Array<any>;
    /**
     * 
     * @type {Array<any>}
     * @memberof SearchTasks200ResponseFaceting
     */
    organizationHqStateFacets?: Array<any>;
    /**
     * 
     * @type {Array<any>}
     * @memberof SearchTasks200ResponseFaceting
     */
    organizationHqCountryFacets?: Array<any>;
    /**
     * 
     * @type {Array<any>}
     * @memberof SearchTasks200ResponseFaceting
     */
    organizationIntentScoringFacets?: Array<any>;
    /**
     * 
     * @type {Array<any>}
     * @memberof SearchTasks200ResponseFaceting
     */
    forecastCategoryFacets?: Array<any>;
    /**
     * 
     * @type {Array<any>}
     * @memberof SearchTasks200ResponseFaceting
     */
    intentTopicCountFacets?: Array<any>;
    /**
     * 
     * @type {Array<SearchTasks200ResponseFacetingTaskTypesInner>}
     * @memberof SearchTasks200ResponseFaceting
     */
    taskTypes?: Array<SearchTasks200ResponseFacetingTaskTypesInner>;
    /**
     * 
     * @type {Array<SearchTasks200ResponseFacetingTaskTypesInner>}
     * @memberof SearchTasks200ResponseFaceting
     */
    totalFacets?: Array<SearchTasks200ResponseFacetingTaskTypesInner>;
    /**
     * 
     * @type {Array<any>}
     * @memberof SearchTasks200ResponseFaceting
     */
    linkedinTask?: Array<any>;
    /**
     * 
     * @type {Array<any>}
     * @memberof SearchTasks200ResponseFaceting
     */
    contactStageFacets?: Array<any>;
}

/**
 * Check if a given object implements the SearchTasks200ResponseFaceting interface.
 */
export function instanceOfSearchTasks200ResponseFaceting(value: object): value is SearchTasks200ResponseFaceting {
    return true;
}

export function SearchTasks200ResponseFacetingFromJSON(json: any): SearchTasks200ResponseFaceting {
    return SearchTasks200ResponseFacetingFromJSONTyped(json, false);
}

export function SearchTasks200ResponseFacetingFromJSONTyped(json: any, ignoreDiscriminator: boolean): SearchTasks200ResponseFaceting {
    if (json == null) {
        return json;
    }
    return {
        
        'playbookStepFacets': json['playbook_step_facets'] == null ? undefined : json['playbook_step_facets'],
        'personFunctionFacets': json['person_function_facets'] == null ? undefined : json['person_function_facets'],
        'personSeniorityFacets': json['person_seniority_facets'] == null ? undefined : json['person_seniority_facets'],
        'normalizedPersonTitleFacets': json['normalized_person_title_facets'] == null ? undefined : json['normalized_person_title_facets'],
        'organizationIdsFacets': json['organization_ids_facets'] == null ? undefined : json['organization_ids_facets'],
        'organizationIdsInQueryFacets': json['organization_ids_in_query_facets'] == null ? undefined : json['organization_ids_in_query_facets'],
        'personPersonaFacets': json['person_persona_facets'] == null ? undefined : json['person_persona_facets'],
        'organizationKeywordsFacets': json['organization_keywords_facets'] == null ? undefined : json['organization_keywords_facets'],
        'linkedinIndustryFacets': json['linkedin_industry_facets'] == null ? undefined : json['linkedin_industry_facets'],
        'numEmployeesFacets': json['num_employees_facets'] == null ? undefined : json['num_employees_facets'],
        'revenuesFacets': json['revenues_facets'] == null ? undefined : json['revenues_facets'],
        'currentlyUsingAnyOfTechnologyUidsFacets': json['currently_using_any_of_technology_uids_facets'] == null ? undefined : json['currently_using_any_of_technology_uids_facets'],
        'currentlyUsingAllOfTechnologyUidsFacets': json['currently_using_all_of_technology_uids_facets'] == null ? undefined : json['currently_using_all_of_technology_uids_facets'],
        'currentlyNotUsingAnyOfTechnologyUidsFacets': json['currently_not_using_any_of_technology_uids_facets'] == null ? undefined : json['currently_not_using_any_of_technology_uids_facets'],
        'addedTechnologyUidsFacets': json['added_technology_uids_facets'] == null ? undefined : json['added_technology_uids_facets'],
        'droppedTechnologyUidsFacets': json['dropped_technology_uids_facets'] == null ? undefined : json['dropped_technology_uids_facets'],
        'latestFundingStageFacets': json['latest_funding_stage_facets'] == null ? undefined : json['latest_funding_stage_facets'],
        'organizationTradingStatusFacets': json['organization_trading_status_facets'] == null ? undefined : json['organization_trading_status_facets'],
        'personCityFacets': json['person_city_facets'] == null ? undefined : json['person_city_facets'],
        'personStateFacets': json['person_state_facets'] == null ? undefined : json['person_state_facets'],
        'personCountryFacets': json['person_country_facets'] == null ? undefined : json['person_country_facets'],
        'organizationHqCityFacets': json['organization_hq_city_facets'] == null ? undefined : json['organization_hq_city_facets'],
        'organizationHqStateFacets': json['organization_hq_state_facets'] == null ? undefined : json['organization_hq_state_facets'],
        'organizationHqCountryFacets': json['organization_hq_country_facets'] == null ? undefined : json['organization_hq_country_facets'],
        'organizationIntentScoringFacets': json['organization_intent_scoring_facets'] == null ? undefined : json['organization_intent_scoring_facets'],
        'forecastCategoryFacets': json['forecast_category_facets'] == null ? undefined : json['forecast_category_facets'],
        'intentTopicCountFacets': json['intent_topic_count_facets'] == null ? undefined : json['intent_topic_count_facets'],
        'taskTypes': json['task_types'] == null ? undefined : ((json['task_types'] as Array<any>).map(SearchTasks200ResponseFacetingTaskTypesInnerFromJSON)),
        'totalFacets': json['total_facets'] == null ? undefined : ((json['total_facets'] as Array<any>).map(SearchTasks200ResponseFacetingTaskTypesInnerFromJSON)),
        'linkedinTask': json['linkedin_task'] == null ? undefined : json['linkedin_task'],
        'contactStageFacets': json['contact_stage_facets'] == null ? undefined : json['contact_stage_facets'],
    };
}

export function SearchTasks200ResponseFacetingToJSON(json: any): SearchTasks200ResponseFaceting {
    return SearchTasks200ResponseFacetingToJSONTyped(json, false);
}

export function SearchTasks200ResponseFacetingToJSONTyped(value?: SearchTasks200ResponseFaceting | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'playbook_step_facets': value['playbookStepFacets'],
        'person_function_facets': value['personFunctionFacets'],
        'person_seniority_facets': value['personSeniorityFacets'],
        'normalized_person_title_facets': value['normalizedPersonTitleFacets'],
        'organization_ids_facets': value['organizationIdsFacets'],
        'organization_ids_in_query_facets': value['organizationIdsInQueryFacets'],
        'person_persona_facets': value['personPersonaFacets'],
        'organization_keywords_facets': value['organizationKeywordsFacets'],
        'linkedin_industry_facets': value['linkedinIndustryFacets'],
        'num_employees_facets': value['numEmployeesFacets'],
        'revenues_facets': value['revenuesFacets'],
        'currently_using_any_of_technology_uids_facets': value['currentlyUsingAnyOfTechnologyUidsFacets'],
        'currently_using_all_of_technology_uids_facets': value['currentlyUsingAllOfTechnologyUidsFacets'],
        'currently_not_using_any_of_technology_uids_facets': value['currentlyNotUsingAnyOfTechnologyUidsFacets'],
        'added_technology_uids_facets': value['addedTechnologyUidsFacets'],
        'dropped_technology_uids_facets': value['droppedTechnologyUidsFacets'],
        'latest_funding_stage_facets': value['latestFundingStageFacets'],
        'organization_trading_status_facets': value['organizationTradingStatusFacets'],
        'person_city_facets': value['personCityFacets'],
        'person_state_facets': value['personStateFacets'],
        'person_country_facets': value['personCountryFacets'],
        'organization_hq_city_facets': value['organizationHqCityFacets'],
        'organization_hq_state_facets': value['organizationHqStateFacets'],
        'organization_hq_country_facets': value['organizationHqCountryFacets'],
        'organization_intent_scoring_facets': value['organizationIntentScoringFacets'],
        'forecast_category_facets': value['forecastCategoryFacets'],
        'intent_topic_count_facets': value['intentTopicCountFacets'],
        'task_types': value['taskTypes'] == null ? undefined : ((value['taskTypes'] as Array<any>).map(SearchTasks200ResponseFacetingTaskTypesInnerToJSON)),
        'total_facets': value['totalFacets'] == null ? undefined : ((value['totalFacets'] as Array<any>).map(SearchTasks200ResponseFacetingTaskTypesInnerToJSON)),
        'linkedin_task': value['linkedinTask'],
        'contact_stage_facets': value['contactStageFacets'],
    };
}

