/* tslint:disable */
/* eslint-disable */
/**
 * apollo-rest-api
 * The Apollo API provides programmatic access to [Apollo](https://www.apollo.io/), the all-in-one sales intelligence and engagement platform. Use it to enrich people and company data (individually or in bulk), search Apollo\'s database of over 230 million contacts and 30 million companies, and manage accounts, contacts, deals, sequences, tasks, calls, and conversations in your go-to-market workflows.  ## Base URL  All API requests are made to `https://api.apollo.io/api/v1`.  ## Authentication  - **Apollo users** authenticate with an API key passed in the `x-api-key` request header. See [Create API Keys](https://docs.apollo.io/docs/create-api-key). - **Apollo partners** building integrations on behalf of mutual users authenticate with the [OAuth 2.0 authorization flow](https://docs.apollo.io/docs/use-oauth-20-authorization-flow-to-access-apollo-user-information-partners).  ## Rate limits & credits  Rate limits and credit consumption depend on your [Apollo pricing plan](https://docs.apollo.io/docs/api-pricing). Check your current limits and usage with the [View API Usage Stats and Rate Limits](https://docs.apollo.io/reference/view-api-usage-stats) endpoint. For more details, see [Rate Limits](https://docs.apollo.io/reference/rate-limits) and the [API FAQs](https://docs.apollo.io/docs/apollo-api-faqs).  New to the API? Start with the [Apollo API Overview](https://docs.apollo.io/docs/apollo-api-overview).
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CreateAnEmailDraft200ResponseEmailerMessageRecipientsInner } from './CreateAnEmailDraft200ResponseEmailerMessageRecipientsInner';
import {
    CreateAnEmailDraft200ResponseEmailerMessageRecipientsInnerFromJSON,
    CreateAnEmailDraft200ResponseEmailerMessageRecipientsInnerFromJSONTyped,
    CreateAnEmailDraft200ResponseEmailerMessageRecipientsInnerToJSON,
    CreateAnEmailDraft200ResponseEmailerMessageRecipientsInnerToJSONTyped,
} from './CreateAnEmailDraft200ResponseEmailerMessageRecipientsInner';
import type { CreateAnEmailDraft200ResponseEmailerMessageSendFrom } from './CreateAnEmailDraft200ResponseEmailerMessageSendFrom';
import {
    CreateAnEmailDraft200ResponseEmailerMessageSendFromFromJSON,
    CreateAnEmailDraft200ResponseEmailerMessageSendFromFromJSONTyped,
    CreateAnEmailDraft200ResponseEmailerMessageSendFromToJSON,
    CreateAnEmailDraft200ResponseEmailerMessageSendFromToJSONTyped,
} from './CreateAnEmailDraft200ResponseEmailerMessageSendFrom';
import type { CreateAnEmailDraft200ResponseEmailerMessageContact } from './CreateAnEmailDraft200ResponseEmailerMessageContact';
import {
    CreateAnEmailDraft200ResponseEmailerMessageContactFromJSON,
    CreateAnEmailDraft200ResponseEmailerMessageContactFromJSONTyped,
    CreateAnEmailDraft200ResponseEmailerMessageContactToJSON,
    CreateAnEmailDraft200ResponseEmailerMessageContactToJSONTyped,
} from './CreateAnEmailDraft200ResponseEmailerMessageContact';

/**
 * 
 * @export
 * @interface SendEmailNow200ResponseEmailerMessage
 */
export interface SendEmailNow200ResponseEmailerMessage {
    /**
     * 
     * @type {string}
     * @memberof SendEmailNow200ResponseEmailerMessage
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof SendEmailNow200ResponseEmailerMessage
     */
    userId?: string;
    /**
     * 
     * @type {string}
     * @memberof SendEmailNow200ResponseEmailerMessage
     */
    status?: string;
    /**
     * 
     * @type {string}
     * @memberof SendEmailNow200ResponseEmailerMessage
     */
    toName?: string;
    /**
     * 
     * @type {string}
     * @memberof SendEmailNow200ResponseEmailerMessage
     */
    dueAt?: string;
    /**
     * 
     * @type {any}
     * @memberof SendEmailNow200ResponseEmailerMessage
     */
    completedAt?: any | null;
    /**
     * 
     * @type {any}
     * @memberof SendEmailNow200ResponseEmailerMessage
     */
    emailerCampaignId?: any | null;
    /**
     * 
     * @type {Array<any>}
     * @memberof SendEmailNow200ResponseEmailerMessage
     */
    attachmentIds?: Array<any>;
    /**
     * 
     * @type {boolean}
     * @memberof SendEmailNow200ResponseEmailerMessage
     */
    enableTracking?: boolean;
    /**
     * 
     * @type {string}
     * @memberof SendEmailNow200ResponseEmailerMessage
     */
    type?: string;
    /**
     * 
     * @type {string}
     * @memberof SendEmailNow200ResponseEmailerMessage
     */
    contactId?: string;
    /**
     * 
     * @type {string}
     * @memberof SendEmailNow200ResponseEmailerMessage
     */
    emailAccountId?: string;
    /**
     * 
     * @type {boolean}
     * @memberof SendEmailNow200ResponseEmailerMessage
     */
    dueAtManuallyChanged?: boolean;
    /**
     * 
     * @type {string}
     * @memberof SendEmailNow200ResponseEmailerMessage
     */
    dueAtSource?: string;
    /**
     * 
     * @type {boolean}
     * @memberof SendEmailNow200ResponseEmailerMessage
     */
    asyncSending?: boolean;
    /**
     * 
     * @type {string}
     * @memberof SendEmailNow200ResponseEmailerMessage
     */
    createdAt?: string;
    /**
     * 
     * @type {string}
     * @memberof SendEmailNow200ResponseEmailerMessage
     */
    accountId?: string;
    /**
     * 
     * @type {boolean}
     * @memberof SendEmailNow200ResponseEmailerMessage
     */
    clickTrackingEnabled?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof SendEmailNow200ResponseEmailerMessage
     */
    openTrackingEnabled?: boolean;
    /**
     * 
     * @type {Array<CreateAnEmailDraft200ResponseEmailerMessageRecipientsInner>}
     * @memberof SendEmailNow200ResponseEmailerMessage
     */
    recipients?: Array<CreateAnEmailDraft200ResponseEmailerMessageRecipientsInner>;
    /**
     * 
     * @type {CreateAnEmailDraft200ResponseEmailerMessageSendFrom}
     * @memberof SendEmailNow200ResponseEmailerMessage
     */
    sendFrom?: CreateAnEmailDraft200ResponseEmailerMessageSendFrom;
    /**
     * 
     * @type {string}
     * @memberof SendEmailNow200ResponseEmailerMessage
     */
    fromEmail?: string;
    /**
     * 
     * @type {string}
     * @memberof SendEmailNow200ResponseEmailerMessage
     */
    toEmail?: string;
    /**
     * 
     * @type {any}
     * @memberof SendEmailNow200ResponseEmailerMessage
     */
    fromName?: any | null;
    /**
     * 
     * @type {Array<any>}
     * @memberof SendEmailNow200ResponseEmailerMessage
     */
    bccEmails?: Array<any>;
    /**
     * 
     * @type {Array<any>}
     * @memberof SendEmailNow200ResponseEmailerMessage
     */
    ccEmails?: Array<any>;
    /**
     * 
     * @type {string}
     * @memberof SendEmailNow200ResponseEmailerMessage
     */
    sendFromInfo?: string;
    /**
     * 
     * @type {string}
     * @memberof SendEmailNow200ResponseEmailerMessage
     */
    bodyText?: string;
    /**
     * 
     * @type {string}
     * @memberof SendEmailNow200ResponseEmailerMessage
     */
    bodyHtml?: string;
    /**
     * 
     * @type {boolean}
     * @memberof SendEmailNow200ResponseEmailerMessage
     */
    bodyHtmlLoaded?: boolean;
    /**
     * 
     * @type {string}
     * @memberof SendEmailNow200ResponseEmailerMessage
     */
    subject?: string;
    /**
     * 
     * @type {CreateAnEmailDraft200ResponseEmailerMessageContact}
     * @memberof SendEmailNow200ResponseEmailerMessage
     */
    contact?: CreateAnEmailDraft200ResponseEmailerMessageContact;
}

/**
 * Check if a given object implements the SendEmailNow200ResponseEmailerMessage interface.
 */
export function instanceOfSendEmailNow200ResponseEmailerMessage(value: object): value is SendEmailNow200ResponseEmailerMessage {
    return true;
}

export function SendEmailNow200ResponseEmailerMessageFromJSON(json: any): SendEmailNow200ResponseEmailerMessage {
    return SendEmailNow200ResponseEmailerMessageFromJSONTyped(json, false);
}

export function SendEmailNow200ResponseEmailerMessageFromJSONTyped(json: any, ignoreDiscriminator: boolean): SendEmailNow200ResponseEmailerMessage {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'userId': json['user_id'] == null ? undefined : json['user_id'],
        'status': json['status'] == null ? undefined : json['status'],
        'toName': json['to_name'] == null ? undefined : json['to_name'],
        'dueAt': json['due_at'] == null ? undefined : json['due_at'],
        'completedAt': json['completed_at'] == null ? undefined : json['completed_at'],
        'emailerCampaignId': json['emailer_campaign_id'] == null ? undefined : json['emailer_campaign_id'],
        'attachmentIds': json['attachment_ids'] == null ? undefined : json['attachment_ids'],
        'enableTracking': json['enable_tracking'] == null ? undefined : json['enable_tracking'],
        'type': json['type'] == null ? undefined : json['type'],
        'contactId': json['contact_id'] == null ? undefined : json['contact_id'],
        'emailAccountId': json['email_account_id'] == null ? undefined : json['email_account_id'],
        'dueAtManuallyChanged': json['due_at_manually_changed'] == null ? undefined : json['due_at_manually_changed'],
        'dueAtSource': json['due_at_source'] == null ? undefined : json['due_at_source'],
        'asyncSending': json['async_sending'] == null ? undefined : json['async_sending'],
        'createdAt': json['created_at'] == null ? undefined : json['created_at'],
        'accountId': json['account_id'] == null ? undefined : json['account_id'],
        'clickTrackingEnabled': json['click_tracking_enabled'] == null ? undefined : json['click_tracking_enabled'],
        'openTrackingEnabled': json['open_tracking_enabled'] == null ? undefined : json['open_tracking_enabled'],
        'recipients': json['recipients'] == null ? undefined : ((json['recipients'] as Array<any>).map(CreateAnEmailDraft200ResponseEmailerMessageRecipientsInnerFromJSON)),
        'sendFrom': json['send_from'] == null ? undefined : CreateAnEmailDraft200ResponseEmailerMessageSendFromFromJSON(json['send_from']),
        'fromEmail': json['from_email'] == null ? undefined : json['from_email'],
        'toEmail': json['to_email'] == null ? undefined : json['to_email'],
        'fromName': json['from_name'] == null ? undefined : json['from_name'],
        'bccEmails': json['bcc_emails'] == null ? undefined : json['bcc_emails'],
        'ccEmails': json['cc_emails'] == null ? undefined : json['cc_emails'],
        'sendFromInfo': json['send_from_info'] == null ? undefined : json['send_from_info'],
        'bodyText': json['body_text'] == null ? undefined : json['body_text'],
        'bodyHtml': json['body_html'] == null ? undefined : json['body_html'],
        'bodyHtmlLoaded': json['body_html_loaded'] == null ? undefined : json['body_html_loaded'],
        'subject': json['subject'] == null ? undefined : json['subject'],
        'contact': json['contact'] == null ? undefined : CreateAnEmailDraft200ResponseEmailerMessageContactFromJSON(json['contact']),
    };
}

export function SendEmailNow200ResponseEmailerMessageToJSON(json: any): SendEmailNow200ResponseEmailerMessage {
    return SendEmailNow200ResponseEmailerMessageToJSONTyped(json, false);
}

export function SendEmailNow200ResponseEmailerMessageToJSONTyped(value?: SendEmailNow200ResponseEmailerMessage | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'user_id': value['userId'],
        'status': value['status'],
        'to_name': value['toName'],
        'due_at': value['dueAt'],
        'completed_at': value['completedAt'],
        'emailer_campaign_id': value['emailerCampaignId'],
        'attachment_ids': value['attachmentIds'],
        'enable_tracking': value['enableTracking'],
        'type': value['type'],
        'contact_id': value['contactId'],
        'email_account_id': value['emailAccountId'],
        'due_at_manually_changed': value['dueAtManuallyChanged'],
        'due_at_source': value['dueAtSource'],
        'async_sending': value['asyncSending'],
        'created_at': value['createdAt'],
        'account_id': value['accountId'],
        'click_tracking_enabled': value['clickTrackingEnabled'],
        'open_tracking_enabled': value['openTrackingEnabled'],
        'recipients': value['recipients'] == null ? undefined : ((value['recipients'] as Array<any>).map(CreateAnEmailDraft200ResponseEmailerMessageRecipientsInnerToJSON)),
        'send_from': CreateAnEmailDraft200ResponseEmailerMessageSendFromToJSON(value['sendFrom']),
        'from_email': value['fromEmail'],
        'to_email': value['toEmail'],
        'from_name': value['fromName'],
        'bcc_emails': value['bccEmails'],
        'cc_emails': value['ccEmails'],
        'send_from_info': value['sendFromInfo'],
        'body_text': value['bodyText'],
        'body_html': value['bodyHtml'],
        'body_html_loaded': value['bodyHtmlLoaded'],
        'subject': value['subject'],
        'contact': CreateAnEmailDraft200ResponseEmailerMessageContactToJSON(value['contact']),
    };
}

