/* tslint:disable */
/* eslint-disable */
/**
 * apollo-rest-api
 * The Apollo API provides programmatic access to [Apollo](https://www.apollo.io/), the all-in-one sales intelligence and engagement platform. Use it to enrich people and company data (individually or in bulk), search Apollo\'s database of over 230 million contacts and 30 million companies, and manage accounts, contacts, deals, sequences, tasks, calls, and conversations in your go-to-market workflows.  ## Base URL  All API requests are made to `https://api.apollo.io/api/v1`.  ## Authentication  - **Apollo users** authenticate with an API key passed in the `x-api-key` request header. See [Create API Keys](https://docs.apollo.io/docs/create-api-key). - **Apollo partners** building integrations on behalf of mutual users authenticate with the [OAuth 2.0 authorization flow](https://docs.apollo.io/docs/use-oauth-20-authorization-flow-to-access-apollo-user-information-partners).  ## Rate limits & credits  Rate limits and credit consumption depend on your [Apollo pricing plan](https://docs.apollo.io/docs/api-pricing). Check your current limits and usage with the [View API Usage Stats and Rate Limits](https://docs.apollo.io/reference/view-api-usage-stats) endpoint. For more details, see [Rate Limits](https://docs.apollo.io/reference/rate-limits) and the [API FAQs](https://docs.apollo.io/docs/apollo-api-faqs).  New to the API? Start with the [Apollo API Overview](https://docs.apollo.io/docs/apollo-api-overview).
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SkipATask200ResponseTask } from './SkipATask200ResponseTask';
import {
    SkipATask200ResponseTaskFromJSON,
    SkipATask200ResponseTaskFromJSONTyped,
    SkipATask200ResponseTaskToJSON,
    SkipATask200ResponseTaskToJSONTyped,
} from './SkipATask200ResponseTask';

/**
 * 
 * @export
 * @interface SkipATask200Response
 */
export interface SkipATask200Response {
    /**
     * 
     * @type {SkipATask200ResponseTask}
     * @memberof SkipATask200Response
     */
    task?: SkipATask200ResponseTask;
}

/**
 * Check if a given object implements the SkipATask200Response interface.
 */
export function instanceOfSkipATask200Response(value: object): value is SkipATask200Response {
    return true;
}

export function SkipATask200ResponseFromJSON(json: any): SkipATask200Response {
    return SkipATask200ResponseFromJSONTyped(json, false);
}

export function SkipATask200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SkipATask200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'task': json['task'] == null ? undefined : SkipATask200ResponseTaskFromJSON(json['task']),
    };
}

export function SkipATask200ResponseToJSON(json: any): SkipATask200Response {
    return SkipATask200ResponseToJSONTyped(json, false);
}

export function SkipATask200ResponseToJSONTyped(value?: SkipATask200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'task': SkipATask200ResponseTaskToJSON(value['task']),
    };
}

