/* tslint:disable */
/* eslint-disable */
/**
 * apollo-rest-api
 * The Apollo API provides programmatic access to [Apollo](https://www.apollo.io/), the all-in-one sales intelligence and engagement platform. Use it to enrich people and company data (individually or in bulk), search Apollo\'s database of over 230 million contacts and 30 million companies, and manage accounts, contacts, deals, sequences, tasks, calls, and conversations in your go-to-market workflows.  ## Base URL  All API requests are made to `https://api.apollo.io/api/v1`.  ## Authentication  - **Apollo users** authenticate with an API key passed in the `x-api-key` request header. See [Create API Keys](https://docs.apollo.io/docs/create-api-key). - **Apollo partners** building integrations on behalf of mutual users authenticate with the [OAuth 2.0 authorization flow](https://docs.apollo.io/docs/use-oauth-20-authorization-flow-to-access-apollo-user-information-partners).  ## Rate limits & credits  Rate limits and credit consumption depend on your [Apollo pricing plan](https://docs.apollo.io/docs/api-pricing). Check your current limits and usage with the [View API Usage Stats and Rate Limits](https://docs.apollo.io/reference/view-api-usage-stats) endpoint. For more details, see [Rate Limits](https://docs.apollo.io/reference/rate-limits) and the [API FAQs](https://docs.apollo.io/docs/apollo-api-faqs).  New to the API? Start with the [Apollo API Overview](https://docs.apollo.io/docs/apollo-api-overview).
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateAListRequest
 */
export interface UpdateAListRequest {
    /**
     * The new name for the list. Must be unique for the list's modality within your team.<br><br>Example: `Conference 2024 - Maui (West)`
     * @type {string}
     * @memberof UpdateAListRequest
     */
    name: string;
    /**
     * Set to `true` to mark an account list as a Book of Business (BoB) list. Only applies to account lists.
     * @type {boolean}
     * @memberof UpdateAListRequest
     */
    bookOfBusiness?: boolean;
}

/**
 * Check if a given object implements the UpdateAListRequest interface.
 */
export function instanceOfUpdateAListRequest(value: object): value is UpdateAListRequest {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function UpdateAListRequestFromJSON(json: any): UpdateAListRequest {
    return UpdateAListRequestFromJSONTyped(json, false);
}

export function UpdateAListRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateAListRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'bookOfBusiness': json['book_of_business'] == null ? undefined : json['book_of_business'],
    };
}

export function UpdateAListRequestToJSON(json: any): UpdateAListRequest {
    return UpdateAListRequestToJSONTyped(json, false);
}

export function UpdateAListRequestToJSONTyped(value?: UpdateAListRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'book_of_business': value['bookOfBusiness'],
    };
}

