/* tslint:disable */
/* eslint-disable */
/**
 * apollo-rest-api
 * The Apollo API provides programmatic access to [Apollo](https://www.apollo.io/), the all-in-one sales intelligence and engagement platform. Use it to enrich people and company data (individually or in bulk), search Apollo\'s database of over 230 million contacts and 30 million companies, and manage accounts, contacts, deals, sequences, tasks, calls, and conversations in your go-to-market workflows.  ## Base URL  All API requests are made to `https://api.apollo.io/api/v1`.  ## Authentication  - **Apollo users** authenticate with an API key passed in the `x-api-key` request header. See [Create API Keys](https://docs.apollo.io/docs/create-api-key). - **Apollo partners** building integrations on behalf of mutual users authenticate with the [OAuth 2.0 authorization flow](https://docs.apollo.io/docs/use-oauth-20-authorization-flow-to-access-apollo-user-information-partners).  ## Rate limits & credits  Rate limits and credit consumption depend on your [Apollo pricing plan](https://docs.apollo.io/docs/api-pricing). Check your current limits and usage with the [View API Usage Stats and Rate Limits](https://docs.apollo.io/reference/view-api-usage-stats) endpoint. For more details, see [Rate Limits](https://docs.apollo.io/reference/rate-limits) and the [API FAQs](https://docs.apollo.io/docs/apollo-api-faqs).  New to the API? Start with the [Apollo API Overview](https://docs.apollo.io/docs/apollo-api-overview).
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { CheckAccountID } from './CheckAccountID';
import {
    instanceOfCheckAccountID,
    CheckAccountIDFromJSON,
    CheckAccountIDFromJSONTyped,
    CheckAccountIDToJSON,
} from './CheckAccountID';
import type { CheckAccountStageID } from './CheckAccountStageID';
import {
    instanceOfCheckAccountStageID,
    CheckAccountStageIDFromJSON,
    CheckAccountStageIDFromJSONTyped,
    CheckAccountStageIDToJSON,
} from './CheckAccountStageID';
import type { CheckOwnerID } from './CheckOwnerID';
import {
    instanceOfCheckOwnerID,
    CheckOwnerIDFromJSON,
    CheckOwnerIDFromJSONTyped,
    CheckOwnerIDToJSON,
} from './CheckOwnerID';

/**
 * @type UpdateAnAccount422Response
 * 
 * @export
 */
export type UpdateAnAccount422Response = CheckAccountID | CheckAccountStageID | CheckOwnerID;

export function UpdateAnAccount422ResponseFromJSON(json: any): UpdateAnAccount422Response {
    return UpdateAnAccount422ResponseFromJSONTyped(json, false);
}

export function UpdateAnAccount422ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateAnAccount422Response {
    if (json == null) {
        return json;
    }
    if (typeof json !== 'object') {
        return json;
    }
    if (instanceOfCheckAccountID(json)) {
        return CheckAccountIDFromJSONTyped(json, true);
    }
    if (instanceOfCheckAccountStageID(json)) {
        return CheckAccountStageIDFromJSONTyped(json, true);
    }
    if (instanceOfCheckOwnerID(json)) {
        return CheckOwnerIDFromJSONTyped(json, true);
    }
    return {} as any;
}

export function UpdateAnAccount422ResponseToJSON(json: any): any {
    return UpdateAnAccount422ResponseToJSONTyped(json, false);
}

export function UpdateAnAccount422ResponseToJSONTyped(value?: UpdateAnAccount422Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    if (typeof value !== 'object') {
        return value;
    }
    if (instanceOfCheckAccountID(value)) {
        return CheckAccountIDToJSON(value as CheckAccountID);
    }
    if (instanceOfCheckAccountStageID(value)) {
        return CheckAccountStageIDToJSON(value as CheckAccountStageID);
    }
    if (instanceOfCheckOwnerID(value)) {
        return CheckOwnerIDToJSON(value as CheckOwnerID);
    }
    return {};
}

