/* tslint:disable */
/* eslint-disable */
/**
 * apollo-rest-api
 * The Apollo API provides programmatic access to [Apollo](https://www.apollo.io/), the all-in-one sales intelligence and engagement platform. Use it to enrich people and company data (individually or in bulk), search Apollo\'s database of over 230 million contacts and 30 million companies, and manage accounts, contacts, deals, sequences, tasks, calls, and conversations in your go-to-market workflows.  ## Base URL  All API requests are made to `https://api.apollo.io/api/v1`.  ## Authentication  - **Apollo users** authenticate with an API key passed in the `x-api-key` request header. See [Create API Keys](https://docs.apollo.io/docs/create-api-key). - **Apollo partners** building integrations on behalf of mutual users authenticate with the [OAuth 2.0 authorization flow](https://docs.apollo.io/docs/use-oauth-20-authorization-flow-to-access-apollo-user-information-partners).  ## Rate limits & credits  Rate limits and credit consumption depend on your [Apollo pricing plan](https://docs.apollo.io/docs/api-pricing). Check your current limits and usage with the [View API Usage Stats and Rate Limits](https://docs.apollo.io/reference/view-api-usage-stats) endpoint. For more details, see [Rate Limits](https://docs.apollo.io/reference/rate-limits) and the [API FAQs](https://docs.apollo.io/docs/apollo-api-faqs).  New to the API? Start with the [Apollo API Overview](https://docs.apollo.io/docs/apollo-api-overview).
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UpdateContactStatusSequence200ResponseEntityProgressJobParams } from './UpdateContactStatusSequence200ResponseEntityProgressJobParams';
import {
    UpdateContactStatusSequence200ResponseEntityProgressJobParamsFromJSON,
    UpdateContactStatusSequence200ResponseEntityProgressJobParamsFromJSONTyped,
    UpdateContactStatusSequence200ResponseEntityProgressJobParamsToJSON,
    UpdateContactStatusSequence200ResponseEntityProgressJobParamsToJSONTyped,
} from './UpdateContactStatusSequence200ResponseEntityProgressJobParams';

/**
 * 
 * @export
 * @interface UpdateContactStatusSequence200ResponseEntityProgressJob
 */
export interface UpdateContactStatusSequence200ResponseEntityProgressJob {
    /**
     * 
     * @type {string}
     * @memberof UpdateContactStatusSequence200ResponseEntityProgressJob
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateContactStatusSequence200ResponseEntityProgressJob
     */
    userId?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateContactStatusSequence200ResponseEntityProgressJob
     */
    jobType?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof UpdateContactStatusSequence200ResponseEntityProgressJob
     */
    entityIds?: Array<string>;
    /**
     * 
     * @type {UpdateContactStatusSequence200ResponseEntityProgressJobParams}
     * @memberof UpdateContactStatusSequence200ResponseEntityProgressJob
     */
    params?: UpdateContactStatusSequence200ResponseEntityProgressJobParams;
    /**
     * 
     * @type {number}
     * @memberof UpdateContactStatusSequence200ResponseEntityProgressJob
     */
    progress?: number;
    /**
     * 
     * @type {number}
     * @memberof UpdateContactStatusSequence200ResponseEntityProgressJob
     */
    batchSize?: number;
}

/**
 * Check if a given object implements the UpdateContactStatusSequence200ResponseEntityProgressJob interface.
 */
export function instanceOfUpdateContactStatusSequence200ResponseEntityProgressJob(value: object): value is UpdateContactStatusSequence200ResponseEntityProgressJob {
    return true;
}

export function UpdateContactStatusSequence200ResponseEntityProgressJobFromJSON(json: any): UpdateContactStatusSequence200ResponseEntityProgressJob {
    return UpdateContactStatusSequence200ResponseEntityProgressJobFromJSONTyped(json, false);
}

export function UpdateContactStatusSequence200ResponseEntityProgressJobFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateContactStatusSequence200ResponseEntityProgressJob {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'userId': json['user_id'] == null ? undefined : json['user_id'],
        'jobType': json['job_type'] == null ? undefined : json['job_type'],
        'entityIds': json['entity_ids'] == null ? undefined : json['entity_ids'],
        'params': json['params'] == null ? undefined : UpdateContactStatusSequence200ResponseEntityProgressJobParamsFromJSON(json['params']),
        'progress': json['progress'] == null ? undefined : json['progress'],
        'batchSize': json['batch_size'] == null ? undefined : json['batch_size'],
    };
}

export function UpdateContactStatusSequence200ResponseEntityProgressJobToJSON(json: any): UpdateContactStatusSequence200ResponseEntityProgressJob {
    return UpdateContactStatusSequence200ResponseEntityProgressJobToJSONTyped(json, false);
}

export function UpdateContactStatusSequence200ResponseEntityProgressJobToJSONTyped(value?: UpdateContactStatusSequence200ResponseEntityProgressJob | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'user_id': value['userId'],
        'job_type': value['jobType'],
        'entity_ids': value['entityIds'],
        'params': UpdateContactStatusSequence200ResponseEntityProgressJobParamsToJSON(value['params']),
        'progress': value['progress'],
        'batch_size': value['batchSize'],
    };
}

