/* tslint:disable */
/* eslint-disable */
/**
 * apollo-rest-api
 * The Apollo API provides programmatic access to [Apollo](https://www.apollo.io/), the all-in-one sales intelligence and engagement platform. Use it to enrich people and company data (individually or in bulk), search Apollo\'s database of over 230 million contacts and 30 million companies, and manage accounts, contacts, deals, sequences, tasks, calls, and conversations in your go-to-market workflows.  ## Base URL  All API requests are made to `https://api.apollo.io/api/v1`.  ## Authentication  - **Apollo users** authenticate with an API key passed in the `x-api-key` request header. See [Create API Keys](https://docs.apollo.io/docs/create-api-key). - **Apollo partners** building integrations on behalf of mutual users authenticate with the [OAuth 2.0 authorization flow](https://docs.apollo.io/docs/use-oauth-20-authorization-flow-to-access-apollo-user-information-partners).  ## Rate limits & credits  Rate limits and credit consumption depend on your [Apollo pricing plan](https://docs.apollo.io/docs/api-pricing). Check your current limits and usage with the [View API Usage Stats and Rate Limits](https://docs.apollo.io/reference/view-api-usage-stats) endpoint. For more details, see [Rate Limits](https://docs.apollo.io/reference/rate-limits) and the [API FAQs](https://docs.apollo.io/docs/apollo-api-faqs).  New to the API? Start with the [Apollo API Overview](https://docs.apollo.io/docs/apollo-api-overview).
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ViewAssociatedDeals200ResponseOpportunitiesInnerOpportunityContactRolesInnerContact
 */
export interface ViewAssociatedDeals200ResponseOpportunitiesInnerOpportunityContactRolesInnerContact {
    /**
     * 
     * @type {string}
     * @memberof ViewAssociatedDeals200ResponseOpportunitiesInnerOpportunityContactRolesInnerContact
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof ViewAssociatedDeals200ResponseOpportunitiesInnerOpportunityContactRolesInnerContact
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof ViewAssociatedDeals200ResponseOpportunitiesInnerOpportunityContactRolesInnerContact
     */
    firstName?: string;
    /**
     * 
     * @type {string}
     * @memberof ViewAssociatedDeals200ResponseOpportunitiesInnerOpportunityContactRolesInnerContact
     */
    lastName?: string;
}

/**
 * Check if a given object implements the ViewAssociatedDeals200ResponseOpportunitiesInnerOpportunityContactRolesInnerContact interface.
 */
export function instanceOfViewAssociatedDeals200ResponseOpportunitiesInnerOpportunityContactRolesInnerContact(value: object): value is ViewAssociatedDeals200ResponseOpportunitiesInnerOpportunityContactRolesInnerContact {
    return true;
}

export function ViewAssociatedDeals200ResponseOpportunitiesInnerOpportunityContactRolesInnerContactFromJSON(json: any): ViewAssociatedDeals200ResponseOpportunitiesInnerOpportunityContactRolesInnerContact {
    return ViewAssociatedDeals200ResponseOpportunitiesInnerOpportunityContactRolesInnerContactFromJSONTyped(json, false);
}

export function ViewAssociatedDeals200ResponseOpportunitiesInnerOpportunityContactRolesInnerContactFromJSONTyped(json: any, ignoreDiscriminator: boolean): ViewAssociatedDeals200ResponseOpportunitiesInnerOpportunityContactRolesInnerContact {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'firstName': json['first_name'] == null ? undefined : json['first_name'],
        'lastName': json['last_name'] == null ? undefined : json['last_name'],
    };
}

export function ViewAssociatedDeals200ResponseOpportunitiesInnerOpportunityContactRolesInnerContactToJSON(json: any): ViewAssociatedDeals200ResponseOpportunitiesInnerOpportunityContactRolesInnerContact {
    return ViewAssociatedDeals200ResponseOpportunitiesInnerOpportunityContactRolesInnerContactToJSONTyped(json, false);
}

export function ViewAssociatedDeals200ResponseOpportunitiesInnerOpportunityContactRolesInnerContactToJSONTyped(value?: ViewAssociatedDeals200ResponseOpportunitiesInnerOpportunityContactRolesInnerContact | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'first_name': value['firstName'],
        'last_name': value['lastName'],
    };
}

