/* tslint:disable */
/* eslint-disable */
/**
 * apollo-rest-api
 * The Apollo API provides programmatic access to [Apollo](https://www.apollo.io/), the all-in-one sales intelligence and engagement platform. Use it to enrich people and company data (individually or in bulk), search Apollo\'s database of over 230 million contacts and 30 million companies, and manage accounts, contacts, deals, sequences, tasks, calls, and conversations in your go-to-market workflows.  ## Base URL  All API requests are made to `https://api.apollo.io/api/v1`.  ## Authentication  - **Apollo users** authenticate with an API key passed in the `x-api-key` request header. See [Create API Keys](https://docs.apollo.io/docs/create-api-key). - **Apollo partners** building integrations on behalf of mutual users authenticate with the [OAuth 2.0 authorization flow](https://docs.apollo.io/docs/use-oauth-20-authorization-flow-to-access-apollo-user-information-partners).  ## Rate limits & credits  Rate limits and credit consumption depend on your [Apollo pricing plan](https://docs.apollo.io/docs/api-pricing). Check your current limits and usage with the [View API Usage Stats and Rate Limits](https://docs.apollo.io/reference/view-api-usage-stats) endpoint. For more details, see [Rate Limits](https://docs.apollo.io/reference/rate-limits) and the [API FAQs](https://docs.apollo.io/docs/apollo-api-faqs).  New to the API? Start with the [Apollo API Overview](https://docs.apollo.io/docs/apollo-api-overview).
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type BulkCreateContacts200Response,
    BulkCreateContacts200ResponseFromJSON,
    BulkCreateContacts200ResponseToJSON,
} from '../models/BulkCreateContacts200Response';
import {
    type BulkCreateContactsRequest,
    BulkCreateContactsRequestFromJSON,
    BulkCreateContactsRequestToJSON,
} from '../models/BulkCreateContactsRequest';
import {
    type BulkUpdateContacts200Response,
    BulkUpdateContacts200ResponseFromJSON,
    BulkUpdateContacts200ResponseToJSON,
} from '../models/BulkUpdateContacts200Response';
import {
    type BulkUpdateContacts422Response,
    BulkUpdateContacts422ResponseFromJSON,
    BulkUpdateContacts422ResponseToJSON,
} from '../models/BulkUpdateContacts422Response';
import {
    type BulkUpdateContactsRequest,
    BulkUpdateContactsRequestFromJSON,
    BulkUpdateContactsRequestToJSON,
} from '../models/BulkUpdateContactsRequest';
import {
    type CreateAContact200Response,
    CreateAContact200ResponseFromJSON,
    CreateAContact200ResponseToJSON,
} from '../models/CreateAContact200Response';
import {
    type CreateAContact422Response,
    CreateAContact422ResponseFromJSON,
    CreateAContact422ResponseToJSON,
} from '../models/CreateAContact422Response';
import {
    type CreateAContactRequest,
    CreateAContactRequestFromJSON,
    CreateAContactRequestToJSON,
} from '../models/CreateAContactRequest';
import {
    type OrganizationEnrichment422Response,
    OrganizationEnrichment422ResponseFromJSON,
    OrganizationEnrichment422ResponseToJSON,
} from '../models/OrganizationEnrichment422Response';
import {
    type PeopleApiSearch403Response,
    PeopleApiSearch403ResponseFromJSON,
    PeopleApiSearch403ResponseToJSON,
} from '../models/PeopleApiSearch403Response';
import {
    type PeopleEnrichment429Response,
    PeopleEnrichment429ResponseFromJSON,
    PeopleEnrichment429ResponseToJSON,
} from '../models/PeopleEnrichment429Response';
import {
    type SearchForContacts200Response,
    SearchForContacts200ResponseFromJSON,
    SearchForContacts200ResponseToJSON,
} from '../models/SearchForContacts200Response';
import {
    type SearchForContactsRequest,
    SearchForContactsRequestFromJSON,
    SearchForContactsRequestToJSON,
} from '../models/SearchForContactsRequest';
import {
    type UpdateAContact200Response,
    UpdateAContact200ResponseFromJSON,
    UpdateAContact200ResponseToJSON,
} from '../models/UpdateAContact200Response';
import {
    type UpdateAContact422Response,
    UpdateAContact422ResponseFromJSON,
    UpdateAContact422ResponseToJSON,
} from '../models/UpdateAContact422Response';
import {
    type UpdateAContactRequest,
    UpdateAContactRequestFromJSON,
    UpdateAContactRequestToJSON,
} from '../models/UpdateAContactRequest';
import {
    type UpdateContactOwnership200Response,
    UpdateContactOwnership200ResponseFromJSON,
    UpdateContactOwnership200ResponseToJSON,
} from '../models/UpdateContactOwnership200Response';
import {
    type UpdateContactStage200Response,
    UpdateContactStage200ResponseFromJSON,
    UpdateContactStage200ResponseToJSON,
} from '../models/UpdateContactStage200Response';
import {
    type ViewAContact200Response,
    ViewAContact200ResponseFromJSON,
    ViewAContact200ResponseToJSON,
} from '../models/ViewAContact200Response';
import {
    type ViewAssociatedDeals200Response,
    ViewAssociatedDeals200ResponseFromJSON,
    ViewAssociatedDeals200ResponseToJSON,
} from '../models/ViewAssociatedDeals200Response';

export interface BulkCreateContactsOperationRequest {
    bulkCreateContactsRequest: BulkCreateContactsRequest;
}

export interface BulkUpdateContactsOperationRequest {
    bulkUpdateContactsRequest: BulkUpdateContactsRequest | null;
}

export interface CreateAContactOperationRequest {
    createAContactRequest: CreateAContactRequest;
}

export interface SearchForContactsOperationRequest {
    searchForContactsRequest: SearchForContactsRequest;
}

export interface UpdateAContactOperationRequest {
    contactId: string;
    updateAContactRequest: UpdateAContactRequest;
}

export interface UpdateContactOwnershipRequest {
    contactIds: Array<string>;
    ownerId: string;
}

export interface UpdateContactStageRequest {
    contactIds: Array<string>;
    contactStageId: string;
}

export interface ViewAContactRequest {
    contactId: string;
}

export interface ViewAssociatedDealsRequest {
    contactId: string;
    body?: object;
}

/**
 * 
 */
export class ContactsApi extends runtime.BaseAPI {

    /**
     * Creates request options for bulkCreateContacts without sending the request
     */
    async bulkCreateContactsRequestOpts(requestParameters: BulkCreateContactsOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['bulkCreateContactsRequest'] == null) {
            throw new runtime.RequiredError(
                'bulkCreateContactsRequest',
                'Required parameter "bulkCreateContactsRequest" was null or undefined when calling bulkCreateContacts().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // apiKey authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/contacts/bulk_create`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: BulkCreateContactsRequestToJSON(requestParameters['bulkCreateContactsRequest']),
        };
    }

    /**
     * This endpoint doesn\'t consume Apollo credits. Learn more about [API pricing and credits](https://docs.apollo.io/docs/api-pricing).  <a href=\"https://knowledge.apollo.io/hc/en-us/articles/5995459280525-View-and-Edit-Contacts\" target=\"_blank\">Contacts</a> are people saved in Apollo.<br><br>Use the Bulk Create Contacts endpoint to create up to 100 contacts in a single API request. This endpoint supports intelligent deduplication and returns separated arrays for newly created and existing contacts. <br><br>Important: This endpoint creates new contacts but doesn\'t update existing ones (except for placeholder contacts from email imports). Existing contacts that match the criteria are returned in the <code>existing_contacts</code> array without modification.<br><br>To update existing contacts, use the <a href=\"https://docs.apollo.io/reference/bulk-update-contacts\">Bulk Update Contacts endpoint</a>.
     * Bulk Create Contacts
     */
    async bulkCreateContactsRaw(requestParameters: BulkCreateContactsOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BulkCreateContacts200Response>> {
        const requestOptions = await this.bulkCreateContactsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BulkCreateContacts200ResponseFromJSON(jsonValue));
    }

    /**
     * This endpoint doesn\'t consume Apollo credits. Learn more about [API pricing and credits](https://docs.apollo.io/docs/api-pricing).  <a href=\"https://knowledge.apollo.io/hc/en-us/articles/5995459280525-View-and-Edit-Contacts\" target=\"_blank\">Contacts</a> are people saved in Apollo.<br><br>Use the Bulk Create Contacts endpoint to create up to 100 contacts in a single API request. This endpoint supports intelligent deduplication and returns separated arrays for newly created and existing contacts. <br><br>Important: This endpoint creates new contacts but doesn\'t update existing ones (except for placeholder contacts from email imports). Existing contacts that match the criteria are returned in the <code>existing_contacts</code> array without modification.<br><br>To update existing contacts, use the <a href=\"https://docs.apollo.io/reference/bulk-update-contacts\">Bulk Update Contacts endpoint</a>.
     * Bulk Create Contacts
     */
    async bulkCreateContacts(requestParameters: BulkCreateContactsOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BulkCreateContacts200Response> {
        const response = await this.bulkCreateContactsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for bulkUpdateContacts without sending the request
     */
    async bulkUpdateContactsRequestOpts(requestParameters: BulkUpdateContactsOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['bulkUpdateContactsRequest'] == null) {
            throw new runtime.RequiredError(
                'bulkUpdateContactsRequest',
                'Required parameter "bulkUpdateContactsRequest" was null or undefined when calling bulkUpdateContacts().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // apiKey authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/contacts/bulk_update`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: BulkUpdateContactsRequestToJSON(requestParameters['bulkUpdateContactsRequest']),
        };
    }

    /**
     * This endpoint doesn\'t consume Apollo credits. Learn more about [API pricing and credits](https://docs.apollo.io/docs/api-pricing).  <a href=\"https://knowledge.apollo.io/hc/en-us/articles/5995459280525-View-and-Edit-Contacts\" target=\"_blank\">Contacts</a> are people saved in Apollo.<br><br>Use the Bulk Update Contacts endpoint to update multiple contacts in your team\'s Apollo account simultaneously. <br><br>This endpoint allows you to update common fields across multiple contacts efficiently, such as contact stages, owners, custom fields, and other contact attributes. <br><br>You can update up to 1000 contacts per request; requests with more than 1000 contacts are rejected with a <code>422</code> error. Requests of 100 or fewer contacts are processed synchronously and return the updated contacts immediately. Requests of 101 to 1000 contacts are processed asynchronously. You can also force asynchronous processing at any batch size by setting the <code>async</code> parameter to <code>true</code>.
     * Bulk Update Contacts
     */
    async bulkUpdateContactsRaw(requestParameters: BulkUpdateContactsOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BulkUpdateContacts200Response>> {
        const requestOptions = await this.bulkUpdateContactsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BulkUpdateContacts200ResponseFromJSON(jsonValue));
    }

    /**
     * This endpoint doesn\'t consume Apollo credits. Learn more about [API pricing and credits](https://docs.apollo.io/docs/api-pricing).  <a href=\"https://knowledge.apollo.io/hc/en-us/articles/5995459280525-View-and-Edit-Contacts\" target=\"_blank\">Contacts</a> are people saved in Apollo.<br><br>Use the Bulk Update Contacts endpoint to update multiple contacts in your team\'s Apollo account simultaneously. <br><br>This endpoint allows you to update common fields across multiple contacts efficiently, such as contact stages, owners, custom fields, and other contact attributes. <br><br>You can update up to 1000 contacts per request; requests with more than 1000 contacts are rejected with a <code>422</code> error. Requests of 100 or fewer contacts are processed synchronously and return the updated contacts immediately. Requests of 101 to 1000 contacts are processed asynchronously. You can also force asynchronous processing at any batch size by setting the <code>async</code> parameter to <code>true</code>.
     * Bulk Update Contacts
     */
    async bulkUpdateContacts(requestParameters: BulkUpdateContactsOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BulkUpdateContacts200Response> {
        const response = await this.bulkUpdateContactsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for createAContact without sending the request
     */
    async createAContactRequestOpts(requestParameters: CreateAContactOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['createAContactRequest'] == null) {
            throw new runtime.RequiredError(
                'createAContactRequest',
                'Required parameter "createAContactRequest" was null or undefined when calling createAContact().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // apiKey authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/contacts`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateAContactRequestToJSON(requestParameters['createAContactRequest']),
        };
    }

    /**
     * This endpoint doesn\'t consume Apollo credits. Learn more about [API pricing and credits](https://docs.apollo.io/docs/api-pricing).  <a href=\"https://knowledge.apollo.io/hc/en-us/articles/5995459280525-View-and-Edit-Contacts\" target=\"_blank\">Contacts</a> are people saved in Apollo.<br><br>Use the Create a Contact endpoint to add a new contact to your team\'s Apollo  account.<br><br>By default, Apollo doesn\'t apply deduplication processes when you create a new contact via API. If your entry has the same name, email address, or other details as an existing contact, Apollo creates a new contact instead of updating the existing contact. To enable deduplication and prevent duplicate contacts, set the <code>run_dedupe</code> parameter to <code>true</code>. <br><br>To update an existing contact, use the <a href=\"https://docs.apollo.io/reference/update-a-contact\">Update a Contact endpoint</a> instead.
     * Create a Contact
     */
    async createAContactRaw(requestParameters: CreateAContactOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CreateAContact200Response>> {
        const requestOptions = await this.createAContactRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CreateAContact200ResponseFromJSON(jsonValue));
    }

    /**
     * This endpoint doesn\'t consume Apollo credits. Learn more about [API pricing and credits](https://docs.apollo.io/docs/api-pricing).  <a href=\"https://knowledge.apollo.io/hc/en-us/articles/5995459280525-View-and-Edit-Contacts\" target=\"_blank\">Contacts</a> are people saved in Apollo.<br><br>Use the Create a Contact endpoint to add a new contact to your team\'s Apollo  account.<br><br>By default, Apollo doesn\'t apply deduplication processes when you create a new contact via API. If your entry has the same name, email address, or other details as an existing contact, Apollo creates a new contact instead of updating the existing contact. To enable deduplication and prevent duplicate contacts, set the <code>run_dedupe</code> parameter to <code>true</code>. <br><br>To update an existing contact, use the <a href=\"https://docs.apollo.io/reference/update-a-contact\">Update a Contact endpoint</a> instead.
     * Create a Contact
     */
    async createAContact(requestParameters: CreateAContactOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CreateAContact200Response> {
        const response = await this.createAContactRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listContactStages without sending the request
     */
    async listContactStagesRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // apiKey authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/contact_stages`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * This endpoint doesn\'t consume Apollo credits. Learn more about [API pricing and credits](https://docs.apollo.io/docs/api-pricing).  <a href=\"https://knowledge.apollo.io/hc/en-us/articles/4410623601165-Contact-and-Account-Stages-Overview\" target=\"_blank\">Contact stages</a> help you track progress on sales and marketing pipelines.<br><br>Use the List Contact Stages endpoint to retrieve the IDs for the available contact stages in your team\'s Apollo account. <br><br>Contact stage IDs can be used to <a href=\"https://docs.apollo.io/reference/update-a-contact\">update individual contacts</a> and <a href=\"https://docs.apollo.io/reference/update-contact-stage\">update the contact stages for multiple contacts</a> via Apollo API.
     * List Contact Stages
     */
    async listContactStagesRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.listContactStagesRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * This endpoint doesn\'t consume Apollo credits. Learn more about [API pricing and credits](https://docs.apollo.io/docs/api-pricing).  <a href=\"https://knowledge.apollo.io/hc/en-us/articles/4410623601165-Contact-and-Account-Stages-Overview\" target=\"_blank\">Contact stages</a> help you track progress on sales and marketing pipelines.<br><br>Use the List Contact Stages endpoint to retrieve the IDs for the available contact stages in your team\'s Apollo account. <br><br>Contact stage IDs can be used to <a href=\"https://docs.apollo.io/reference/update-a-contact\">update individual contacts</a> and <a href=\"https://docs.apollo.io/reference/update-contact-stage\">update the contact stages for multiple contacts</a> via Apollo API.
     * List Contact Stages
     */
    async listContactStages(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.listContactStagesRaw(initOverrides);
    }

    /**
     * Creates request options for searchForContacts without sending the request
     */
    async searchForContactsRequestOpts(requestParameters: SearchForContactsOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['searchForContactsRequest'] == null) {
            throw new runtime.RequiredError(
                'searchForContactsRequest',
                'Required parameter "searchForContactsRequest" was null or undefined when calling searchForContacts().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // apiKey authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/contacts/search`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SearchForContactsRequestToJSON(requestParameters['searchForContactsRequest']),
        };
    }

    /**
     * This endpoint doesn\'t consume Apollo credits. Learn more about [API pricing and credits](https://docs.apollo.io/docs/api-pricing).  <a href=\"https://knowledge.apollo.io/hc/en-us/articles/5995459280525-View-and-Edit-Contacts\" target=\"_blank\">Contacts</a> are people saved in Apollo.<br><br>Use the Search for Contacts endpoint to search for the contacts that have been added to your team\'s Apollo account.<br><br>This endpoint only returns contacts in the search results. To search for people in the Apollo database, call the <a href=\"https://docs.apollo.io/reference/people-api-search\">People API Search endpoint</a>.<br><br>To protect Apollo\'s performance for all users, this endpoint has a display limit of 50,000 records (100 records per page, up to 500 pages). Add more filters to narrow your search results as much as possible.
     * Search for Contacts
     */
    async searchForContactsRaw(requestParameters: SearchForContactsOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SearchForContacts200Response>> {
        const requestOptions = await this.searchForContactsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SearchForContacts200ResponseFromJSON(jsonValue));
    }

    /**
     * This endpoint doesn\'t consume Apollo credits. Learn more about [API pricing and credits](https://docs.apollo.io/docs/api-pricing).  <a href=\"https://knowledge.apollo.io/hc/en-us/articles/5995459280525-View-and-Edit-Contacts\" target=\"_blank\">Contacts</a> are people saved in Apollo.<br><br>Use the Search for Contacts endpoint to search for the contacts that have been added to your team\'s Apollo account.<br><br>This endpoint only returns contacts in the search results. To search for people in the Apollo database, call the <a href=\"https://docs.apollo.io/reference/people-api-search\">People API Search endpoint</a>.<br><br>To protect Apollo\'s performance for all users, this endpoint has a display limit of 50,000 records (100 records per page, up to 500 pages). Add more filters to narrow your search results as much as possible.
     * Search for Contacts
     */
    async searchForContacts(requestParameters: SearchForContactsOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SearchForContacts200Response> {
        const response = await this.searchForContactsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for updateAContact without sending the request
     */
    async updateAContactRequestOpts(requestParameters: UpdateAContactOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['contactId'] == null) {
            throw new runtime.RequiredError(
                'contactId',
                'Required parameter "contactId" was null or undefined when calling updateAContact().'
            );
        }

        if (requestParameters['updateAContactRequest'] == null) {
            throw new runtime.RequiredError(
                'updateAContactRequest',
                'Required parameter "updateAContactRequest" was null or undefined when calling updateAContact().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // apiKey authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/contacts/{contact_id}`;
        urlPath = urlPath.replace('{contact_id}', encodeURIComponent(String(requestParameters['contactId'])));

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateAContactRequestToJSON(requestParameters['updateAContactRequest']),
        };
    }

    /**
     * This endpoint doesn\'t consume Apollo credits. Learn more about [API pricing and credits](https://docs.apollo.io/docs/api-pricing).  <a href=\"https://knowledge.apollo.io/hc/en-us/articles/5995459280525-View-and-Edit-Contacts\" target=\"_blank\">Contacts</a> are people saved in Apollo.<br><br>Use the Update a Contact endpoint to update existing contacts in your team\'s Apollo account.<br><br>To create a new contact, use the <a href=\"https://docs.apollo.io/reference/create-a-contact\">Create a Contact endpoint</a> instead. To update the contact stage for multiple contacts, use the <a href=\"https://docs.apollo.io/reference/update-contact-stage\">Update Contact Stage for Multiple Contacts</a> endpoint.
     * Update a Contact
     */
    async updateAContactRaw(requestParameters: UpdateAContactOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UpdateAContact200Response>> {
        const requestOptions = await this.updateAContactRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UpdateAContact200ResponseFromJSON(jsonValue));
    }

    /**
     * This endpoint doesn\'t consume Apollo credits. Learn more about [API pricing and credits](https://docs.apollo.io/docs/api-pricing).  <a href=\"https://knowledge.apollo.io/hc/en-us/articles/5995459280525-View-and-Edit-Contacts\" target=\"_blank\">Contacts</a> are people saved in Apollo.<br><br>Use the Update a Contact endpoint to update existing contacts in your team\'s Apollo account.<br><br>To create a new contact, use the <a href=\"https://docs.apollo.io/reference/create-a-contact\">Create a Contact endpoint</a> instead. To update the contact stage for multiple contacts, use the <a href=\"https://docs.apollo.io/reference/update-contact-stage\">Update Contact Stage for Multiple Contacts</a> endpoint.
     * Update a Contact
     */
    async updateAContact(requestParameters: UpdateAContactOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UpdateAContact200Response> {
        const response = await this.updateAContactRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for updateContactOwnership without sending the request
     */
    async updateContactOwnershipRequestOpts(requestParameters: UpdateContactOwnershipRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['contactIds'] == null) {
            throw new runtime.RequiredError(
                'contactIds',
                'Required parameter "contactIds" was null or undefined when calling updateContactOwnership().'
            );
        }

        if (requestParameters['ownerId'] == null) {
            throw new runtime.RequiredError(
                'ownerId',
                'Required parameter "ownerId" was null or undefined when calling updateContactOwnership().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['contactIds'] != null) {
            queryParameters['contact_ids[]'] = requestParameters['contactIds'];
        }

        if (requestParameters['ownerId'] != null) {
            queryParameters['owner_id'] = requestParameters['ownerId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // apiKey authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/contacts/update_owners`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * This endpoint doesn\'t consume Apollo credits. Learn more about [API pricing and credits](https://docs.apollo.io/docs/api-pricing).  <a href=\"https://knowledge.apollo.io/hc/en-us/articles/5631686093069-Edit-a-Contact-or-Account-Owner\" target=\"_blank\">Contact owners</a> manage specific contacts in Apollo.<br><br>Use the Update Contact Owner for Multiple Contacts endpoint to assign multiple contacts to a different user in your team\'s Apollo account. <br><br>To update more than the contact\'s owner, such as job titles or contact details, use the <a href=\"https://docs.apollo.io/reference/update-a-contact\">Update a Contact endpoint</a> instead.
     * Update Contact Owner for Multiple Contacts
     */
    async updateContactOwnershipRaw(requestParameters: UpdateContactOwnershipRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UpdateContactOwnership200Response>> {
        const requestOptions = await this.updateContactOwnershipRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UpdateContactOwnership200ResponseFromJSON(jsonValue));
    }

    /**
     * This endpoint doesn\'t consume Apollo credits. Learn more about [API pricing and credits](https://docs.apollo.io/docs/api-pricing).  <a href=\"https://knowledge.apollo.io/hc/en-us/articles/5631686093069-Edit-a-Contact-or-Account-Owner\" target=\"_blank\">Contact owners</a> manage specific contacts in Apollo.<br><br>Use the Update Contact Owner for Multiple Contacts endpoint to assign multiple contacts to a different user in your team\'s Apollo account. <br><br>To update more than the contact\'s owner, such as job titles or contact details, use the <a href=\"https://docs.apollo.io/reference/update-a-contact\">Update a Contact endpoint</a> instead.
     * Update Contact Owner for Multiple Contacts
     */
    async updateContactOwnership(requestParameters: UpdateContactOwnershipRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UpdateContactOwnership200Response> {
        const response = await this.updateContactOwnershipRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for updateContactStage without sending the request
     */
    async updateContactStageRequestOpts(requestParameters: UpdateContactStageRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['contactIds'] == null) {
            throw new runtime.RequiredError(
                'contactIds',
                'Required parameter "contactIds" was null or undefined when calling updateContactStage().'
            );
        }

        if (requestParameters['contactStageId'] == null) {
            throw new runtime.RequiredError(
                'contactStageId',
                'Required parameter "contactStageId" was null or undefined when calling updateContactStage().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['contactIds'] != null) {
            queryParameters['contact_ids[]'] = requestParameters['contactIds'];
        }

        if (requestParameters['contactStageId'] != null) {
            queryParameters['contact_stage_id'] = requestParameters['contactStageId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // apiKey authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/contacts/update_stages`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * This endpoint doesn\'t consume Apollo credits. Learn more about [API pricing and credits](https://docs.apollo.io/docs/api-pricing).  <a href=\"https://knowledge.apollo.io/hc/en-us/articles/4410623601165-Contact-and-Account-Stages-Overview\" target=\"_blank\">Contact stages</a> help you track progress on sales and marketing pipelines.<br><br>Use the Update Contact Stage for Multiple Contacts endpoint to update the contact stage for several contacts in your team\'s Apollo account.<br><br>To update more than the contact stage, such as job titles or contact details, use the <a href=\"https://docs.apollo.io/reference/update-a-contact\">Update a Contact endpoint</a> instead.
     * Update Contact Stage for Multiple Contacts
     */
    async updateContactStageRaw(requestParameters: UpdateContactStageRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UpdateContactStage200Response>> {
        const requestOptions = await this.updateContactStageRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UpdateContactStage200ResponseFromJSON(jsonValue));
    }

    /**
     * This endpoint doesn\'t consume Apollo credits. Learn more about [API pricing and credits](https://docs.apollo.io/docs/api-pricing).  <a href=\"https://knowledge.apollo.io/hc/en-us/articles/4410623601165-Contact-and-Account-Stages-Overview\" target=\"_blank\">Contact stages</a> help you track progress on sales and marketing pipelines.<br><br>Use the Update Contact Stage for Multiple Contacts endpoint to update the contact stage for several contacts in your team\'s Apollo account.<br><br>To update more than the contact stage, such as job titles or contact details, use the <a href=\"https://docs.apollo.io/reference/update-a-contact\">Update a Contact endpoint</a> instead.
     * Update Contact Stage for Multiple Contacts
     */
    async updateContactStage(requestParameters: UpdateContactStageRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UpdateContactStage200Response> {
        const response = await this.updateContactStageRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for viewAContact without sending the request
     */
    async viewAContactRequestOpts(requestParameters: ViewAContactRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['contactId'] == null) {
            throw new runtime.RequiredError(
                'contactId',
                'Required parameter "contactId" was null or undefined when calling viewAContact().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // apiKey authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/contacts/{contact_id}`;
        urlPath = urlPath.replace('{contact_id}', encodeURIComponent(String(requestParameters['contactId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * This endpoint doesn\'t consume Apollo credits. Learn more about [API pricing and credits](https://docs.apollo.io/docs/api-pricing).  <a href=\"https://knowledge.apollo.io/hc/en-us/articles/5995459280525-View-and-Edit-Contacts\" target=\"_blank\">Contacts</a> are people saved in Apollo.<br><br>Use the View a Contact endpoint to retrieve details for an existing contact in your team\'s Apollo database.<br><br>This endpoint requires a master API key. If you call the endpoint without a master key, you receive a `403` response. Check out <a href=\"https://docs.apollo.io/docs/create-api-key\">Create an API Key</a> to learn how to create a master key.
     * View a Contact
     */
    async viewAContactRaw(requestParameters: ViewAContactRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ViewAContact200Response>> {
        const requestOptions = await this.viewAContactRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ViewAContact200ResponseFromJSON(jsonValue));
    }

    /**
     * This endpoint doesn\'t consume Apollo credits. Learn more about [API pricing and credits](https://docs.apollo.io/docs/api-pricing).  <a href=\"https://knowledge.apollo.io/hc/en-us/articles/5995459280525-View-and-Edit-Contacts\" target=\"_blank\">Contacts</a> are people saved in Apollo.<br><br>Use the View a Contact endpoint to retrieve details for an existing contact in your team\'s Apollo database.<br><br>This endpoint requires a master API key. If you call the endpoint without a master key, you receive a `403` response. Check out <a href=\"https://docs.apollo.io/docs/create-api-key\">Create an API Key</a> to learn how to create a master key.
     * View a Contact
     */
    async viewAContact(requestParameters: ViewAContactRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ViewAContact200Response> {
        const response = await this.viewAContactRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for viewAssociatedDeals without sending the request
     */
    async viewAssociatedDealsRequestOpts(requestParameters: ViewAssociatedDealsRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['contactId'] == null) {
            throw new runtime.RequiredError(
                'contactId',
                'Required parameter "contactId" was null or undefined when calling viewAssociatedDeals().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // apiKey authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/contacts/{contact_id}/opportunities`;
        urlPath = urlPath.replace('{contact_id}', encodeURIComponent(String(requestParameters['contactId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['body'] as any,
        };
    }

    /**
     * This endpoint doesn\'t consume Apollo credits. Learn more about [API pricing and credits](https://docs.apollo.io/docs/api-pricing).  <a href=\"https://knowledge.apollo.io/hc/en-us/articles/4415062467725-Deals-Overview\" target=\"_blank\">Deals</a> on Apollo help you track sales opportunities.<br><br>Use the View Associated Deals endpoint to retrieve the deals associated with a contact.<br><br>This endpoint doesn\'t require a request body. If you include one, Apollo doesn\'t read its fields. An empty JSON <code>{}</code> is sufficient.<br><br>Each result returns the same deal details as <a href=\"https://docs.apollo.io/reference/view-deal\">View Deal</a> endpoint. If the contact has no associated deals or the contact ID isn\'t recognized, Apollo returns a <code>200</code> response with an empty array rather than a <code>404</code> error.
     * View Associated Deals
     */
    async viewAssociatedDealsRaw(requestParameters: ViewAssociatedDealsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ViewAssociatedDeals200Response>> {
        const requestOptions = await this.viewAssociatedDealsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ViewAssociatedDeals200ResponseFromJSON(jsonValue));
    }

    /**
     * This endpoint doesn\'t consume Apollo credits. Learn more about [API pricing and credits](https://docs.apollo.io/docs/api-pricing).  <a href=\"https://knowledge.apollo.io/hc/en-us/articles/4415062467725-Deals-Overview\" target=\"_blank\">Deals</a> on Apollo help you track sales opportunities.<br><br>Use the View Associated Deals endpoint to retrieve the deals associated with a contact.<br><br>This endpoint doesn\'t require a request body. If you include one, Apollo doesn\'t read its fields. An empty JSON <code>{}</code> is sufficient.<br><br>Each result returns the same deal details as <a href=\"https://docs.apollo.io/reference/view-deal\">View Deal</a> endpoint. If the contact has no associated deals or the contact ID isn\'t recognized, Apollo returns a <code>200</code> response with an empty array rather than a <code>404</code> error.
     * View Associated Deals
     */
    async viewAssociatedDeals(requestParameters: ViewAssociatedDealsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ViewAssociatedDeals200Response> {
        const response = await this.viewAssociatedDealsRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
