/* tslint:disable */
/* eslint-disable */
/**
 * apollo-rest-api
 * The Apollo API provides programmatic access to [Apollo](https://www.apollo.io/), the all-in-one sales intelligence and engagement platform. Use it to enrich people and company data (individually or in bulk), search Apollo\'s database of over 230 million contacts and 30 million companies, and manage accounts, contacts, deals, sequences, tasks, calls, and conversations in your go-to-market workflows.  ## Base URL  All API requests are made to `https://api.apollo.io/api/v1`.  ## Authentication  - **Apollo users** authenticate with an API key passed in the `x-api-key` request header. See [Create API Keys](https://docs.apollo.io/docs/create-api-key). - **Apollo partners** building integrations on behalf of mutual users authenticate with the [OAuth 2.0 authorization flow](https://docs.apollo.io/docs/use-oauth-20-authorization-flow-to-access-apollo-user-information-partners).  ## Rate limits & credits  Rate limits and credit consumption depend on your [Apollo pricing plan](https://docs.apollo.io/docs/api-pricing). Check your current limits and usage with the [View API Usage Stats and Rate Limits](https://docs.apollo.io/reference/view-api-usage-stats) endpoint. For more details, see [Rate Limits](https://docs.apollo.io/reference/rate-limits) and the [API FAQs](https://docs.apollo.io/docs/apollo-api-faqs).  New to the API? Start with the [Apollo API Overview](https://docs.apollo.io/docs/apollo-api-overview).
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type CheckEmailSendStatus200Response,
    CheckEmailSendStatus200ResponseFromJSON,
    CheckEmailSendStatus200ResponseToJSON,
} from '../models/CheckEmailSendStatus200Response';
import {
    type CheckEmailSendStatusRequest,
    CheckEmailSendStatusRequestFromJSON,
    CheckEmailSendStatusRequestToJSON,
} from '../models/CheckEmailSendStatusRequest';
import {
    type CreateAnEmailDraft200Response,
    CreateAnEmailDraft200ResponseFromJSON,
    CreateAnEmailDraft200ResponseToJSON,
} from '../models/CreateAnEmailDraft200Response';
import {
    type CreateAnEmailDraftRequest,
    CreateAnEmailDraftRequestFromJSON,
    CreateAnEmailDraftRequestToJSON,
} from '../models/CreateAnEmailDraftRequest';
import {
    type OrganizationEnrichment422Response,
    OrganizationEnrichment422ResponseFromJSON,
    OrganizationEnrichment422ResponseToJSON,
} from '../models/OrganizationEnrichment422Response';
import {
    type PeopleApiSearch403Response,
    PeopleApiSearch403ResponseFromJSON,
    PeopleApiSearch403ResponseToJSON,
} from '../models/PeopleApiSearch403Response';
import {
    type PeopleEnrichment429Response,
    PeopleEnrichment429ResponseFromJSON,
    PeopleEnrichment429ResponseToJSON,
} from '../models/PeopleEnrichment429Response';
import {
    type SendEmailNow200Response,
    SendEmailNow200ResponseFromJSON,
    SendEmailNow200ResponseToJSON,
} from '../models/SendEmailNow200Response';
import {
    type SendEmailNowRequest,
    SendEmailNowRequestFromJSON,
    SendEmailNowRequestToJSON,
} from '../models/SendEmailNowRequest';

export interface CheckEmailSendStatusOperationRequest {
    checkEmailSendStatusRequest: CheckEmailSendStatusRequest;
}

export interface CreateAnEmailDraftOperationRequest {
    createAnEmailDraftRequest: CreateAnEmailDraftRequest;
}

export interface SendEmailNowOperationRequest {
    id: string;
    sendEmailNowRequest?: SendEmailNowRequest;
}

/**
 * 
 */
export class EmailerMessagesApi extends runtime.BaseAPI {

    /**
     * Creates request options for checkEmailSendStatus without sending the request
     */
    async checkEmailSendStatusRequestOpts(requestParameters: CheckEmailSendStatusOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['checkEmailSendStatusRequest'] == null) {
            throw new runtime.RequiredError(
                'checkEmailSendStatusRequest',
                'Required parameter "checkEmailSendStatusRequest" was null or undefined when calling checkEmailSendStatus().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // apiKey authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/emailer_messages/email_send_status`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CheckEmailSendStatusRequestToJSON(requestParameters['checkEmailSendStatusRequest']),
        };
    }

    /**
     * Use the Check Email Send Status endpoint to check the current delivery status of an email message. This is typically used after calling the <a href=\"https://docs.apollo.io/reference/send-email-now\" target=\"_blank\">Send Email Now endpoint</a>, since emails are sent asynchronously and a successful send response only means the email was queued. <br><br>You must provide the `id` of the email message. The message must belong to your team, otherwise a `404` is returned. <br><br>The response always includes the message `id`, its current `status`, and a human-readable `message`. The remaining fields depend on the status: <ul> <li> If the email was delivered (`completed`), a `completed_at` timestamp is included. </li> <li> If the email failed (`failed`), a `not_sent_reason`, `failure_reason`, and `failed_at` timestamp may be included. </li> <li> If the email is still being processed (e.g. `drafted` or `scheduled`), a `retry_after_seconds` value is included to indicate how long to wait before checking again. </li> </ul>
     * Check Email Send Status
     */
    async checkEmailSendStatusRaw(requestParameters: CheckEmailSendStatusOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CheckEmailSendStatus200Response>> {
        const requestOptions = await this.checkEmailSendStatusRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CheckEmailSendStatus200ResponseFromJSON(jsonValue));
    }

    /**
     * Use the Check Email Send Status endpoint to check the current delivery status of an email message. This is typically used after calling the <a href=\"https://docs.apollo.io/reference/send-email-now\" target=\"_blank\">Send Email Now endpoint</a>, since emails are sent asynchronously and a successful send response only means the email was queued. <br><br>You must provide the `id` of the email message. The message must belong to your team, otherwise a `404` is returned. <br><br>The response always includes the message `id`, its current `status`, and a human-readable `message`. The remaining fields depend on the status: <ul> <li> If the email was delivered (`completed`), a `completed_at` timestamp is included. </li> <li> If the email failed (`failed`), a `not_sent_reason`, `failure_reason`, and `failed_at` timestamp may be included. </li> <li> If the email is still being processed (e.g. `drafted` or `scheduled`), a `retry_after_seconds` value is included to indicate how long to wait before checking again. </li> </ul>
     * Check Email Send Status
     */
    async checkEmailSendStatus(requestParameters: CheckEmailSendStatusOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CheckEmailSendStatus200Response> {
        const response = await this.checkEmailSendStatusRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for createAnEmailDraft without sending the request
     */
    async createAnEmailDraftRequestOpts(requestParameters: CreateAnEmailDraftOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['createAnEmailDraftRequest'] == null) {
            throw new runtime.RequiredError(
                'createAnEmailDraftRequest',
                'Required parameter "createAnEmailDraftRequest" was null or undefined when calling createAnEmailDraft().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // apiKey authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/emailer_messages`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateAnEmailDraftRequestToJSON(requestParameters['createAnEmailDraftRequest']),
        };
    }

    /**
     * Use the Create an Email Draft endpoint to create a single, unsent email message (an email draft) for a contact. The draft is created with a `drafted` status — this endpoint does not send the email. <br><br>To send the draft after creating it, call the <a href=\"https://docs.apollo.io/reference/send-email-now\" target=\"_blank\">Send Email Now endpoint</a> with the `id` returned in the response. <br><br>You must provide a `contact_id` so Apollo knows who the email is for. Alternatively, to draft a reply within an existing email thread, provide `in_response_to_emailer_message_id` instead and Apollo will infer the contact and recipients from the parent message. <br><br>The email is drafted from the user that owns the API key. That user must have permission to email the contact (i.e. they own the contact or its account), and the contact must not be blocked by your team\'s Do Not Contact (DNC) enforcement settings. <br><br>This endpoint returns the created `emailer_message` object. If the draft is linked to an outreach task, a `task` object is also returned.
     * Create an Email Draft
     */
    async createAnEmailDraftRaw(requestParameters: CreateAnEmailDraftOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CreateAnEmailDraft200Response>> {
        const requestOptions = await this.createAnEmailDraftRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CreateAnEmailDraft200ResponseFromJSON(jsonValue));
    }

    /**
     * Use the Create an Email Draft endpoint to create a single, unsent email message (an email draft) for a contact. The draft is created with a `drafted` status — this endpoint does not send the email. <br><br>To send the draft after creating it, call the <a href=\"https://docs.apollo.io/reference/send-email-now\" target=\"_blank\">Send Email Now endpoint</a> with the `id` returned in the response. <br><br>You must provide a `contact_id` so Apollo knows who the email is for. Alternatively, to draft a reply within an existing email thread, provide `in_response_to_emailer_message_id` instead and Apollo will infer the contact and recipients from the parent message. <br><br>The email is drafted from the user that owns the API key. That user must have permission to email the contact (i.e. they own the contact or its account), and the contact must not be blocked by your team\'s Do Not Contact (DNC) enforcement settings. <br><br>This endpoint returns the created `emailer_message` object. If the draft is linked to an outreach task, a `task` object is also returned.
     * Create an Email Draft
     */
    async createAnEmailDraft(requestParameters: CreateAnEmailDraftOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CreateAnEmailDraft200Response> {
        const response = await this.createAnEmailDraftRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for sendEmailNow without sending the request
     */
    async sendEmailNowRequestOpts(requestParameters: SendEmailNowOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling sendEmailNow().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // apiKey authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/emailer_messages/{id}/send_now`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SendEmailNowRequestToJSON(requestParameters['sendEmailNowRequest']),
        };
    }

    /**
     * Use the Send Email Now endpoint to immediately send an existing email message. This works for emails that are currently in a `drafted`, `scheduled`, or `failed` state — Apollo schedules the email to be sent right away and processes it asynchronously. <br><br>To first create an email draft, use the <a href=\"https://docs.apollo.io/reference/create-an-email-draft\" target=\"_blank\">Create an Email Draft endpoint</a> and then pass the returned `id` to this endpoint. <br><br>The email is sent from the user that owns the API key. That user must have a linked email account on the message, must have permission to send from that email account, and must have permission to email the contact. The contact must also not be blocked by your team\'s Do Not Contact (DNC) enforcement settings, and the user must not have exceeded their daily sending limit. <br><br>Because sending is processed asynchronously, a successful `200` response means the email has been queued for sending — not that it has been delivered. To check whether the email was delivered, poll the <a href=\"https://docs.apollo.io/reference/check-email-send-status\" target=\"_blank\">Check Email Send Status endpoint</a> using the message `id`. <br><br>This endpoint returns the `emailer_message` object. If the message is linked to an outreach task, a `task` object is also returned.
     * Send Email Now
     */
    async sendEmailNowRaw(requestParameters: SendEmailNowOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SendEmailNow200Response>> {
        const requestOptions = await this.sendEmailNowRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SendEmailNow200ResponseFromJSON(jsonValue));
    }

    /**
     * Use the Send Email Now endpoint to immediately send an existing email message. This works for emails that are currently in a `drafted`, `scheduled`, or `failed` state — Apollo schedules the email to be sent right away and processes it asynchronously. <br><br>To first create an email draft, use the <a href=\"https://docs.apollo.io/reference/create-an-email-draft\" target=\"_blank\">Create an Email Draft endpoint</a> and then pass the returned `id` to this endpoint. <br><br>The email is sent from the user that owns the API key. That user must have a linked email account on the message, must have permission to send from that email account, and must have permission to email the contact. The contact must also not be blocked by your team\'s Do Not Contact (DNC) enforcement settings, and the user must not have exceeded their daily sending limit. <br><br>Because sending is processed asynchronously, a successful `200` response means the email has been queued for sending — not that it has been delivered. To check whether the email was delivered, poll the <a href=\"https://docs.apollo.io/reference/check-email-send-status\" target=\"_blank\">Check Email Send Status endpoint</a> using the message `id`. <br><br>This endpoint returns the `emailer_message` object. If the message is linked to an outreach task, a `task` object is also returned.
     * Send Email Now
     */
    async sendEmailNow(requestParameters: SendEmailNowOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SendEmailNow200Response> {
        const response = await this.sendEmailNowRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
