/* tslint:disable */
/* eslint-disable */
/**
 * apollo-rest-api
 * The Apollo API provides programmatic access to [Apollo](https://www.apollo.io/), the all-in-one sales intelligence and engagement platform. Use it to enrich people and company data (individually or in bulk), search Apollo\'s database of over 230 million contacts and 30 million companies, and manage accounts, contacts, deals, sequences, tasks, calls, and conversations in your go-to-market workflows.  ## Base URL  All API requests are made to `https://api.apollo.io/api/v1`.  ## Authentication  - **Apollo users** authenticate with an API key passed in the `x-api-key` request header. See [Create API Keys](https://docs.apollo.io/docs/create-api-key). - **Apollo partners** building integrations on behalf of mutual users authenticate with the [OAuth 2.0 authorization flow](https://docs.apollo.io/docs/use-oauth-20-authorization-flow-to-access-apollo-user-information-partners).  ## Rate limits & credits  Rate limits and credit consumption depend on your [Apollo pricing plan](https://docs.apollo.io/docs/api-pricing). Check your current limits and usage with the [View API Usage Stats and Rate Limits](https://docs.apollo.io/reference/view-api-usage-stats) endpoint. For more details, see [Rate Limits](https://docs.apollo.io/reference/rate-limits) and the [API FAQs](https://docs.apollo.io/docs/apollo-api-faqs).  New to the API? Start with the [Apollo API Overview](https://docs.apollo.io/docs/apollo-api-overview).
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type OrganizationEnrichment422Response,
    OrganizationEnrichment422ResponseFromJSON,
    OrganizationEnrichment422ResponseToJSON,
} from '../models/OrganizationEnrichment422Response';
import {
    type OrganizationJobsPostings200Response,
    OrganizationJobsPostings200ResponseFromJSON,
    OrganizationJobsPostings200ResponseToJSON,
} from '../models/OrganizationJobsPostings200Response';
import {
    type OrganizationSearch200Response,
    OrganizationSearch200ResponseFromJSON,
    OrganizationSearch200ResponseToJSON,
} from '../models/OrganizationSearch200Response';
import {
    type PeopleApiSearch200Response,
    PeopleApiSearch200ResponseFromJSON,
    PeopleApiSearch200ResponseToJSON,
} from '../models/PeopleApiSearch200Response';
import {
    type PeopleApiSearch403Response,
    PeopleApiSearch403ResponseFromJSON,
    PeopleApiSearch403ResponseToJSON,
} from '../models/PeopleApiSearch403Response';
import {
    type PeopleEnrichment429Response,
    PeopleEnrichment429ResponseFromJSON,
    PeopleEnrichment429ResponseToJSON,
} from '../models/PeopleEnrichment429Response';

export interface GetOrganizationsidRequest {
    id: string;
}

export interface GetPeopleidRequest {
    id: string;
}

export interface NewsArticlesSearchRequest {
    organizationIds: Array<string>;
    categories?: Array<string>;
    publishedAtMin?: Date;
    publishedAtMax?: Date;
    page?: number;
    perPage?: number;
}

export interface OrganizationJobsPostingsRequest {
    organizationId: string;
    page?: number;
    perPage?: number;
}

export interface OrganizationSearchRequest {
    qOrganizationDomainsList?: Array<string>;
    organizationNumEmployeesRanges?: Array<string>;
    organizationLocations?: Array<string>;
    organizationNotLocations?: Array<string>;
    revenueRangeMin?: number;
    revenueRangeMax?: number;
    currentlyUsingAnyOfTechnologyUids?: Array<string>;
    qOrganizationKeywordTags?: Array<string>;
    qOrganizationName?: string;
    organizationIds?: Array<string>;
    latestFundingAmountRangeMin?: number;
    latestFundingAmountRangeMax?: number;
    totalFundingRangeMin?: number;
    totalFundingRangeMax?: number;
    latestFundingDateRangeMin?: Date;
    latestFundingDateRangeMax?: Date;
    qOrganizationJobTitles?: Array<string>;
    organizationJobLocations?: Array<string>;
    organizationNumJobsRangeMin?: number;
    organizationNumJobsRangeMax?: number;
    organizationJobPostedAtRangeMin?: Date;
    organizationJobPostedAtRangeMax?: Date;
    page?: number;
    perPage?: number;
}

export interface PeopleApiSearchRequest {
    personTitles?: Array<string>;
    includeSimilarTitles?: boolean;
    qKeywords?: string;
    personLocations?: Array<string>;
    personSeniorities?: Array<string>;
    organizationLocations?: Array<string>;
    qOrganizationDomainsList?: Array<string>;
    contactEmailStatus?: Array<string>;
    organizationIds?: Array<string>;
    organizationNumEmployeesRanges?: Array<string>;
    revenueRangeMin?: number;
    revenueRangeMax?: number;
    currentlyUsingAllOfTechnologyUids?: Array<string>;
    currentlyUsingAnyOfTechnologyUids?: Array<string>;
    currentlyNotUsingAnyOfTechnologyUids?: Array<string>;
    qOrganizationJobTitles?: Array<string>;
    organizationJobLocations?: Array<string>;
    organizationNumJobsRangeMin?: number;
    organizationNumJobsRangeMax?: number;
    organizationJobPostedAtRangeMin?: Date;
    organizationJobPostedAtRangeMax?: Date;
    page?: number;
    perPage?: number;
}

/**
 * 
 */
export class SearchApi extends runtime.BaseAPI {

    /**
     * Creates request options for getOrganizationsid without sending the request
     */
    async getOrganizationsidRequestOpts(requestParameters: GetOrganizationsidRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getOrganizationsid().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // apiKey authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/organizations/{id}`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * This endpoint consumes Apollo credits per record when data is returned. Learn more about [API pricing and credits](https://docs.apollo.io/docs/api-pricing).  <a href=\"https://knowledge.apollo.io/hc/en-us/articles/4412658766477-Search-for-Companies\" target=\"_blank\">Organizations</a> are companies you haven\'t yet saved as accounts on Apollo.<br><br>Use the Get Complete Organization Info endpoint to retrieve complete details about an organization in Apollo.<br><br>This endpoint requires a master API key. If you call the endpoint without a master key, you receive a `403` response. Check out <a href=\"https://docs.apollo.io/docs/create-api-key\" target=\"_blank\">Create an API Key</a> to learn how to create a master key.
     * Get Complete Organization Info
     */
    async getOrganizationsidRaw(requestParameters: GetOrganizationsidRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.getOrganizationsidRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * This endpoint consumes Apollo credits per record when data is returned. Learn more about [API pricing and credits](https://docs.apollo.io/docs/api-pricing).  <a href=\"https://knowledge.apollo.io/hc/en-us/articles/4412658766477-Search-for-Companies\" target=\"_blank\">Organizations</a> are companies you haven\'t yet saved as accounts on Apollo.<br><br>Use the Get Complete Organization Info endpoint to retrieve complete details about an organization in Apollo.<br><br>This endpoint requires a master API key. If you call the endpoint without a master key, you receive a `403` response. Check out <a href=\"https://docs.apollo.io/docs/create-api-key\" target=\"_blank\">Create an API Key</a> to learn how to create a master key.
     * Get Complete Organization Info
     */
    async getOrganizationsid(requestParameters: GetOrganizationsidRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.getOrganizationsidRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for getPeopleid without sending the request
     */
    async getPeopleidRequestOpts(requestParameters: GetPeopleidRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getPeopleid().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // apiKey authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/people/{id}`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * This endpoint consumes Apollo credits per record when data is returned. Learn more about [API pricing and credits](https://docs.apollo.io/docs/api-pricing).  Use the Get Complete Person Info endpoint to retrieve complete details about a person in the Apollo database, including employment history, location, and the full details of the person\'s current organization.<br><br>This endpoint requires a master API key. If you call this endpoint without a master key, you receive a `403` response. Check out <a href=\"https://docs.apollo.io/docs/create-api-key\">Create an API Key</a> to learn how to create a master key.
     * Get Complete Person Info
     */
    async getPeopleidRaw(requestParameters: GetPeopleidRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.getPeopleidRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * This endpoint consumes Apollo credits per record when data is returned. Learn more about [API pricing and credits](https://docs.apollo.io/docs/api-pricing).  Use the Get Complete Person Info endpoint to retrieve complete details about a person in the Apollo database, including employment history, location, and the full details of the person\'s current organization.<br><br>This endpoint requires a master API key. If you call this endpoint without a master key, you receive a `403` response. Check out <a href=\"https://docs.apollo.io/docs/create-api-key\">Create an API Key</a> to learn how to create a master key.
     * Get Complete Person Info
     */
    async getPeopleid(requestParameters: GetPeopleidRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.getPeopleidRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for newsArticlesSearch without sending the request
     */
    async newsArticlesSearchRequestOpts(requestParameters: NewsArticlesSearchRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['organizationIds'] == null) {
            throw new runtime.RequiredError(
                'organizationIds',
                'Required parameter "organizationIds" was null or undefined when calling newsArticlesSearch().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['organizationIds'] != null) {
            queryParameters['organization_ids[]'] = requestParameters['organizationIds'];
        }

        if (requestParameters['categories'] != null) {
            queryParameters['categories[]'] = requestParameters['categories'];
        }

        if (requestParameters['publishedAtMin'] != null) {
            queryParameters['published_at[min]'] = (requestParameters['publishedAtMin'] as any).toISOString().substring(0,10);
        }

        if (requestParameters['publishedAtMax'] != null) {
            queryParameters['published_at[max]'] = (requestParameters['publishedAtMax'] as any).toISOString().substring(0,10);
        }

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['perPage'] != null) {
            queryParameters['per_page'] = requestParameters['perPage'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // apiKey authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/news_articles/search`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * This endpoint consumes Apollo credits per page when data is returned. Learn more about [API pricing and credits](https://docs.apollo.io/docs/api-pricing).  <a href=\"https://knowledge.apollo.io/hc/en-us/articles/4412665755661-Search-Filters-Overview#news\" target=\"_blank\">News</a> includes articles related to companies in Apollo.<br><br>Use the News Articles Search endpoint to find news articles related to specific companies. Several filters are available to help narrow your search.
     * News Articles Search
     */
    async newsArticlesSearchRaw(requestParameters: NewsArticlesSearchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.newsArticlesSearchRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * This endpoint consumes Apollo credits per page when data is returned. Learn more about [API pricing and credits](https://docs.apollo.io/docs/api-pricing).  <a href=\"https://knowledge.apollo.io/hc/en-us/articles/4412665755661-Search-Filters-Overview#news\" target=\"_blank\">News</a> includes articles related to companies in Apollo.<br><br>Use the News Articles Search endpoint to find news articles related to specific companies. Several filters are available to help narrow your search.
     * News Articles Search
     */
    async newsArticlesSearch(requestParameters: NewsArticlesSearchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.newsArticlesSearchRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for organizationJobsPostings without sending the request
     */
    async organizationJobsPostingsRequestOpts(requestParameters: OrganizationJobsPostingsRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['organizationId'] == null) {
            throw new runtime.RequiredError(
                'organizationId',
                'Required parameter "organizationId" was null or undefined when calling organizationJobsPostings().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['perPage'] != null) {
            queryParameters['per_page'] = requestParameters['perPage'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // apiKey authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/organizations/{organization_id}/job_postings`;
        urlPath = urlPath.replace('{organization_id}', encodeURIComponent(String(requestParameters['organizationId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * This endpoint consumes Apollo credits per page when data is returned. Learn more about [API pricing and credits](https://docs.apollo.io/docs/api-pricing).  <a href=\"https://knowledge.apollo.io/hc/en-us/articles/4412658766477-Search-for-Companies\" target=\"_blank\">Organizations</a> are companies you haven\'t yet saved as accounts on Apollo.<br><br>Use the Organization Job Postings endpoint to retrieve the current job postings for companies. This can help you identify companies that are growing headcount in areas that are strategically important for you.<br><br>To protect Apollo\'s performance for all users, this endpoint has a display limit of 10,000 records.
     * Organization Job Postings
     */
    async organizationJobsPostingsRaw(requestParameters: OrganizationJobsPostingsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<OrganizationJobsPostings200Response>> {
        const requestOptions = await this.organizationJobsPostingsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => OrganizationJobsPostings200ResponseFromJSON(jsonValue));
    }

    /**
     * This endpoint consumes Apollo credits per page when data is returned. Learn more about [API pricing and credits](https://docs.apollo.io/docs/api-pricing).  <a href=\"https://knowledge.apollo.io/hc/en-us/articles/4412658766477-Search-for-Companies\" target=\"_blank\">Organizations</a> are companies you haven\'t yet saved as accounts on Apollo.<br><br>Use the Organization Job Postings endpoint to retrieve the current job postings for companies. This can help you identify companies that are growing headcount in areas that are strategically important for you.<br><br>To protect Apollo\'s performance for all users, this endpoint has a display limit of 10,000 records.
     * Organization Job Postings
     */
    async organizationJobsPostings(requestParameters: OrganizationJobsPostingsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<OrganizationJobsPostings200Response> {
        const response = await this.organizationJobsPostingsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for organizationSearch without sending the request
     */
    async organizationSearchRequestOpts(requestParameters: OrganizationSearchRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['qOrganizationDomainsList'] != null) {
            queryParameters['q_organization_domains_list[]'] = requestParameters['qOrganizationDomainsList'];
        }

        if (requestParameters['organizationNumEmployeesRanges'] != null) {
            queryParameters['organization_num_employees_ranges[]'] = requestParameters['organizationNumEmployeesRanges'];
        }

        if (requestParameters['organizationLocations'] != null) {
            queryParameters['organization_locations[]'] = requestParameters['organizationLocations'];
        }

        if (requestParameters['organizationNotLocations'] != null) {
            queryParameters['organization_not_locations[]'] = requestParameters['organizationNotLocations'];
        }

        if (requestParameters['revenueRangeMin'] != null) {
            queryParameters['revenue_range[min]'] = requestParameters['revenueRangeMin'];
        }

        if (requestParameters['revenueRangeMax'] != null) {
            queryParameters['revenue_range[max]'] = requestParameters['revenueRangeMax'];
        }

        if (requestParameters['currentlyUsingAnyOfTechnologyUids'] != null) {
            queryParameters['currently_using_any_of_technology_uids[]'] = requestParameters['currentlyUsingAnyOfTechnologyUids'];
        }

        if (requestParameters['qOrganizationKeywordTags'] != null) {
            queryParameters['q_organization_keyword_tags[]'] = requestParameters['qOrganizationKeywordTags'];
        }

        if (requestParameters['qOrganizationName'] != null) {
            queryParameters['q_organization_name'] = requestParameters['qOrganizationName'];
        }

        if (requestParameters['organizationIds'] != null) {
            queryParameters['organization_ids[]'] = requestParameters['organizationIds'];
        }

        if (requestParameters['latestFundingAmountRangeMin'] != null) {
            queryParameters['latest_funding_amount_range[min]'] = requestParameters['latestFundingAmountRangeMin'];
        }

        if (requestParameters['latestFundingAmountRangeMax'] != null) {
            queryParameters['latest_funding_amount_range[max]'] = requestParameters['latestFundingAmountRangeMax'];
        }

        if (requestParameters['totalFundingRangeMin'] != null) {
            queryParameters['total_funding_range[min]'] = requestParameters['totalFundingRangeMin'];
        }

        if (requestParameters['totalFundingRangeMax'] != null) {
            queryParameters['total_funding_range[max]'] = requestParameters['totalFundingRangeMax'];
        }

        if (requestParameters['latestFundingDateRangeMin'] != null) {
            queryParameters['latest_funding_date_range[min]'] = (requestParameters['latestFundingDateRangeMin'] as any).toISOString().substring(0,10);
        }

        if (requestParameters['latestFundingDateRangeMax'] != null) {
            queryParameters['latest_funding_date_range[max]'] = (requestParameters['latestFundingDateRangeMax'] as any).toISOString().substring(0,10);
        }

        if (requestParameters['qOrganizationJobTitles'] != null) {
            queryParameters['q_organization_job_titles[]'] = requestParameters['qOrganizationJobTitles'];
        }

        if (requestParameters['organizationJobLocations'] != null) {
            queryParameters['organization_job_locations[]'] = requestParameters['organizationJobLocations'];
        }

        if (requestParameters['organizationNumJobsRangeMin'] != null) {
            queryParameters['organization_num_jobs_range[min]'] = requestParameters['organizationNumJobsRangeMin'];
        }

        if (requestParameters['organizationNumJobsRangeMax'] != null) {
            queryParameters['organization_num_jobs_range[max]'] = requestParameters['organizationNumJobsRangeMax'];
        }

        if (requestParameters['organizationJobPostedAtRangeMin'] != null) {
            queryParameters['organization_job_posted_at_range[min]'] = (requestParameters['organizationJobPostedAtRangeMin'] as any).toISOString().substring(0,10);
        }

        if (requestParameters['organizationJobPostedAtRangeMax'] != null) {
            queryParameters['organization_job_posted_at_range[max]'] = (requestParameters['organizationJobPostedAtRangeMax'] as any).toISOString().substring(0,10);
        }

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['perPage'] != null) {
            queryParameters['per_page'] = requestParameters['perPage'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // apiKey authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/mixed_companies/search`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * This endpoint consumes Apollo credits per page when data is returned. Learn more about [API pricing and credits](https://docs.apollo.io/docs/api-pricing).  <a href=\"https://knowledge.apollo.io/hc/en-us/articles/4412658766477-Search-for-Companies\" target=\"_blank\">Organizations</a> are companies you haven\'t yet saved as accounts on Apollo.<br><br>Use the Organization Search endpoint to find companies in the Apollo database. Several filters are available to help narrow your search.<br><br>To protect Apollo\'s performance for all users, this endpoint has a display limit of 50,000 records (100 records per page, up to 500 pages). Add more filters to narrow your search results as much as possible.
     * Organization Search
     */
    async organizationSearchRaw(requestParameters: OrganizationSearchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<OrganizationSearch200Response>> {
        const requestOptions = await this.organizationSearchRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => OrganizationSearch200ResponseFromJSON(jsonValue));
    }

    /**
     * This endpoint consumes Apollo credits per page when data is returned. Learn more about [API pricing and credits](https://docs.apollo.io/docs/api-pricing).  <a href=\"https://knowledge.apollo.io/hc/en-us/articles/4412658766477-Search-for-Companies\" target=\"_blank\">Organizations</a> are companies you haven\'t yet saved as accounts on Apollo.<br><br>Use the Organization Search endpoint to find companies in the Apollo database. Several filters are available to help narrow your search.<br><br>To protect Apollo\'s performance for all users, this endpoint has a display limit of 50,000 records (100 records per page, up to 500 pages). Add more filters to narrow your search results as much as possible.
     * Organization Search
     */
    async organizationSearch(requestParameters: OrganizationSearchRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<OrganizationSearch200Response> {
        const response = await this.organizationSearchRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for peopleApiSearch without sending the request
     */
    async peopleApiSearchRequestOpts(requestParameters: PeopleApiSearchRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['personTitles'] != null) {
            queryParameters['person_titles[]'] = requestParameters['personTitles'];
        }

        if (requestParameters['includeSimilarTitles'] != null) {
            queryParameters['include_similar_titles'] = requestParameters['includeSimilarTitles'];
        }

        if (requestParameters['qKeywords'] != null) {
            queryParameters['q_keywords'] = requestParameters['qKeywords'];
        }

        if (requestParameters['personLocations'] != null) {
            queryParameters['person_locations[]'] = requestParameters['personLocations'];
        }

        if (requestParameters['personSeniorities'] != null) {
            queryParameters['person_seniorities[]'] = requestParameters['personSeniorities'];
        }

        if (requestParameters['organizationLocations'] != null) {
            queryParameters['organization_locations[]'] = requestParameters['organizationLocations'];
        }

        if (requestParameters['qOrganizationDomainsList'] != null) {
            queryParameters['q_organization_domains_list[]'] = requestParameters['qOrganizationDomainsList'];
        }

        if (requestParameters['contactEmailStatus'] != null) {
            queryParameters['contact_email_status[]'] = requestParameters['contactEmailStatus'];
        }

        if (requestParameters['organizationIds'] != null) {
            queryParameters['organization_ids[]'] = requestParameters['organizationIds'];
        }

        if (requestParameters['organizationNumEmployeesRanges'] != null) {
            queryParameters['organization_num_employees_ranges[]'] = requestParameters['organizationNumEmployeesRanges'];
        }

        if (requestParameters['revenueRangeMin'] != null) {
            queryParameters['revenue_range[min]'] = requestParameters['revenueRangeMin'];
        }

        if (requestParameters['revenueRangeMax'] != null) {
            queryParameters['revenue_range[max]'] = requestParameters['revenueRangeMax'];
        }

        if (requestParameters['currentlyUsingAllOfTechnologyUids'] != null) {
            queryParameters['currently_using_all_of_technology_uids[]'] = requestParameters['currentlyUsingAllOfTechnologyUids'];
        }

        if (requestParameters['currentlyUsingAnyOfTechnologyUids'] != null) {
            queryParameters['currently_using_any_of_technology_uids[]'] = requestParameters['currentlyUsingAnyOfTechnologyUids'];
        }

        if (requestParameters['currentlyNotUsingAnyOfTechnologyUids'] != null) {
            queryParameters['currently_not_using_any_of_technology_uids[]'] = requestParameters['currentlyNotUsingAnyOfTechnologyUids'];
        }

        if (requestParameters['qOrganizationJobTitles'] != null) {
            queryParameters['q_organization_job_titles[]'] = requestParameters['qOrganizationJobTitles'];
        }

        if (requestParameters['organizationJobLocations'] != null) {
            queryParameters['organization_job_locations[]'] = requestParameters['organizationJobLocations'];
        }

        if (requestParameters['organizationNumJobsRangeMin'] != null) {
            queryParameters['organization_num_jobs_range[min]'] = requestParameters['organizationNumJobsRangeMin'];
        }

        if (requestParameters['organizationNumJobsRangeMax'] != null) {
            queryParameters['organization_num_jobs_range[max]'] = requestParameters['organizationNumJobsRangeMax'];
        }

        if (requestParameters['organizationJobPostedAtRangeMin'] != null) {
            queryParameters['organization_job_posted_at_range[min]'] = (requestParameters['organizationJobPostedAtRangeMin'] as any).toISOString().substring(0,10);
        }

        if (requestParameters['organizationJobPostedAtRangeMax'] != null) {
            queryParameters['organization_job_posted_at_range[max]'] = (requestParameters['organizationJobPostedAtRangeMax'] as any).toISOString().substring(0,10);
        }

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['perPage'] != null) {
            queryParameters['per_page'] = requestParameters['perPage'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // apiKey authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/mixed_people/api_search`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * This endpoint doesn\'t consume Apollo credits. Learn more about [API pricing and credits](https://docs.apollo.io/docs/api-pricing).  <a href=\"https://knowledge.apollo.io/hc/en-us/articles/4412658716941-Search-for-People\" target=\"_blank\">People</a> are net-new prospects you haven\'t yet saved as contacts on Apollo.<br><br>Use the People API Search endpoint to find new prospects. Several filters are available to help narrow your search. This endpoint doesn\'t return email addresses or phone numbers. Use the <a href=\"https://docs.apollo.io/reference/people-enrichment\">People Enrichment</a> or <a href=\"https://docs.apollo.io/reference/bulk-people-enrichment\">Bulk People Enrichment</a> endpoints to enrich data.<br><br>This endpoint requires a master API key. Check out <a href=\"https://docs.apollo.io/docs/create-api-key\" target=\"_blank\">Create an API Key</a> to learn how to create a master key.<br><br>To protect Apollo\'s performance for all users, this endpoint has a display limit of 50,000 records (100 records per page, up to 500 pages). Add more filters to narrow your search results as much as possible.
     * People API Search
     */
    async peopleApiSearchRaw(requestParameters: PeopleApiSearchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PeopleApiSearch200Response>> {
        const requestOptions = await this.peopleApiSearchRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PeopleApiSearch200ResponseFromJSON(jsonValue));
    }

    /**
     * This endpoint doesn\'t consume Apollo credits. Learn more about [API pricing and credits](https://docs.apollo.io/docs/api-pricing).  <a href=\"https://knowledge.apollo.io/hc/en-us/articles/4412658716941-Search-for-People\" target=\"_blank\">People</a> are net-new prospects you haven\'t yet saved as contacts on Apollo.<br><br>Use the People API Search endpoint to find new prospects. Several filters are available to help narrow your search. This endpoint doesn\'t return email addresses or phone numbers. Use the <a href=\"https://docs.apollo.io/reference/people-enrichment\">People Enrichment</a> or <a href=\"https://docs.apollo.io/reference/bulk-people-enrichment\">Bulk People Enrichment</a> endpoints to enrich data.<br><br>This endpoint requires a master API key. Check out <a href=\"https://docs.apollo.io/docs/create-api-key\" target=\"_blank\">Create an API Key</a> to learn how to create a master key.<br><br>To protect Apollo\'s performance for all users, this endpoint has a display limit of 50,000 records (100 records per page, up to 500 pages). Add more filters to narrow your search results as much as possible.
     * People API Search
     */
    async peopleApiSearch(requestParameters: PeopleApiSearchRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PeopleApiSearch200Response> {
        const response = await this.peopleApiSearchRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
